SET PATH=c:\COMPS\DJGPP\BIN;c:\COMPS\GPM\BIN;%PATH%
SET DJGPP=c:\COMPS\DJGPP\DJGPP.ENV
SET TEMP=c:\COMPS\DJGPP\TMP
SET M2LIB=c:\COMPS\GPM\GPMLIB;c:\COMPS\GPM\ISOLIB
SET M2SYM=c:\COMPS\GPM\GPMSYM;c:\COMPS\GPM\ISOSYM
