SET PATH=c:\COMPS\DJGPP\BIN;c:\COMPS\GPMPC
SET DJGPP=c:\COMPS\DJGPP\DJGPP.ENV
SET TEMP=c:\COMPS\DJGPP\TMP
SET M2LIB=c:\COMPS\GPMPC\M2LIB;c:\COMPS\GPMPC\M2LIB\SVGA;c:\COMPS\GPMPC\M2LIB\VGA
SET M2SYM=c:\COMPS\GPMPC\M2SYM
