//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: Livrus.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_Livrus_H__
#define __WDR_Livrus_H__

#if defined(__GNUG__) && !defined(__APPLE__)
    #pragma interface "Livrus_wdr.h"
#endif

// Include wxWindows' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>

// Declare window functions

#define LAB_CODIGO 10000
#define EDT_CODIGO 10001
#define LAB_DESCRICAO 10002
#define EDT_DESCRICAO 10003
#define BTN_PESQUISAR 10004
#define BTN_ANTERIOR 10005
#define BTN_PROXIMO 10006
#define BTN_SALVAR 10007
#define BTN_EXCLUIR 10008
#define BTN_LIMPAR 10009
#define BTN_FECHAR 10010
wxSizer *frmCadAssuntos( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

wxSizer *frmCadAutores( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_PANEL 10011
#define ID_BUTTON 10012
#define ID_GRID 10013
wxSizer *frmConAssuntos( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_STATICBITMAP 10014
wxSizer *frmSplash( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define LAB_LOGIN 10015
#define EDT_LOGIN 10016
#define LAB_SENHA 10017
#define EDT_SENHA 10018
#define BTN_LOGIN 10019
#define BTN_CANCELAR 10020
wxSizer *frmLogin( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_TEXT 10021
#define BTN_OK 10022
wxSizer *frmSobre( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define EDT_SENHAATUAL 10023
#define EDT_NOVASENHA 10024
#define EDT_CONFIRMSENHA 10025
wxSizer *frmAlterarSenha( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

wxSizer *frmConVendas( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

#define MNU_CADASTROS 10
#define MNU_CADASSUNTOS 11
#define MNU_CADAUTORES 12
#define MNU_CADENDERECOS 13
#define MNU_CADIDIOMAS 14
#define MNU_CADPAISES 15
#define MNU_CADPROFISSOES 16
#define ID_MENU 10026
#define MNU_CADCLIENTES 17
#define MNU_CADLIVROS 18
#define MNU_PESQUISAS 20
#define MNU_CONASSUNTOS 21
#define MNU_CONAUTORES 22
#define MNU_CONENDERECOS 23
#define MNU_CONIDIOMAS 24
#define MNU_CONPAISES 25
#define MNU_CONPROFISSOES 26
#define MNU_CONCLIENTES 27
#define MNU_CONLIVROS 28
#define MNU_VENDAS 30
#define MNU_VENDER 31
#define MNU_VENDASREALIZADAS 32
#define MNU_JANELAS 40
#define MNU_LADOALADOHORIZONTAL 41
#define MNU_LADOALADOVERTICAL 42
#define MNU_EMCASCATA 43
#define MNU_ORGANIZARICONES 44
#define MNU_OPCOES 50
#define MNU_ALTERARSENHA 51
#define MNU_SOBRE 52
#define MNU_SAIR 53
wxMenuBar *MontaBarraDeMenu();

// Declare toolbar functions

#define TLB_CLIENTE 0
#define TLB_LIVRO 1
#define TLB_VENDAS 2
#define TLB_SOBRE 3
#define TLB_SAIR 4
void MontaBarraDeFerramentas( wxToolBar *parent );

// Declare bitmap functions

#define BMP_CLIENTE 0
#define BMP_LIVRO 1
#define BMP_LIVROS 2
#define BMP_SOBRE 3
#define BMP_SAIR 4
#define BMP_LOGIN 5
#define BMP_SPLASH 6
#define BMP_LIVRUSVIRTUS 7
wxBitmap ListaBitmaps( size_t index );

#endif

// End of generated file
