/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget *create_frmPrincipal (void);
GtkWidget *create_frmCadastros (void);
GtkWidget *create_frmConsultas (void);
GtkWidget *create_frmLogin (void);
GtkWidget *create_frmSplash (void);
GtkWidget *create_frmAlterarSenha (void);
GtkWidget *create_frmSobre (void);
GtkWidget *create_frmCadEnderecos (void);
GtkWidget *create_frmCadClientes (void);
GtkWidget *create_frmCadLivros (void);
GtkWidget *create_frmVenderLivros (void);
GtkWidget *create_frmConVendas (void);
