sCaminho = "C:/LivrusVirtus/wxWindows/wxLua/"

require(sCaminho .. "Resource.lua")
require(sCaminho .. "RotinasGlobais.lua")
require(sCaminho .. "ConsultasSQL.lua")
require(sCaminho .. "Principal.lua")
require(sCaminho .. "Login.lua")
require(sCaminho .. "Splash.lua")
require(sCaminho .. "Sobre.lua")
require(sCaminho .. "Filha.lua")
require(sCaminho .. "Cadastros.lua")
require(sCaminho .. "CadAssuntos.lua")
require(sCaminho .. "CadAutores.lua")
require(sCaminho .. "CadEditoras.lua")
require(sCaminho .. "CadEnderecos.lua")
require(sCaminho .. "CadIdiomas.lua")
require(sCaminho .. "CadPaises.lua")
require(sCaminho .. "CadProfissoes.lua")
require(sCaminho .. "CadClientes.lua")
require(sCaminho .. "CadLivros.lua")
require(sCaminho .. "VenderLivros.lua")
require(sCaminho .. "ConVendas.lua")
require(sCaminho .. "Consultas.lua")
require(sCaminho .. "ConAssuntos.lua")
require(sCaminho .. "ConAutores.lua")
require(sCaminho .. "ConEditoras.lua")
require(sCaminho .. "ConEnderecos.lua")
require(sCaminho .. "ConIdiomas.lua")
require(sCaminho .. "ConPaises.lua")
require(sCaminho .. "ConProfissoes.lua")
require(sCaminho .. "ConClientes.lua")
require(sCaminho .. "ConLivros.lua")
require(sCaminho .. "AlterarSenha.lua")

function main()
  frmSplash:Show(wx.TRUE)
end

main()
