// generated by Fast Light User Interface Designer (fluid) version 1.0106

#include "Livrus.h"

int main(int argc, char **argv) {
  return Fl::run();
}

#include <FL/Fl_Image.H>
static unsigned char idata_Livrus[] =
"\300\300\300\300\300\300\300\300\300\300\300\300\300\300\300\300\300\300\300\
\300\300\300\300\300\300\300\300\0\377\377\0\377\377\0\377\377\0\0\0\300\300\
\300\300\300\300\300\300\300\300\300\300\300\300\300\300\300\300\300\300\300\
\300\300\300\300\300\300\300\300\300\300\300\300\300\300\300\0\0\0\0\0\0\0\0\
\0\0\0\0\300\300\300\300\300\300\300\300\300\300\300\300\300\300\300\300\300\
\300\300\300\300\300\300\300\300\300\300\300\300\300\300\300\300\300\300\300\
\0\377\377\0\377\377\0\377\377\0\0\0\300\300\300\300\300\300\300\300\300\300\
\300\300\300\300\300\300\300\300\300\300\300\300\300\300\377\377\0\377\377\0\
\377\377\0\0\0\0\0\377\377\0\377\377\0\0\0\0\0\0\300\300\300\300\300\300\300\
\300\300\300\300\300\300\300\300\200\200\200\0\0\0\0\0\0\377\377\0\377\377\0\
\0\0\0\0\0\0\0\377\377\0\377\377\0\377\377\0\0\0\377\377\377\377\377\377\0\0\
\0\300\300\300\300\300\300\0\0\0\0\377\0\200\200\200\377\377\0\377\377\0\377\
\377\0\0\0\0\0\377\377\0\377\377\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\300\300\300\0\
\0\0\0\0\0\0\377\0\200\200\200\377\377\0\377\377\0\0\0\0\0\0\0\0\377\377\0\
\377\377\0\377\377\0\0\0\377\377\377\377\377\377\0\0\0\300\300\300\0\0\0\0\
\377\0\0\377\0\0\0\0\377\377\0\377\377\0\377\377\0\0\0\0\0\377\377\0\0\0\0\0\
\0\0\0\0\377\377\377\377\377\377\0\0\0\200\200\200\0\377\0\0\377\0\0\377\0\0\
\0\0\377\377\0\0\0\0\0\0\0\0\0\0\0\377\377\0\377\377\0\377\377\0\0\0\377\377\
\377\377\377\377\0\0\0\0\0\0\0\377\0\0\377\0\0\377\0\0\0\0\377\377\0\0\0\0\0\
\0\0\0\0\0\0\377\377\0\377\377\0\377\377\0\0\0\377\377\377\377\377\377\0\0\0\
\0\0\0\0\377\0\0\377\0\200\200\200\0\0\0\377\377\0\0\0\0\377\377\0\0\0\0\0\
\377\377\0\377\377\0\377\377\0\0\0\377\377\377\377\377\377\0\0\0\200\200\200\
\0\377\0\0\377\0\0\0\0\300\300\300\377\377\0\0\0\0\377\377\0\0\0\0\0\377\377\
\0\377\377\0\377\377\0\0\0\377\377\377\377\377\377\0\0\0\0\377\0\0\377\0\0\
\377\0\0\0\0\300\300\300\377\377\0\0\0\0\0\0\0\0\0\0\0\377\377\0\377\377\0\0\
\0\0\0\0\377\377\377\377\377\377\0\0\0\0\377\0\0\0\0\0\0\0\0\0\0\300\300\300\
\377\377\0\377\377\0\0\0\0\0\0\0\0\377\377\0\377\377\0\377\377\0\0\0\377\377\
\377\377\377\377\0\0\0\0\377\0\0\377\0\0\0\0\300\300\300\300\300\300\377\377\
\0\0\0\0\0\0\0\0\0\0\0\377\377\0\377\377\0\377\377\0\0\0\377\377\377\377\377\
\377\0\0\0\0\0\0\0\0\0\0\0\0\300\300\300\300\300\300\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0";
static Fl_RGB_Image image_Livrus(idata_Livrus, 16, 16, 3, 0);

Fl_Menu_Item CfrmPrincipal::menu_BarraDeMenu[] = {
 {"&Cadastros", 0,  0, 0, 64, 0, 0, 14, 56},
 {"&Assuntos", 0,  (Fl_Callback*)frmPrincipal_mnuCadAssuntos_cb, 0, 0, 0, 0, 14, 56},
 {"A&utores", 0,  (Fl_Callback*)frmPrincipal_mnuCadAutores_cb, 0, 0, 0, 0, 14, 56},
 {"&Editoras", 0,  (Fl_Callback*)frmPrincipal_mnuCadEditoras_cb, 0, 0, 0, 0, 14, 56},
 {"E&ndere\347os", 0,  (Fl_Callback*)frmPrincipal_mnuCadEnderecos_cb, 0, 0, 0, 0, 14, 56},
 {"&Idiomas", 0,  (Fl_Callback*)frmPrincipal_mnuCadIdiomas_cb, 0, 0, 0, 0, 14, 56},
 {"&Pa\355ses", 0,  (Fl_Callback*)frmPrincipal_mnuCadPaises_cb, 0, 0, 0, 0, 14, 56},
 {"P&rofiss\365""es", 0,  (Fl_Callback*)frmPrincipal_mnuCadProfissoes_cb, 0, 128, 0, 0, 14, 56},
 {"&Clientes", 0,  (Fl_Callback*)frmPrincipal_mnuCadClientes_cb, 0, 0, 0, 0, 14, 56},
 {"&Livros", 0,  (Fl_Callback*)frmPrincipal_mnuCadLivros_cb, 0, 0, 0, 0, 14, 56},
 {0,0,0,0,0,0,0,0,0},
 {"&Pesquisas", 0,  0, 0, 64, 0, 0, 14, 56},
 {"&Assuntos", 0,  (Fl_Callback*)frmPrincipal_mnuConAssuntos_cb, 0, 0, 0, 0, 14, 56},
 {"A&utores", 0,  (Fl_Callback*)frmPrincipal_mnuConAutores_cb, 0, 0, 0, 0, 14, 56},
 {"&Editoras", 0,  (Fl_Callback*)frmPrincipal_mnuConEditoras_cb, 0, 0, 0, 0, 14, 56},
 {"E&ndere\347os", 0,  (Fl_Callback*)frmPrincipal_mnuConEnderecos_cb, 0, 0, 0, 0, 14, 56},
 {"&Idiomas", 0,  (Fl_Callback*)frmPrincipal_mnuConIdiomas_cb, 0, 0, 0, 0, 14, 56},
 {"&Pa\355ses", 0,  (Fl_Callback*)frmPrincipal_mnuConPaises_cb, 0, 0, 0, 0, 14, 56},
 {"P&rofiss\365""es", 0,  (Fl_Callback*)frmPrincipal_mnuConProfissoes_cb, 0, 128, 0, 0, 14, 56},
 {"&Clientes", 0,  (Fl_Callback*)frmPrincipal_mnuConClientes_cb, 0, 0, 0, 0, 14, 56},
 {"&Livros", 0,  (Fl_Callback*)frmPrincipal_mnuConLivros_cb, 0, 0, 0, 0, 14, 56},
 {0,0,0,0,0,0,0,0,0},
 {"&Vendas", 0,  0, 0, 64, 0, 0, 14, 56},
 {"&Vender Livros", 0,  (Fl_Callback*)frmPrincipal_mnuVenVenderLivros_cb, 0, 0, 0, 0, 14, 56},
 {"Vendas &Realizadas", 0,  (Fl_Callback*)frmPrincipal_mnuVenVendasRealizadas_cb, 0, 0, 0, 0, 14, 56},
 {0,0,0,0,0,0,0,0,0},
 {"&Janelas", 0,  0, 0, 64, 0, 0, 14, 56},
 {"Lado a lado &horizontal", 0,  0, 0, 0, 0, 0, 14, 56},
 {"Lado a lado &vertical", 0,  0, 0, 0, 0, 0, 14, 56},
 {"Em &cascata", 0,  0, 0, 0, 0, 0, 14, 56},
 {"&Organizar \355""cones", 0,  0, 0, 0, 0, 0, 14, 56},
 {0,0,0,0,0,0,0,0,0},
 {"&Op\347\365""es", 0,  0, 0, 64, 0, 0, 14, 56},
 {"&Alterar Senha", 0,  (Fl_Callback*)frmPrincipal_mnuOpAlterarSenha_cb, 0, 128, 0, 0, 14, 56},
 {"&Sobre", 0,  (Fl_Callback*)frmPrincipal_mnuOpSobre_cb, 0, 0, 0, 0, 14, 56},
 {"Sa&ir", 0,  (Fl_Callback*)frmPrincipal_mnuOpSair_cb, 0, 0, 0, 0, 14, 56},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* CfrmPrincipal::mnuCadastros = CfrmPrincipal::menu_BarraDeMenu + 0;
Fl_Menu_Item* CfrmPrincipal::mnuCadAssuntos = CfrmPrincipal::menu_BarraDeMenu + 1;
Fl_Menu_Item* CfrmPrincipal::mnuCadAutores = CfrmPrincipal::menu_BarraDeMenu + 2;
Fl_Menu_Item* CfrmPrincipal::mnuCadEditoras = CfrmPrincipal::menu_BarraDeMenu + 3;
Fl_Menu_Item* CfrmPrincipal::mnuCadEnderecos = CfrmPrincipal::menu_BarraDeMenu + 4;
Fl_Menu_Item* CfrmPrincipal::mnuCadIdiomas = CfrmPrincipal::menu_BarraDeMenu + 5;
Fl_Menu_Item* CfrmPrincipal::mnuCadPaises = CfrmPrincipal::menu_BarraDeMenu + 6;
Fl_Menu_Item* CfrmPrincipal::mnuCadProfissoes = CfrmPrincipal::menu_BarraDeMenu + 7;
Fl_Menu_Item* CfrmPrincipal::mnuCadCLientes = CfrmPrincipal::menu_BarraDeMenu + 8;
Fl_Menu_Item* CfrmPrincipal::mnuCadLivros = CfrmPrincipal::menu_BarraDeMenu + 9;
Fl_Menu_Item* CfrmPrincipal::mnuPesquisas = CfrmPrincipal::menu_BarraDeMenu + 11;
Fl_Menu_Item* CfrmPrincipal::mnuConAssuntos = CfrmPrincipal::menu_BarraDeMenu + 12;
Fl_Menu_Item* CfrmPrincipal::mnuConAutores = CfrmPrincipal::menu_BarraDeMenu + 13;
Fl_Menu_Item* CfrmPrincipal::mnuConEditoras = CfrmPrincipal::menu_BarraDeMenu + 14;
Fl_Menu_Item* CfrmPrincipal::mnuConEnderecos = CfrmPrincipal::menu_BarraDeMenu + 15;
Fl_Menu_Item* CfrmPrincipal::mnuConIdiomas = CfrmPrincipal::menu_BarraDeMenu + 16;
Fl_Menu_Item* CfrmPrincipal::mnuConPaises = CfrmPrincipal::menu_BarraDeMenu + 17;
Fl_Menu_Item* CfrmPrincipal::mnuConProfissoes = CfrmPrincipal::menu_BarraDeMenu + 18;
Fl_Menu_Item* CfrmPrincipal::mnuConClientes = CfrmPrincipal::menu_BarraDeMenu + 19;
Fl_Menu_Item* CfrmPrincipal::mnuConLivros = CfrmPrincipal::menu_BarraDeMenu + 20;
Fl_Menu_Item* CfrmPrincipal::mnuVendas = CfrmPrincipal::menu_BarraDeMenu + 22;
Fl_Menu_Item* CfrmPrincipal::mnuVenVenderLivros = CfrmPrincipal::menu_BarraDeMenu + 23;
Fl_Menu_Item* CfrmPrincipal::mnuVenVendasRealizadas = CfrmPrincipal::menu_BarraDeMenu + 24;
Fl_Menu_Item* CfrmPrincipal::mnuJanelas = CfrmPrincipal::menu_BarraDeMenu + 26;
Fl_Menu_Item* CfrmPrincipal::mnuJanLadoHorizontal = CfrmPrincipal::menu_BarraDeMenu + 27;
Fl_Menu_Item* CfrmPrincipal::mnuJanLadoVertical = CfrmPrincipal::menu_BarraDeMenu + 28;
Fl_Menu_Item* CfrmPrincipal::mnuJanEmCascata = CfrmPrincipal::menu_BarraDeMenu + 29;
Fl_Menu_Item* CfrmPrincipal::mnuJanOrganizarIcones = CfrmPrincipal::menu_BarraDeMenu + 30;
Fl_Menu_Item* CfrmPrincipal::mnuOpcoes = CfrmPrincipal::menu_BarraDeMenu + 32;
Fl_Menu_Item* CfrmPrincipal::mnuOpAlterarSenha = CfrmPrincipal::menu_BarraDeMenu + 33;
Fl_Menu_Item* CfrmPrincipal::mnuOpSobre = CfrmPrincipal::menu_BarraDeMenu + 34;
Fl_Menu_Item* CfrmPrincipal::mnuOpSair = CfrmPrincipal::menu_BarraDeMenu + 35;

void CfrmPrincipal::IniciaControles() {
  frmPrincipal* w;
  { frmPrincipal* o = fPrincipal = new frmPrincipal(0, 0, 507, 390, "Livrus Virtus");
    w = o;
    o->box(FL_FLAT_BOX);
    o->color(FL_BACKGROUND_COLOR);
    o->selection_color(FL_BACKGROUND_COLOR);
    o->image(image_Livrus);
    o->labeltype(FL_NO_LABEL);
    o->labelfont(0);
    o->labelsize(14);
    o->labelcolor(FL_BLACK);
    o->user_data((void*)(this));
    o->align(FL_ALIGN_TOP);
    o->when(FL_WHEN_RELEASE);
    { Fl_Menu_Bar* o = BarraDeMenu = new Fl_Menu_Bar(0, 0, 505, 25);
      o->align(FL_ALIGN_TOP);
      o->menu(menu_BarraDeMenu);
    }
    { Fl_Group* o = BarraDeFerra = new Fl_Group(0, 25, 505, 35);
      o->box(FL_UP_BOX);
      { Fl_Button* o = tlbClientes = new Fl_Button(5, 30, 25, 25);
        o->callback((Fl_Callback*)frmPrincipal_tlbClientesClick_cb);
      }
      { Fl_Button* o = tlbLivros = new Fl_Button(30, 30, 25, 25);
        o->callback((Fl_Callback*)frmPrincipal_tlbLivrosClick_cb);
      }
      { Fl_Button* o = tlbVenda = new Fl_Button(55, 30, 25, 25);
        o->callback((Fl_Callback*)frmPrincipal_tlbVendaClick_cb);
      }
      { Fl_Button* o = tlbSobre = new Fl_Button(85, 30, 25, 25);
        o->callback((Fl_Callback*)frmPrincipal_tlbSobreClick_cb);
      }
      { Fl_Button* o = tlbSair = new Fl_Button(110, 30, 25, 25);
        o->callback((Fl_Callback*)frmPrincipal_tlbSairClick_cb);
      }
      o->end();
    }
    { Fl_Box* o = BarraDeStatus1 = new Fl_Box(0, 370, 105, 20, "Usu\341rio: admin");
      o->box(FL_DOWN_BOX);
      o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    }
    { Fl_Box* o = BarraDeStatus2 = new Fl_Box(106, 370, 400, 20);
      o->box(FL_DOWN_BOX);
    }
    o->end();
    o->resizable(o);
  }
  { Fl_Double_Window* o = new Fl_Double_Window(104, 100);
    w = o;
    o->user_data((void*)(this));
    o->end();
  }
}

void CfrmCadastros::IniciaControles() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = fCadastros = new Fl_Double_Window(382, 136, "Cadastro de");
    w = o;
    o->user_data((void*)(this));
    { Fl_Input* o = edtCodigo = new Fl_Input(10, 20, 140, 25, "C\363""digo:");
      o->type(2);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Button* o = btnNovo = new Fl_Button(160, 20, 75, 25, "&Novo");
      o->callback((Fl_Callback*)frmCadastros_btnNovoClick_cb);
    }
    { Fl_Input* o = edtDescricao = new Fl_Input(10, 70, 275, 25, "Descri\347\343o:");
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Button* o = btnPesquisar = new Fl_Button(300, 10, 75, 25, "&Pesquisar");
      o->callback((Fl_Callback*)frmCadastros_btnPesquisarClick_cb);
    }
    { Fl_Button* o = btnAnterior = new Fl_Button(300, 40, 75, 25, "&Anterior");
      o->callback((Fl_Callback*)frmCadastros_btnAnteriorClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnProximo = new Fl_Button(300, 70, 75, 25, "Pr\363xi&mo");
      o->callback((Fl_Callback*)frmCadastros_btnProximoClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnSalvar = new Fl_Button(60, 105, 75, 25, "&Salvar");
      o->callback((Fl_Callback*)frmCadastros_btnSalvarClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnExcluir = new Fl_Button(140, 105, 75, 25, "&Excluir");
      o->callback((Fl_Callback*)frmCadastros_btnExcluirClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnLimpar = new Fl_Button(220, 105, 75, 25, "&Limpar");
      o->callback((Fl_Callback*)frmCadastros_btnLimparClick_cb);
    }
    { Fl_Button* o = btnFechar = new Fl_Button(300, 105, 75, 25, "&Fechar");
      o->callback((Fl_Callback*)frmCadastros_btnFecharClick_cb);
    }
    o->end();
  }
}

void CfrmSplash::IniciaControles() {
  CfrmSplash* w;
  { CfrmSplash* o = fSplash = new CfrmSplash(0, 0, 259, 73);
    w = o;
    o->box(FL_FLAT_BOX);
    o->color(FL_BACKGROUND_COLOR);
    o->selection_color(FL_BACKGROUND_COLOR);
    o->labeltype(FL_NO_LABEL);
    o->labelfont(0);
    o->labelsize(14);
    o->labelcolor(FL_BLACK);
    o->user_data((void*)(this));
    o->align(FL_ALIGN_TOP);
    o->when(FL_WHEN_RELEASE);
    imagem1 = new Fl_Box(0, 0, 260, 70);
    o->set_modal();
    o->clear_border();
    o->end();
  }
}

void CfrmSobre::IniciaControles() {
  CfrmSobre* w;
  { CfrmSobre* o = fSobre = new CfrmSobre(0, 0, 302, 267, "Sobre o Sistema");
    w = o;
    o->box(FL_FLAT_BOX);
    o->color(FL_BACKGROUND_COLOR);
    o->selection_color(FL_BACKGROUND_COLOR);
    o->labeltype(FL_NO_LABEL);
    o->labelfont(0);
    o->labelsize(14);
    o->labelcolor(FL_BLACK);
    o->user_data((void*)(this));
    o->align(FL_ALIGN_TOP);
    o->when(FL_WHEN_RELEASE);
    w->hotspot(o);
    { Fl_Group* o = grupo1 = new Fl_Group(5, 5, 290, 220);
      o->box(FL_ENGRAVED_BOX);
      imagem1 = new Fl_Box(20, 15, 260, 80);
      labVersao = new Fl_Box(195, 95, 95, 20, "Vers\343o 1.0.0");
      { Fl_Box* o = labDireitos = new Fl_Box(15, 120, 275, 40, "Todos os diretos reservados para: Henrique F. de Souza");
        o->align(FL_ALIGN_WRAP);
      }
      { Fl_Box* o = labSistema = new Fl_Box(10, 165, 285, 55, "Sistema integrante do projeto Livrus Virtus, vers\343o programada no Visual C\
++ 6.0 usando FLTK.");
        o->align(FL_ALIGN_WRAP);
      }
      o->end();
    }
    { Fl_Button* o = btnOk = new Fl_Button(115, 235, 75, 25, "&Ok");
      o->callback((Fl_Callback*)frmSobre_btnOkClick_cb);
    }
    o->set_modal();
    o->end();
  }
}

void CfrmLogin::IniciaControles() {
  CfrmLogin* w;
  { CfrmLogin* o = fLogin = new CfrmLogin(0, 0, 207, 141, "Login do Sistema");
    w = o;
    o->box(FL_FLAT_BOX);
    o->color(FL_BACKGROUND_COLOR);
    o->selection_color(FL_BACKGROUND_COLOR);
    o->labeltype(FL_NO_LABEL);
    o->labelfont(0);
    o->labelsize(14);
    o->labelcolor(FL_BLACK);
    o->user_data((void*)(this));
    o->align(FL_ALIGN_TOP);
    o->when(FL_WHEN_RELEASE);
    new Fl_Box(5, 5, 100, 105);
    { Fl_Input* o = edtLogin = new Fl_Input(110, 30, 95, 25, "Login:");
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Input* o = edtSenha = new Fl_Input(110, 75, 95, 25, "Senha:");
      o->type(5);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Button* o = btnLogin = new Fl_Button(25, 110, 75, 25, "&Login");
      o->callback((Fl_Callback*)frmLogin_btnLoginClick_cb);
    }
    { Fl_Button* o = btnCancelar = new Fl_Button(110, 110, 75, 25, "&Cancelar");
      o->callback((Fl_Callback*)frmLogin_btnCancelarClick_cb);
    }
    o->set_modal();
    o->end();
  }
}

void CfrmAlterarSenha::IniciaControles() {
  CfrmAlterarSenha* w;
  { CfrmAlterarSenha* o = fAlterarSenha = new CfrmAlterarSenha(0, 0, 258, 137, "Altera\347\343o de Senha");
    w = o;
    o->box(FL_FLAT_BOX);
    o->color(FL_BACKGROUND_COLOR);
    o->selection_color(FL_BACKGROUND_COLOR);
    o->labeltype(FL_NO_LABEL);
    o->labelfont(0);
    o->labelsize(14);
    o->labelcolor(FL_BLACK);
    o->user_data((void*)(this));
    o->align(FL_ALIGN_TOP);
    o->when(FL_WHEN_RELEASE);
    { Fl_Input* o = edtLogin = new Fl_Input(10, 25, 105, 25, "Login:");
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Input* o = edtSenhaAtual = new Fl_Input(120, 25, 105, 25, "Senha atual:");
      o->type(5);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Input* o = edtNovaSenha = new Fl_Input(10, 70, 105, 25, "Nova senha:");
      o->type(5);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Input* o = edtConfirmaSenha = new Fl_Input(120, 70, 105, 25, "Confirma Senha:");
      o->type(5);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Button* o = btnSalvar = new Fl_Button(10, 105, 75, 25, "&Salvar");
      o->callback((Fl_Callback*)frmAlterarSenha_btnSalvarClick_cb);
    }
    { Fl_Button* o = btnLimpar = new Fl_Button(90, 105, 75, 25, "&Limpar");
      o->callback((Fl_Callback*)frmAlterarSenha_btnLimparClick_cb);
    }
    { Fl_Button* o = btnFechar = new Fl_Button(170, 105, 75, 25, "&Fechar");
      o->callback((Fl_Callback*)frmAlterarSenha_btnFecharClick_cb);
    }
    o->end();
  }
}

void CfrmCadEnderecos::IniciaControles() {
  CfrmCadEnderecos* w;
  { CfrmCadEnderecos* o = fCadEnderecos = new CfrmCadEnderecos(0, 0, 525, 175, "Cadastro de Endere\347os");
    w = o;
    o->box(FL_FLAT_BOX);
    o->color(FL_BACKGROUND_COLOR);
    o->selection_color(FL_BACKGROUND_COLOR);
    o->labeltype(FL_NORMAL_LABEL);
    o->labelfont(0);
    o->labelsize(14);
    o->labelcolor(FL_BLACK);
    o->user_data((void*)(this));
    o->align(FL_ALIGN_TOP);
    o->when(FL_WHEN_RELEASE);
    { Fl_Input* o = edtCodigo = new Fl_Input(5, 20, 140, 25, "C\363""digo:");
      o->type(2);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Button* o = btnNovo = new Fl_Button(150, 20, 75, 25, "&Novo");
      o->callback((Fl_Callback*)frmCadEnderecos_btnNovoClick_cb);
    }
    { Fl_Input* o = edtDescricao = new Fl_Input(5, 65, 275, 25, "Logradouro:");
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Input* o = edtBairro = new Fl_Input(285, 65, 150, 25, "Bairro:");
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Input* o = edtCep = new Fl_Input(5, 110, 85, 25, "CEP:");
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Input* o = edtCidade = new Fl_Input(95, 110, 185, 25, "Cidade:");
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Choice* o = cmbEstado = new Fl_Choice(285, 110, 150, 25, "Estado:");
      o->down_box(FL_BORDER_BOX);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Button* o = btnPesquisar = new Fl_Button(445, 15, 75, 25, "&Pesquisar");
      o->callback((Fl_Callback*)frmCadEnderecos_btnPesquisarClick_cb);
    }
    { Fl_Button* o = btnAnterior = new Fl_Button(445, 45, 75, 25, "&Anterior");
      o->callback((Fl_Callback*)frmCadEnderecos_btnAnteriorClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnProximo = new Fl_Button(445, 75, 75, 25, "Pr\363xi&mo");
      o->callback((Fl_Callback*)frmCadEnderecos_btnProximoClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnSalvar = new Fl_Button(205, 145, 75, 25, "&Salvar");
      o->callback((Fl_Callback*)frmCadEnderecos_btnSalvarClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnExcluir = new Fl_Button(285, 145, 75, 25, "&Excluir");
      o->callback((Fl_Callback*)frmCadEnderecos_btnExcluirClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnLimpar = new Fl_Button(365, 145, 75, 25, "&Limpar");
      o->callback((Fl_Callback*)frmCadEnderecos_btnLimparClick_cb);
    }
    { Fl_Button* o = btnFechar = new Fl_Button(445, 145, 75, 25, "&Fechar");
      o->callback((Fl_Callback*)frmCadEnderecos_btnFecharClick_cb);
    }
    o->end();
  }
}

void CfrmCadAssuntos::IniciaControles() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = fCadAssuntos = new Fl_Double_Window(382, 136, "Cadastro de Assuntos");
    w = o;
    o->labeltype(FL_NORMAL_LABEL);
    o->user_data((void*)(this));
    { Fl_Input* o = edtCodigo = new Fl_Input(10, 20, 140, 25, "C\363""digo:");
      o->type(2);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Button* o = btnNovo = new Fl_Button(160, 20, 75, 25, "&Novo");
      o->callback((Fl_Callback*)frmCadAssuntos_btnNovoClick_cb);
    }
    { Fl_Input* o = edtDescricao = new Fl_Input(10, 70, 275, 25, "Assunto:");
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Button* o = btnPesquisar = new Fl_Button(300, 10, 75, 25, "&Pesquisar");
      o->callback((Fl_Callback*)frmCadAssuntos_btnPesquisarClick_cb);
    }
    { Fl_Button* o = btnAnterior = new Fl_Button(300, 40, 75, 25, "&Anterior");
      o->callback((Fl_Callback*)frmCadAssuntos_btnAnteriorClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnProximo = new Fl_Button(300, 70, 75, 25, "Pr\363xi&mo");
      o->callback((Fl_Callback*)frmCadAssuntos_btnProximoClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnSalvar = new Fl_Button(60, 105, 75, 25, "&Salvar");
      o->callback((Fl_Callback*)frmCadAssuntos_btnSalvarClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnExcluir = new Fl_Button(140, 105, 75, 25, "&Excluir");
      o->callback((Fl_Callback*)frmCadAssuntos_btnExcluirClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnLimpar = new Fl_Button(220, 105, 75, 25, "&Limpar");
      o->callback((Fl_Callback*)frmCadAssuntos_btnLimparClick_cb);
    }
    { Fl_Button* o = btnFechar = new Fl_Button(300, 105, 75, 25, "&Fechar");
      o->callback((Fl_Callback*)frmCadAssuntos_btnFecharClick_cb);
    }
    o->end();
  }
}

void CfrmCadAutores::IniciaControles() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = fCadAutores = new Fl_Double_Window(382, 136, "Cadastro de Autores");
    w = o;
    o->user_data((void*)(this));
    { Fl_Input* o = edtCodigo = new Fl_Input(10, 20, 140, 25, "C\363""digo:");
      o->type(2);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Button* o = btnNovo = new Fl_Button(160, 20, 75, 25, "&Novo");
      o->callback((Fl_Callback*)frmCadAutores_btnNovoClick_cb);
    }
    { Fl_Input* o = edtDescricao = new Fl_Input(10, 70, 275, 25, "Autor::");
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Button* o = btnPesquisar = new Fl_Button(300, 10, 75, 25, "&Pesquisar");
      o->callback((Fl_Callback*)frmCadAutores_btnPesquisarClick_cb);
    }
    { Fl_Button* o = btnAnterior = new Fl_Button(300, 40, 75, 25, "&Anterior");
      o->callback((Fl_Callback*)frmCadAutores_btnAnteriorClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnProximo = new Fl_Button(300, 70, 75, 25, "Pr\363xi&mo");
      o->callback((Fl_Callback*)frmCadAutores_btnProximoClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnSalvar = new Fl_Button(60, 105, 75, 25, "&Salvar");
      o->callback((Fl_Callback*)frmCadAutores_btnSalvarClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnExcluir = new Fl_Button(140, 105, 75, 25, "&Excluir");
      o->callback((Fl_Callback*)frmCadAutores_btnExcluirClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnLimpar = new Fl_Button(220, 105, 75, 25, "&Limpar");
      o->callback((Fl_Callback*)frmCadAutores_btnLimparClick_cb);
    }
    { Fl_Button* o = btnFechar = new Fl_Button(300, 105, 75, 25, "&Fechar");
      o->callback((Fl_Callback*)frmCadAutores_btnFecharClick_cb);
    }
    o->end();
  }
}

void CfrmCadClientes::IniciaControles() {
  CfrmCadClientes* w;
  { CfrmCadClientes* o = fCadClientes = new CfrmCadClientes(0, 0, 535, 469, "Cadastro de Clientes");
    w = o;
    o->box(FL_FLAT_BOX);
    o->color(FL_BACKGROUND_COLOR);
    o->selection_color(FL_BACKGROUND_COLOR);
    o->labeltype(FL_NO_LABEL);
    o->labelfont(0);
    o->labelsize(14);
    o->labelcolor(FL_BLACK);
    o->user_data((void*)(this));
    o->align(FL_ALIGN_TOP);
    o->when(FL_WHEN_RELEASE);
    { Fl_Input* o = edtCodigo = new Fl_Input(10, 25, 140, 25, "CPF:");
      o->callback((Fl_Callback*)frmCadClientes_edtCodigoKillFocus_cb, (void*)(novidade));
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Button* o = btnNovo = new Fl_Button(155, 25, 75, 25, "&Novo");
      o->callback((Fl_Callback*)frmCadClientes_btnNovoClick_cb);
    }
    { Fl_Input* o = edtDescricao = new Fl_Input(10, 70, 305, 25, "Nome:");
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Input* o = edtEmail = new Fl_Input(10, 115, 305, 25, "E-mail:");
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Input* o = edtIdentidade = new Fl_Input(320, 115, 120, 25, "Identidade:");
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Group* o = grpSexo = new Fl_Group(10, 160, 190, 30, "Sexo");
      o->box(FL_ENGRAVED_BOX);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
      { Fl_Round_Button* o = rbMasculino = new Fl_Round_Button(20, 165, 90, 20, "Masculino");
        o->down_box(FL_ROUND_DOWN_BOX);
      }
      { Fl_Round_Button* o = rbFeminino = new Fl_Round_Button(110, 165, 85, 20, "Feminino");
        o->down_box(FL_ROUND_DOWN_BOX);
      }
      o->end();
    }
    { Fl_Input* o = edtTelefone = new Fl_Input(205, 165, 110, 25, "Telefone:");
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Input* o = edtDtNasc = new Fl_Input(320, 165, 120, 25, "Dt. Nascimento:");
      o->callback((Fl_Callback*)frmCadClientes_edtDtNascKillFocus_cb);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Group* o = grpEndereco = new Fl_Group(10, 210, 440, 130, "Endere\347o");
      o->box(FL_ENGRAVED_BOX);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
      { Fl_Input* o = edtCodEndereco = new Fl_Input(20, 220, 140, 25);
        o->type(2);
        o->labeltype(FL_NO_LABEL);
        o->callback((Fl_Callback*)frmCadLivros_edtCodEnderecoKillFocus_cb);
        o->align(FL_ALIGN_TOP_LEFT);
      }
      { Fl_Button* o = btnPEndereco = new Fl_Button(160, 220, 25, 25, "...");
        o->callback((Fl_Callback*)frmCadClientes_btnPEnderecoClick_cb);
      }
      { Fl_Input* o = edtLogradouro = new Fl_Input(20, 265, 275, 25, "Logradouro:");
        o->align(FL_ALIGN_TOP_LEFT);
      }
      { Fl_Input* o = edtBairro = new Fl_Input(300, 265, 145, 25, "Bairro:");
        o->align(FL_ALIGN_TOP_LEFT);
      }
      { Fl_Input* o = edtCep = new Fl_Input(20, 310, 85, 25, "CEP:");
        o->align(FL_ALIGN_TOP_LEFT);
      }
      { Fl_Input* o = edtCidade = new Fl_Input(110, 310, 185, 25, "Cidade:");
        o->align(FL_ALIGN_TOP_LEFT);
      }
      { Fl_Input* o = edtEstado = new Fl_Input(300, 310, 145, 25, "Estado:");
        o->align(FL_ALIGN_TOP_LEFT);
      }
      o->end();
    }
    { Fl_Input* o = edtCodPais = new Fl_Input(10, 360, 100, 25, "Pa\355s de origem:");
      o->type(2);
      o->callback((Fl_Callback*)frmCadClientes_edtCodPaisKillFocus_cb);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Input* o = edtPais = new Fl_Input(115, 360, 275, 25);
      o->labeltype(FL_NO_LABEL);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Button* o = btnPPais = new Fl_Button(390, 360, 25, 25, "...");
      o->callback((Fl_Callback*)frmCadClientes_btnPPaisClick_cb);
      o->deactivate();
    }
    { Fl_Input* o = edtCodProfissao = new Fl_Input(10, 405, 100, 25, "Profiss\343o:");
      o->type(2);
      o->callback((Fl_Callback*)frmCadClientes_edtCodProfissaoKillFocus_cb);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Input* o = edtProfissao = new Fl_Input(115, 405, 275, 25);
      o->labeltype(FL_NO_LABEL);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Button* o = btnPProfissao = new Fl_Button(390, 405, 25, 25, "...");
      o->callback((Fl_Callback*)frmCadClientes_btnPProfissaoClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnPesquisar = new Fl_Button(455, 25, 75, 25, "&Pesquisar");
      o->callback((Fl_Callback*)frmCadClientes_btnPesquisarClick_cb);
    }
    { Fl_Button* o = btnAnterior = new Fl_Button(455, 55, 75, 25, "&Anterior");
      o->callback((Fl_Callback*)frmCadClientes_btnAnteriorClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnProximo = new Fl_Button(455, 85, 75, 25, "Pr\363xi&mo");
      o->callback((Fl_Callback*)frmCadClientes_btnProximoClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnSalvar = new Fl_Button(215, 440, 75, 25, "&Salvar");
      o->callback((Fl_Callback*)frmCadClientes_btnSalvarClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnExcluir = new Fl_Button(295, 440, 75, 25, "&Excluir");
      o->callback((Fl_Callback*)frmCadClientes_btnExcluirClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnLimpar = new Fl_Button(375, 440, 75, 25, "&Limpar");
      o->callback((Fl_Callback*)frmCadClientes_btnLimparClick_cb);
    }
    { Fl_Button* o = btnFechar = new Fl_Button(455, 440, 75, 25, "&Fechar");
      o->callback((Fl_Callback*)frmCadClientes_btnFecharClick_cb);
    }
    o->end();
  }
}

void CfrmCadLivros::IniciaControles() {
  CfrmCadLivros* w;
  { CfrmCadLivros* o = fCadLivros = new CfrmCadLivros(0, 0, 557, 436, "Cadastro de Livros");
    w = o;
    o->box(FL_FLAT_BOX);
    o->color(FL_BACKGROUND_COLOR);
    o->selection_color(FL_BACKGROUND_COLOR);
    o->labeltype(FL_NO_LABEL);
    o->labelfont(0);
    o->labelsize(14);
    o->labelcolor(FL_BLACK);
    o->user_data((void*)(this));
    o->align(FL_ALIGN_TOP);
    o->when(FL_WHEN_RELEASE);
    { Fl_Input* o = edtCodigo = new Fl_Input(10, 25, 140, 25, "ISBN:");
      o->callback((Fl_Callback*)frmCadLivros_edtCodigoKillFocus_cb);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Button* o = btnNovo = new Fl_Button(155, 25, 75, 25, "&Novo");
      o->callback((Fl_Callback*)frmCadLivros_btnNovoClick_cb);
    }
    { Fl_Input* o = edtDescricao = new Fl_Input(10, 70, 350, 25, "T\355tulo:");
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Value_Input* o = edtEdicao = new Fl_Value_Input(365, 70, 105, 25, "Edi\347\343o:");
      o->minimum(1);
      o->maximum(9999);
      o->step(1);
      o->value(1);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Value_Input* o = edtAnoPubli = new Fl_Value_Input(10, 115, 105, 25, "Ano Publica\347\343o:");
      o->minimum(1);
      o->maximum(9999);
      o->step(1);
      o->value(1);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Input* o = edtCodEditora = new Fl_Input(120, 115, 100, 25, "Editora:");
      o->type(2);
      o->callback((Fl_Callback*)frmCadLivros_edtCodEditoraKillFocus_cb);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Input* o = edtEditora = new Fl_Input(225, 115, 220, 25);
      o->labeltype(FL_NO_LABEL);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Button* o = btnPEditora = new Fl_Button(445, 115, 25, 25, "...");
      o->callback((Fl_Callback*)frmCadLivros_btnPEditoraClick_cb);
      o->deactivate();
    }
    { Fl_Value_Input* o = edtVolume = new Fl_Value_Input(10, 160, 105, 25, "Volume:");
      o->minimum(1);
      o->maximum(9999);
      o->step(1);
      o->value(1);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Choice* o = cmbIdioma = new Fl_Choice(120, 160, 350, 25, "Idioma:");
      o->down_box(FL_BORDER_BOX);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Value_Input* o = edtNPaginas = new Fl_Value_Input(10, 205, 105, 25, "N. P\341ginas:");
      o->minimum(1);
      o->maximum(9999);
      o->step(1);
      o->value(1);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Input* o = edtCodAssunto = new Fl_Input(120, 205, 100, 25, "Assunto:");
      o->type(2);
      o->callback((Fl_Callback*)frmCadLivros_edtCodAssuntoKillFocus_cb);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Input* o = edtAssunto = new Fl_Input(225, 205, 190, 25);
      o->labeltype(FL_NO_LABEL);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Button* o = btnAdAssuntos = new Fl_Button(415, 205, 25, 25, "+");
      o->callback((Fl_Callback*)frmCadLivros_btnAdAssuntosClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnPAssunto = new Fl_Button(445, 205, 25, 25, "...");
      o->callback((Fl_Callback*)frmCadLivros_btnPAssuntoClick_cb);
      o->deactivate();
    }
    { Fl_Input* o = edtPreco = new Fl_Input(10, 265, 105, 25, "Pre\347o:");
      o->type(1);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Browser* o = lstAssuntos = new Fl_Browser(120, 230, 350, 60);
      o->type(1);
      o->callback((Fl_Callback*)frmCadLivros_lstAssuntosDblClick_cb);
      o->deactivate();
    }
    { Fl_Value_Input* o = edtQtdEstoque = new Fl_Value_Input(10, 310, 105, 25, "Qtd. Estoque:");
      o->maximum(9999);
      o->step(1);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Input* o = edtCodAutor = new Fl_Input(120, 310, 100, 25, "Autor:");
      o->type(2);
      o->callback((Fl_Callback*)frmCadLivros_edtCodAutorKillFocus_cb);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Input* o = edtAutor = new Fl_Input(225, 310, 190, 25);
      o->labeltype(FL_NO_LABEL);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Button* o = btnAdAutores = new Fl_Button(415, 310, 25, 25, "+");
      o->callback((Fl_Callback*)frmCadLivros_btnAdAutoresClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnPAutor = new Fl_Button(445, 310, 25, 25, "...");
      o->callback((Fl_Callback*)frmCadLivros_btnPAutorClick_cb);
      o->deactivate();
    }
    { Fl_Browser* o = lstAutores = new Fl_Browser(120, 335, 350, 60);
      o->type(1);
      o->callback((Fl_Callback*)frmCadLivros_lstAutoresDblClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnPesquisar = new Fl_Button(475, 20, 75, 25, "&Pesquisar");
      o->callback((Fl_Callback*)frmCadLivros_btnPesquisarClick_cb);
    }
    { Fl_Button* o = btnAnterior = new Fl_Button(475, 50, 75, 25, "&Anterior");
      o->callback((Fl_Callback*)frmCadLivros_btnAnteriorClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnProximo = new Fl_Button(475, 80, 75, 25, "Pr\363xi&mo");
      o->callback((Fl_Callback*)frmCadLivros_btnProximoClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnSalvar = new Fl_Button(235, 404, 75, 25, "&Salvar");
      o->callback((Fl_Callback*)frmCadLivros_btnSalvarClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnExcluir = new Fl_Button(315, 404, 75, 25, "&Excluir");
      o->callback((Fl_Callback*)frmCadLivros_btnExcluirClick_cb);
      o->deactivate();
    }
    { Fl_Button* o = btnLimpar = new Fl_Button(395, 404, 75, 25, "&Limpar");
      o->callback((Fl_Callback*)frmCadLivros_btnLimparClick_cb);
    }
    { Fl_Button* o = btnFechar = new Fl_Button(475, 404, 75, 25, "&Fechar");
      o->callback((Fl_Callback*)frmCadLivros_btnFecharClick_cb);
    }
    o->end();
  }
}

void CfrmConsultas::IniciaControles() {
  CfrmConsultas* w;
  { CfrmConsultas* o = fConsultas = new CfrmConsultas(0, 0, 416, 255, "Consulta de ");
    w = o;
    o->box(FL_FLAT_BOX);
    o->color(FL_BACKGROUND_COLOR);
    o->selection_color(FL_BACKGROUND_COLOR);
    o->labeltype(FL_NO_LABEL);
    o->labelfont(0);
    o->labelsize(14);
    o->labelcolor(FL_BLACK);
    o->user_data((void*)(this));
    o->align(FL_ALIGN_TOP);
    o->when(FL_WHEN_RELEASE);
    { Fl_Group* o = grupo1 = new Fl_Group(0, 0, 415, 65);
      o->box(FL_UP_BOX);
      { Fl_Input* o = edtDescricao = new Fl_Input(10, 25, 315, 25, "Descri\347\343o:");
        o->align(FL_ALIGN_TOP_LEFT);
      }
      { Fl_Button* o = btnPesquisar = new Fl_Button(330, 25, 75, 25, "&Pesquisar");
        o->callback((Fl_Callback*)frmConsultas_btnPesquisarClick_cb);
      }
      o->end();
    }
    { Fl_Browser* o = gridConsulta = new Fl_Browser(0, 65, 415, 145);
      o->type(3);
      o->box(FL_UP_BOX);
      o->callback((Fl_Callback*)frmConsultas_gridConsultaSelect_cb);
      Fl_Group::current()->resizable(o);
    }
    { Fl_Group* o = grupo2 = new Fl_Group(0, 210, 415, 45);
      o->box(FL_UP_BOX);
      { Fl_Box* o = labRegistros = new Fl_Box(10, 220, 140, 25, "Registro 0 de 0 ");
        o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
      }
      { Fl_Button* o = btnLimpar = new Fl_Button(250, 220, 75, 25, "&Limpar");
        o->callback((Fl_Callback*)frmConsultas_btnLimparClick_cb);
      }
      { Fl_Button* o = btnFechar = new Fl_Button(330, 220, 75, 25, "&Fechar");
        o->callback((Fl_Callback*)frmConsultas_btnFecharClick_cb);
      }
      o->end();
    }
    o->set_modal();
    o->end();
  }
}

void CfrmConAssuntos::IniciaControles() {
  CfrmConAssuntos* w;
  { CfrmConAssuntos* o = fConAssuntos = new CfrmConAssuntos(0, 0, 416, 255, "Consulta de Assuntos");
    w = o;
    o->box(FL_FLAT_BOX);
    o->color(FL_BACKGROUND_COLOR);
    o->selection_color(FL_BACKGROUND_COLOR);
    o->labeltype(FL_NO_LABEL);
    o->labelfont(0);
    o->labelsize(14);
    o->labelcolor(FL_BLACK);
    o->user_data((void*)(this));
    o->align(FL_ALIGN_TOP);
    o->when(FL_WHEN_RELEASE);
    { Fl_Group* o = grupo1 = new Fl_Group(0, 0, 415, 65);
      o->box(FL_UP_BOX);
      { Fl_Input* o = edtDescricao = new Fl_Input(10, 25, 315, 25, "Assunto:");
        o->align(FL_ALIGN_TOP_LEFT);
      }
      { Fl_Button* o = btnPesquisar = new Fl_Button(330, 25, 75, 25, "&Pesquisar");
        o->callback((Fl_Callback*)frmConsultas_btnPesquisarClick_cb);
      }
      o->end();
    }
    { Fl_Browser* o = gridConsulta = new Fl_Browser(0, 65, 415, 145);
      o->type(3);
      o->box(FL_UP_BOX);
      o->callback((Fl_Callback*)frmConsultas_gridConsultaSelect_cb);
      Fl_Group::current()->resizable(o);
    }
    { Fl_Group* o = grupo2 = new Fl_Group(0, 210, 415, 45);
      o->box(FL_UP_BOX);
      { Fl_Box* o = labRegistros = new Fl_Box(10, 220, 140, 25, "Registro 0 de 0 ");
        o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
      }
      { Fl_Button* o = btnLimpar = new Fl_Button(250, 220, 75, 25, "&Limpar");
        o->callback((Fl_Callback*)frmConsultas_btnLimparClick_cb);
      }
      { Fl_Button* o = btnFechar = new Fl_Button(330, 220, 75, 25, "&Fechar");
        o->callback((Fl_Callback*)frmConsultas_btnFecharClick_cb);
      }
      o->end();
    }
    o->set_modal();
    o->end();
  }
}

void CfrmVenderLivros::IniciaControles() {
  CfrmVenderLivros* w;
  { CfrmVenderLivros* o = fVenderLivros = new CfrmVenderLivros(0, 0, 511, 316, "Vender Livros");
    w = o;
    o->box(FL_FLAT_BOX);
    o->color(FL_BACKGROUND_COLOR);
    o->selection_color(FL_BACKGROUND_COLOR);
    o->labeltype(FL_NO_LABEL);
    o->labelfont(0);
    o->labelsize(14);
    o->labelcolor(FL_BLACK);
    o->user_data((void*)(this));
    o->align(FL_ALIGN_TOP);
    o->when(FL_WHEN_RELEASE);
    { Fl_Output* o = edtDtHrVenda = new Fl_Output(10, 20, 160, 25, "Data/Hora Venda:");
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
    }
    { Fl_Input* o = edtCPF = new Fl_Input(10, 65, 160, 25, "CPF:");
      o->callback((Fl_Callback*)frmVenderLivros_edtCPFKillFocus_cb);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Output* o = edtCliente = new Fl_Output(170, 65, 310, 25);
      o->deactivate();
    }
    { Fl_Button* o = btnPCliente = new Fl_Button(480, 65, 25, 25, "...");
      o->callback((Fl_Callback*)frmVenderLivros_btnPClienteClick_cb);
    }
    { Fl_Input* o = edtISBN = new Fl_Input(10, 110, 160, 25, "ISBN:");
      o->callback((Fl_Callback*)frmVenderLivros_edtISBNKillFocus_cb);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Output* o = edtLivro = new Fl_Output(170, 110, 280, 25);
      o->deactivate();
    }
    { Fl_Button* o = btnAdLivros = new Fl_Button(450, 110, 25, 25, "+");
      o->callback((Fl_Callback*)frmVenderLivros_btnAdLivrosClick_cb);
    }
    { Fl_Button* o = btnPLivro = new Fl_Button(480, 110, 25, 25, "...");
      o->callback((Fl_Callback*)frmVenderLivros_btnPLivroClick_cb);
    }
    { Fl_Browser* o = lstLivros = new Fl_Browser(10, 155, 495, 95, "Livros para vender:");
      o->type(1);
      o->callback((Fl_Callback*)frmVenderLivros_lstVendasSelect_cb);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Output* o = edtPrecoTotal = new Fl_Output(350, 255, 155, 25, "Pre\347o Total:");
      o->deactivate();
    }
    { Fl_Button* o = btnVender = new Fl_Button(270, 285, 75, 25, "&Vender");
      o->callback((Fl_Callback*)frmVenderLivros_btnVenderClick_cb);
    }
    { Fl_Button* o = btnLimpar = new Fl_Button(350, 285, 75, 25, "&Limpar");
      o->callback((Fl_Callback*)frmVenderLivros_btnLimparClick_cb);
    }
    { Fl_Button* o = btnFechar = new Fl_Button(430, 285, 75, 25, "&Fechar");
      o->callback((Fl_Callback*)frmVenderLivros_btnFecharClick_cb);
    }
    o->end();
    o->resizable(o);
  }
}

void CfrmConVendas::IniciaControles() {
  CfrmConVendas* w;
  { CfrmConVendas* o = fConVendas = new CfrmConVendas(0, 0, 520, 329, "Vendas Realizadas");
    w = o;
    o->box(FL_FLAT_BOX);
    o->color(FL_BACKGROUND_COLOR);
    o->selection_color(FL_BACKGROUND_COLOR);
    o->labeltype(FL_NO_LABEL);
    o->labelfont(0);
    o->labelsize(14);
    o->labelcolor(FL_BLACK);
    o->user_data((void*)(this));
    o->align(FL_ALIGN_TOP);
    o->when(FL_WHEN_RELEASE);
    { Fl_Group* o = grupo1 = new Fl_Group(0, 0, 520, 150);
      o->box(FL_UP_BOX);
      { Fl_Output* o = edtDtHrVenda = new Fl_Output(10, 25, 160, 25, "Data/Hora Venda:");
        o->callback((Fl_Callback*)frmConVendas_edtDtHrVendaKillFocus_cb);
        o->align(FL_ALIGN_TOP_LEFT);
      }
      { Fl_Button* o = btnPesquisar = new Fl_Button(175, 25, 75, 25, "&Pesquisar");
        o->callback((Fl_Callback*)frmConVendas_btnPesquisarClick_cb);
      }
      { Fl_Input* o = edtCPF = new Fl_Input(10, 70, 160, 25, "CPF:");
        o->callback((Fl_Callback*)frmConVendas_edtCPFKillFocus_cb);
        o->align(FL_ALIGN_TOP_LEFT);
      }
      { Fl_Output* o = edtCliente = new Fl_Output(175, 70, 310, 25);
        o->deactivate();
      }
      { Fl_Button* o = btnPCliente = new Fl_Button(485, 70, 25, 25, "...");
        o->callback((Fl_Callback*)frmConVendas_btnPClienteClick_cb);
      }
      { Fl_Input* o = edtISBN = new Fl_Input(10, 115, 160, 25, "ISBN:");
        o->callback((Fl_Callback*)frmConVendas_edtISBNKillFocus_cb);
        o->align(FL_ALIGN_TOP_LEFT);
      }
      { Fl_Output* o = edtLivro = new Fl_Output(175, 115, 310, 25);
        o->deactivate();
      }
      { Fl_Button* o = btnPLivro = new Fl_Button(485, 115, 25, 25, "...");
        o->callback((Fl_Callback*)frmConVendas_btnPLivroClick_cb);
      }
      o->end();
    }
    { Fl_Browser* o = gridConsulta = new Fl_Browser(0, 150, 520, 100);
      o->type(3);
      o->box(FL_UP_BOX);
      o->callback((Fl_Callback*)frmConVendas_gridConsultaSelect_cb);
    }
    { Fl_Group* o = grupo2 = new Fl_Group(0, 250, 520, 80);
      o->box(FL_UP_BOX);
      { Fl_Box* o = labRegistros = new Fl_Box(10, 260, 140, 25, "Registro 0 de 0 ");
        o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
      }
      { Fl_Output* o = edtPrecoTotal = new Fl_Output(360, 260, 155, 25, "Pre\347o Total:");
        o->deactivate();
      }
      { Fl_Button* o = btnLimpar = new Fl_Button(360, 295, 75, 25, "&Limpar");
        o->callback((Fl_Callback*)frmConVendas_btnLimparClick_cb);
      }
      { Fl_Button* o = btnFechar = new Fl_Button(440, 295, 75, 25, "&Fechar");
        o->callback((Fl_Callback*)frmConVendas_btnFecharClick_cb);
      }
      o->end();
    }
    o->end();
    o->resizable(o);
  }
}
