#pragma once

namespace Livrus
{
	public __gc class Resource
	{
  	public:
  		//static Resource* Res;
      static int FRMCADASSUNTOS = 1000;
      static int FRMCADAUTORES	 = 1001;
      static int FRMCADEDITORAS = 1002;
      static int FRMCADENDERECOS = 1003;
      static int FRMCADIDIOMAS	 = 1004;
      static int FRMCADPAISES	 = 1005;
      static int FRMCADPROFISSOES = 1006;
      static int FRMCADCLIENTES	 = 1007;
      static int FRMCADLIVROS	  = 1008;
      static int FRMVENDERLIVROS = 1009;
      static int FRMCONVENDAS	  = 1010;
      static int FRMALTERARSENHA = 1111;
    
      static int MNU_CAD_ASSUNTOS	=	2000;
      static int MNU_CAD_AUTORES	=	2001;
      static int MNU_CAD_EDITORAS  =	2002;
      static int MNU_CAD_ENDERECOS	=	2003;
      static int MNU_CAD_IDIOMAS	=	2004;
      static int MNU_CAD_PAISES	=	2005;
      static int MNU_CAD_PROFISSOES	=	2006;
      static int MNU_CAD_CLIENTES	=	2007;
      static int MNU_CAD_LIVROS	=	2008;
      static int MNU_CON_ASSUNTOS	=	2009;
      static int MNU_CON_AUTORES	=	2010;
      static int MNU_CON_EDITORAS	=	2011;
      static int MNU_CON_ENDERECOS	=	2012;
      static int MNU_CON_IDIOMAS	=	2013;
      static int MNU_CON_PAISES	=	2014;
      static int MNU_CON_PROFISSOES	=	2015;
      static int MNU_CON_CLIENTES	=	2016;
      static int MNU_CON_LIVROS	=	2017;
      static int MNU_VEN_VENDERLIVROS	=	2018;
      static int MNU_VEN_VENDASREALIZADAS	=	2019;
      static int MNU_OP_ALTERARSENHA	=	2020;
      static int MNU_OP_SOBRE	=	2021;
      static int MNU_OP_SAIR	=	2022;
    
      static int TLB_CADCLIENTES = 2023;
      static int TLB_CADLIVROS = 2024;
      static int TLB_VENDERLIVROS = 2025;
  
      static System::String* STR_TITULO       = "Livrus Virtus";
      static System::String* STR_APPEXEC      = "A aplicação já está sendo executada.";
      static System::String* STR_NREGJAN      = "Não consigo registrar a janela principal.";
      static System::String* STR_SEMJAN       = "Sem janela principal";
      static System::String* STR_NCONBANCO    = "Não consigo conectar com o banco de dados!";
      static System::String* STR_NALOCODBC    = "Não foi possível alocar um manuseador para o ambiente ODBC";
      static System::String* STR_CADASSUNTO   = "Cadastro de Assuntos";
      static System::String* STR_CADAUTOR     = "Cadastro de Autores";
      static System::String* STR_CADEDITORA   = "Cadastro de Editoras";
      static System::String* STR_CADENDERECO  = "Cadastro de Endereços";
      static System::String* STR_CADIDIOMA    = "Cadastro de Idiomas";
      static System::String* STR_CADPAIS      = "Cadastro de Países";
      static System::String* STR_CADPROFISS   = "Cadastro de Profissões";
      static System::String* STR_CADCLIENTE   = "Cadastro de Clientes";
      static System::String* STR_CADLIVRO     = "Cadastro de Livros";
      static System::String* STR_CONASSUNTO   = "Consulta de Assuntos";
      static System::String* STR_CONAUTOR     = "Consulta de Autores";
      static System::String* STR_CONEDITORA   = "Consulta de Editoras";
      static System::String* STR_CONENDERECO  = "Consulta de Endereços";
      static System::String* STR_CONIDIOMA    = "Consulta de Idiomas";
      static System::String* STR_CONPAIS      = "Consulta de Países";
      static System::String* STR_CONPROFISS   = "Consulta de Profissões";
      static System::String* STR_CONCLIENTE   = "Consulta de Clientes";
      static System::String* STR_CONLIVRO     = "Consulta de Livros";
      static System::String* STR_VENLIVRO     = "Vender Livros";
      static System::String* STR_CONVENLIVRO  = "Vendas Realizadas";
      static System::String* STR_ALTSENHA     = "Alteração de Senha";
      static System::String* STR_OPSOBRE      = "Sobre o Sistema";
      static System::String* STR_OPSAIR       = "Sair do Sistema";  
      static System::String* STR_SAIRSIS      = "Deseja sair do sistema?";
      static System::String* STR_EMAILNINF    = "E-mail não informado!";
      static System::String* STR_NCCRIADLG    = "Não consigo criar a dialog!";
      static System::String* STR_CERTEXCL     = "Certeza de excluir?";
      static System::String* STR_TELNINF      = "Telefone não informado!";
      static System::String* STR_NREGTELA     = "Não consigo registrar a tela!";
      static System::String* STR_NCCRIATELA   = "Não consigo criar a tela!";
      static System::String* STR_NCPREPSQL    = "Não conseguiu preparar o SQL!";
      static System::String* STR_NCEXECSQL    = "Não conseguiu executar o SQL!";
      static System::String* STR_DATINV       = "Data inválida!";
      static System::String* STR_SENALTSUC    = "Senha alterada com sucesso!";
      static System::String* STR_SENNCSU      = "A Senha atual não confere com a senha do usuário!";
      static System::String* STR_NSENNINF     = "Nova senha não informada!";
      static System::String* STR_NSENNCCON    = "A Nova senha não confere com a senha a confirmar!";
      static System::String* STR_DTHRINV      = "Data/Hora inválida!";
      static System::String* STR_USUARIO      = "Usuário: ";
      static System::String* STR_LOGSENINC    = "Login ou senha incorretos!";
      static System::String* STR_ISBNNINF     = "ISBN não informado!";
      static System::String* STR_CODNINF      = "Código não informado!";
      static System::String* STR_ASSNENC      = "Assunto não encontrado!";
      static System::String* STR_ASSNINF      = "Assunto não informado!";
      static System::String* STR_AUTNENC      = "Autor não encontrado!";
      static System::String* STR_AUTNINF      = "Autor não informado!";
      static System::String* STR_EDTNENC      = "Editora não encontrada!";
      static System::String* STR_EDTNINF      = "Editora não informada!";
      static System::String* STR_ENDNENC      = "Endereço não encontrado!";
      static System::String* STR_ENDNINF      = "Endereço não informado!";
      static System::String* STR_IDINENC      = "Idioma não encontrado!";
      static System::String* STR_IDININF      = "Idioma não informado!";
      static System::String* STR_PAISNENC     = "País não encontrado!";
      static System::String* STR_PAISNINF     = "País não informado!";
      static System::String* STR_PROFNENC     = "Profissão não encontrada!";
      static System::String* STR_PROFNINF     = "Profissão não informada!";
      static System::String* STR_CLINENC      = "Cliente não encontrado!";
      static System::String* STR_CLININF      = "Cliente não informado!";
      static System::String* STR_LIVNENC      = "Livro não encontrado!";
      static System::String* STR_LIVNINF      = "Livro não informado!";
      static System::String* STR_PE           = "Pernambuco";
      static System::String* STR_AC           = "Acre";
      static System::String* STR_AL           = "Alagoas";
      static System::String* STR_AP           = "Amapá";
      static System::String* STR_AM           = "Amazonas";
      static System::String* STR_BA           = "Bahia";
      static System::String* STR_BR           = "Brasília";
      static System::String* STR_CE           = "Ceará";
      static System::String* STR_DF           = "Distrito Federal";
      static System::String* STR_ES           = "Espírito Santo";
      static System::String* STR_GO           = "Goiás";
      static System::String* STR_MT           = "Mato Grosso";
      static System::String* STR_MS           = "Mato Grosso do Sul";
      static System::String* STR_MG           = "Minas Gerais";
      static System::String* STR_PA           = "Pará";
      static System::String* STR_PB           = "Paraíba";
      static System::String* STR_PR           = "Paraná";
      static System::String* STR_SC           = "Santa Catarina";
      static System::String* STR_RN           = "Rio Grande do Norte";
      static System::String* STR_RS           = "Rio Grande do Sul";
      static System::String* STR_RJ           = "Rio de Janeiro";
      static System::String* STR_RO           = "Rondônia";
      static System::String* STR_RR           = "Roraima";
      static System::String* STR_SP           = "São Paulo";
      static System::String* STR_SE           = "Sergipe";
      static System::String* STR_TO           = "Tocantins";
      static System::String* STR_CPFNINF      = "CPF não informado!";
      static System::String* STR_SEXNINF      = "Sexo não informado!";
      static System::String* STR_CPFINV       = "CPF inválido!";
      static System::String* STR_TITNINF      = "Título não informado!";
      static System::String* STR_ISBNINV      = "ISBN inválido!";
      static System::String* STR_NUMINV       = "Número inválido!";
      static System::String* STR_LIVVENNINF   = "Livro(s) para vender não informado(s)!";
      static System::String* STR_LIVNEST      = "Livro não existe no estoque!";
      static System::String* STR_VENRESUC     = "Venda realizada com sucesso!";
      static System::String* STR_VENNENC      = "Venda não encontrada!";
      static System::String* STR_BAIRRONINF   = "Bairro não informado!";
      static System::String* STR_CEPNINF      = "CEP não informado!";
      static System::String* STR_CIDADENINF   = "Cidade não informada!";

      Resource();
  };
}
