class Resource:
  FRMCADASSUNTOS = 1000
  FRMCADAUTORES	 = 1001
  FRMCADEDITORAS = 1002
  FRMCADENDERECOS = 1003
  FRMCADIDIOMAS	 = 1004
  FRMCADPAISES	 = 1005
  FRMCADPROFISSOES = 1006
  FRMCADCLIENTES	 = 1007
  FRMCADLIVROS	  = 1008
  FRMVENDERLIVROS = 1009
  FRMCONVENDAS	  = 1010
  FRMALTERARSENHA = 1111

  MNU_CAD_ASSUNTOS	=	2000
  MNU_CAD_AUTORES	=	2001
  MNU_CAD_EDITORAS  =	2002
  MNU_CAD_ENDERECOS	=	2003
  MNU_CAD_IDIOMAS	=	2004
  MNU_CAD_PAISES	=	2005
  MNU_CAD_PROFISSOES	=	2006
  MNU_CAD_CLIENTES	=	2007
  MNU_CAD_LIVROS	=	2008
  MNU_CON_ASSUNTOS	=	2009
  MNU_CON_AUTORES	=	2010
  MNU_CON_EDITORAS	=	2011
  MNU_CON_ENDERECOS	=	2012
  MNU_CON_IDIOMAS	=	2013
  MNU_CON_PAISES	=	2014
  MNU_CON_PROFISSOES	=	2015
  MNU_CON_CLIENTES	=	2016
  MNU_CON_LIVROS	=	2017
  MNU_VEN_VENDERLIVROS	=	2018
  MNU_VEN_VENDASREALIZADAS	=	2019
  MNU_OP_ALTERARSENHA	=	2020
  MNU_OP_SOBRE	=	2021
  MNU_OP_SAIR	=	2022

  TLB_CADCLIENTES = 2023
  TLB_CADLIVROS = 2024
  TLB_VENDERLIVROS = 2025

  ICO_LIVRUS	      = u"Livrus.ico"

  STR_TITULO        = u"Livrus Virtus"
  STR_APPEXEC       = u"A aplica\xe7\xe3o j\xe1 est\xe1 sendo executada."
  STR_NREGJAN       = u"N\xe3o consigo registrar a janela principal."
  STR_SEMJAN        = u"Sem janela principal"
  STR_NCONBANCO     = u"N\xe3o consigo conectar com o banco de dados!"
  STR_NALOCODBC     = u"N\xe3o foi poss\xedvel alocar um manuseador para o ambiente ODBC"
  STR_CADASSUNTO    = u"Cadastro de Assuntos"
  STR_CADAUTOR      = u"Cadastro de Autores"
  STR_CADEDITORA    = u"Cadastro de Editoras"
  STR_CADENDERECO   = u"Cadastro de Endere\xe7os"
  STR_CADIDIOMA     = u"Cadastro de Idiomas"
  STR_CADPAIS       = u"Cadastro de Pa\xedses"
  STR_CADPROFISS    = u"Cadastro de Profiss\xf5es"
  STR_CADCLIENTE    = u"Cadastro de Clientes"
  STR_CADLIVRO      = u"Cadastro de Livros"
  STR_CONASSUNTO    = u"Consulta de Assuntos"
  STR_CONAUTOR      = u"Consulta de Autores"
  STR_CONEDITORA    = u"Consulta de Editoras"
  STR_CONENDERECO   = u"Consulta de Endere\xe7os"
  STR_CONIDIOMA     = u"Consulta de Idiomas"
  STR_CONPAIS       = u"Consulta de Pa\xedses"
  STR_CONPROFISS    = u"Consulta de Profiss\xf5es"
  STR_CONCLIENTE    = u"Consulta de Clientes"
  STR_CONLIVRO      = u"Consulta de Livros"
  STR_VENLIVRO      = u"Vender Livros"
  STR_CONVENLIVRO   = u"Vendas Realizadas"
  STR_ALTSENHA      = u"Altera\xe7\xe3o de Senha"
  STR_OPSOBRE       = u"Sobre o Sistema"
  STR_OPSAIR        = u"Sair do Sistema"  
  STR_SAIRSIS       = u"Deseja sair do sistema?"
  STR_EMAILNINF     = u"E-mail n\xe3o informado!"
  STR_NCCRIADLG     = u"N\xe3o consigo criar a dialog!"
  STR_CERTEXCL      = u"Certeza de excluir?"
  STR_TELNINF       = u"Telefone n\xe3o informado!"
  STR_NREGTELA      = u"N\xe3o consigo registrar a tela!"
  STR_NCCRIATELA    = u"N\xe3o consigo criar a tela!"
  STR_NCPREPSQL     = u"N\xe3o conseguiu preparar o SQL!"
  STR_NCEXECSQL     = u"N\xe3o conseguiu executar o SQL!"
  STR_DATINV        = u"Data inv\xe1lida!"
  STR_SENALTSUC     = u"Senha alterada com sucesso!"
  STR_SENNCSU       = u"A Senha atual n\xe3o confere com a senha do usu\xe1rio!"
  STR_NSENNINF      = u"Nova senha n\xe3o informada!"
  STR_NSENNCCON     = u"A Nova senha n\xe3o confere com a senha a confirmar!"
  STR_DTHRINV       = u"Data/Hora inv\xe1lida!"
  STR_USUARIO       = u"Usu\xe1rio: "
  STR_LOGSENINC     = u"Login ou senha incorretos!"
  STR_ISBNNINF      = u"ISBN n\xe3o informado!"
  STR_CODNINF       = u"C\xf3digo n\xe3o informado!"
  STR_ASSNENC       = u"Assunto n\xe3o encontrado!"
  STR_ASSNINF       = u"Assunto n\xe3o informado!"
  STR_AUTNENC       = u"Autor n\xe3o encontrado!"
  STR_AUTNINF       = u"Autor n\xe3o informado!"
  STR_EDTNENC       = u"Editora n\xe3o encontrada!"
  STR_EDTNINF       = u"Editora n\xe3o informada!"
  STR_ENDNENC       = u"Endere\xe7o n\xe3o encontrado!"
  STR_ENDNINF       = u"Endere\xe7o n\xe3o informado!"
  STR_IDINENC       = u"Idioma n\xe3o encontrado!"
  STR_IDININF       = u"Idioma n\xe3o informado!"
  STR_PAISNENC      = u"Pa\xeds n\xe3o encontrado!"
  STR_PAISNINF      = u"Pa\xeds n\xe3o informado!"
  STR_PROFNENC      = u"Profiss\xe3o n\xe3o encontrada!"
  STR_PROFNINF      = u"Profiss\xe3o n\xe3o informada!"
  STR_CLINENC       = u"Cliente n\xe3o encontrado!"
  STR_CLININF       = u"Cliente n\xe3o informado!"
  STR_LIVNENC       = u"Livro n\xe3o encontrado!"
  STR_LIVNINF       = u"Livro n\xe3o informado!"
  STR_PE            = u"Pernambuco"
  STR_AC            = u"Acre"
  STR_AL            = u"Alagoas"
  STR_AP            = u"Amap\xe1"
  STR_AM            = u"Amazonas"
  STR_BA            = u"Bahia"
  STR_BR            = u"Bras\xedlia"
  STR_CE            = u"Cear\xe1"
  STR_DF            = u"Distrito Federal"
  STR_ES            = u"Esp\xedrito Santo"
  STR_GO            = u"Goi\xe1s"
  STR_MT            = u"Mato Grosso"
  STR_MS            = u"Mato Grosso do Sul"
  STR_MG            = u"Minas Gerais"
  STR_PA            = u"Par\xe1"
  STR_PB            = u"Para\xedba"
  STR_PR            = u"Paran\xe1"
  STR_SC            = u"Santa Catarina"
  STR_RN            = u"Rio Grande do Norte"
  STR_RS            = u"Rio Grande do Sul"
  STR_RJ            = u"Rio de Janeiro"
  STR_RO            = u"Rond\xf4nia"
  STR_RR            = u"Roraima"
  STR_SP            = u"S\xe3o Paulo"
  STR_SE            = u"Sergipe"
  STR_TO            = u"Tocantins"
  STR_CPFNINF       = u"CPF n\xe3o informado!"
  STR_SEXNINF       = u"Sexo n\xe3o informado!"
  STR_CPFINV        = u"CPF inv\xe1lido!"
  STR_TITNINF       = u"T\xedtulo n\xe3o informado!"
  STR_ISBNINV       = u"ISBN inv\xe1lido!"
  STR_NUMINV        = u"N\xfamero inv\xe1lido!"
  STR_LIVVENNINF    = u"Livro(s) para vender n\xe3o informado(s)!"
  STR_LIVNEST       = u"Livro n\xe3o existe no estoque!"
  STR_VENRESUC      = u"Venda realizada com sucesso!"
  STR_VENNENC       = u"Venda n\xe3o encontrada!"
  STR_BAIRRONINF    = u"Bairro n\xe3o informado!"
  STR_CEPNINF       = u"CEP n\xe3o informado!"
  STR_CIDADENINF    = u"Cidade n\xe3o informada!"
  STR_NDCOBANCO     = u"N\xe3o consigo desconectar com o banco de dados!"
  STR_NALOCHSTM     = u"N\xe3o foi poss\xedvel alocar o manuseador para o procedimento!"
  STR_DESCPROC      = u"N\xe3o conseguiu descrever o procedimento!"
  STR_NINITRAN      = u"N\xe3o conseguiu iniciar a transa\xe7\xe3o!"
  STR_NLIBTRAN      = u"N\xe3o conseguiu liberar a transa\xe7\xe3o!"
  STR_NFINTRAN      = u"N\xe3o conseguiu finalizar a transa\xe7\xe3o!"

  def __init__(self):
    self.data = []
