// generated 2005/1/16 14:04:21 BRST by hfs@localhost.(none)
// using glademm V1.1.2
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/hfs/KDevelop/glade2/plivrus.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./CPP/frmCadLivros.cc

#include "config.h"
#include "frmCadLivros.hh"

frmCadLivros_glade::frmCadLivros_glade(
) : Gtk::Window(GTK_WINDOW_TOPLEVEL)
{  
   
   Gtk::Window *frmCadLivros = this;
   frmCadLivros->set_title("");
   frmCadLivros->set_modal(false);
   frmCadLivros->show();
}

frmCadLivros_glade::~frmCadLivros_glade()
{  
}
