// generated 2005/1/16 14:04:21 BRST by hfs@localhost.(none)
// using glademm V1.1.2
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/hfs/KDevelop/glade2/plivrus.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./CPP/frmCadastros.hh and./CPP/frmCadastros.cc

#ifndef _FRMCADASTROS_GLADE_HH
#  define _FRMCADASTROS_GLADE_HH

#include <gtk--/window.h>

class frmCadastros_glade : public Gtk::Window
{  
protected:
        
        
        frmCadastros_glade();
        
        ~frmCadastros_glade();
private:
        virtual void on_frmCadastros_show() = 0;
        virtual void on_frmCadastros_destroy() = 0;
};
#endif
