// generated 2005/1/16 14:04:21 BRST by hfs@localhost.(none)
// using glademm V1.1.2
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/hfs/KDevelop/glade2/plivrus.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./CPP/frmCadastros.cc

#include "config.h"
#include "frmCadastros.hh"

frmCadastros_glade::frmCadastros_glade(
) : Gtk::Window(GTK_WINDOW_TOPLEVEL)
{  
   
   Gtk::Window *frmCadastros = this;
   frmCadastros->set_title("");
   frmCadastros->set_modal(false);
   frmCadastros->show();
   frmCadastros->show.connect(SigC::slot(this, &frmCadastros_glade::on_frmCadastros_show));
   frmCadastros->destroy.connect(SigC::slot(this, &frmCadastros_glade::on_frmCadastros_destroy));
}

frmCadastros_glade::~frmCadastros_glade()
{  
}
