// generated 2005/1/16 14:04:21 BRST by hfs@localhost.(none)
// using glademm V1.1.2
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/hfs/KDevelop/glade2/plivrus.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./CPP/frmConsultas.hh and./CPP/frmConsultas.cc

#ifndef _FRMCONSULTAS_GLADE_HH
#  define _FRMCONSULTAS_GLADE_HH

#include <gtk--/window.h>

class frmConsultas_glade : public Gtk::Window
{  
protected:
        
        
        frmConsultas_glade();
        
        ~frmConsultas_glade();
private:
        virtual void on_frmConsultas_show() = 0;
        virtual void on_frmConsultas_destroy() = 0;
};
#endif
