// generated 2005/1/16 14:04:21 BRST by hfs@localhost.(none)
// using glademm V1.1.2
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/hfs/KDevelop/glade2/plivrus.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./CPP/frmConVendas.cc

#include "config.h"
#include "frmConVendas.hh"

frmConVendas_glade::frmConVendas_glade(
) : Gtk::Window(GTK_WINDOW_TOPLEVEL)
{  
   
   Gtk::Window *frmConVendas = this;
   frmConVendas->set_title("");
   frmConVendas->set_modal(false);
   frmConVendas->show();
   frmConVendas->destroy_event.connect(SigC::slot(this, &frmConVendas_glade::on_frmConVendas_destroy_event));
}

frmConVendas_glade::~frmConVendas_glade()
{  
}
