// generated 2005/1/16 14:04:21 BRST by hfs@localhost.(none)
// using glademm V1.1.2
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/hfs/KDevelop/glade2/plivrus.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./CPP/frmLogin.cc

#include "config.h"
#include "frmLogin.hh"

frmLogin_glade::frmLogin_glade(
) : Gtk::Window(GTK_WINDOW_TOPLEVEL)
{  
   
   Gtk::Window *frmLogin = this;
   frmLogin->set_title("");
   frmLogin->set_modal(false);
   frmLogin->show();
   frmLogin->show.connect(SigC::slot(this, &frmLogin_glade::on_frmLogin_show));
   frmLogin->destroy.connect(SigC::slot(this, &frmLogin_glade::on_frmLogin_destroy));
}

frmLogin_glade::~frmLogin_glade()
{  
}
