// generated 2005/1/16 14:04:21 BRST by hfs@localhost.(none)
// using glademm V1.1.2
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/hfs/KDevelop/glade2/plivrus.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./CPP/frmLogin.hh and./CPP/frmLogin.cc

#ifndef _FRMLOGIN_GLADE_HH
#  define _FRMLOGIN_GLADE_HH

#include <gtk--/window.h>

class frmLogin_glade : public Gtk::Window
{  
protected:
        
        
        frmLogin_glade();
        
        ~frmLogin_glade();
private:
        virtual void on_frmLogin_show() = 0;
        virtual void on_frmLogin_destroy() = 0;
};
#endif
