// generated 2005/1/16 14:04:21 BRST by hfs@localhost.(none)
// using glademm V1.1.2
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/hfs/KDevelop/glade2/plivrus.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./CPP/frmPrincipal.hh and./CPP/frmPrincipal.cc

#ifndef _FRMPRINCIPAL_GLADE_HH
#  define _FRMPRINCIPAL_GLADE_HH

#include <gtk--/window.h>

class frmPrincipal_glade : public Gtk::Window
{  
protected:
        
        
        frmPrincipal_glade();
        
        ~frmPrincipal_glade();
private:
        virtual void on_mnuCadAssuntos_activate() = 0;
        virtual void on_mnuCadAutores_activate() = 0;
        virtual void on_mnuCadEditoras_activate() = 0;
        virtual void on_mnuCadEnderecos_activate() = 0;
        virtual void on_mnuCadIdiomas_activate() = 0;
        virtual void on_mnuCadPaises_activate() = 0;
        virtual void on_mnuCadProfissoes_activate() = 0;
        virtual void on_mnuCadClientes_activate() = 0;
        virtual void on_mnuCadLivros_activate() = 0;
        virtual void on_mnuConAssuntos_activate() = 0;
        virtual void on_mnuConAutores_activate() = 0;
        virtual void on_mnuConEditoras_activate() = 0;
        virtual void on_mnuConEnderecos_activate() = 0;
        virtual void on_mnuConIdiomas_activate() = 0;
        virtual void on_mnuConPaises_activate() = 0;
        virtual void on_mnuConProfissoes_activate() = 0;
        virtual void on_mnuConClientes_activate() = 0;
        virtual void on_mnuConLivros_activate() = 0;
        virtual void on_mnuVenderLivros_activate() = 0;
        virtual void on_mnuVendasRealizadas_activate() = 0;
        virtual void on_mnuVendas_activate() = 0;
        virtual void on_mnuJanHorizontal_activate() = 0;
        virtual void on_mnuJanVertical_activate() = 0;
        virtual void on_mnuJanCascata_activate() = 0;
        virtual void on_mnuJanOrganizarIcones_activate() = 0;
        virtual void on_mnuJanelas_activate() = 0;
        virtual void on_mnuAlterarsenha_activate() = 0;
        virtual void on_mnuSobre_activate() = 0;
        virtual void on_mnuSair_activate() = 0;
        virtual void on_frmPrincipal_show() = 0;
        virtual void on_frmPrincipal_destroy() = 0;
};
#endif
