// generated 2005/1/16 14:04:21 BRST by hfs@localhost.(none)
// using glademm V1.1.2
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/hfs/KDevelop/glade2/plivrus.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./CPP/frmPrincipal.cc

#include "config.h"
#include "frmPrincipal.hh"
#include <gtk--/menuitem.h>
#include <gtk--/menu.h>
#include <gtk--/menubar.h>
#include <gtk--/button.h>
#include <gtk--/separator.h>
#include <gtk--/toolbar.h>
#include <gtk--/fixed.h>
#include <gtk--/statusbar.h>
#include <gtk--/box.h>

frmPrincipal_glade::frmPrincipal_glade(
) : Gtk::Window(GTK_WINDOW_TOPLEVEL)
{  
   
   Gtk::Window *frmPrincipal = this;
   Gtk::MenuItem *mnuCadAssuntos = NULL;
   Gtk::MenuItem *mnuCadAutores = NULL;
   Gtk::MenuItem *mnuCadEditoras = NULL;
   Gtk::MenuItem *mnuCadEnderecos = NULL;
   Gtk::MenuItem *mnuCadIdiomas = NULL;
   Gtk::MenuItem *mnuCadPaises = NULL;
   Gtk::MenuItem *mnuCadProfissoes = NULL;
   Gtk::MenuItem *separator2 = NULL;
   Gtk::MenuItem *mnuCadClientes = NULL;
   Gtk::MenuItem *mnuCadLivros = NULL;
   Gtk::Menu *mnuCadastros_menu = manage(new class Gtk::Menu());
   Gtk::MenuItem *mnuCadastros = NULL;
   Gtk::MenuItem *mnuConAssuntos = NULL;
   Gtk::MenuItem *mnuConAutores = NULL;
   Gtk::MenuItem *mnuConEditoras = NULL;
   Gtk::MenuItem *mnuConEnderecos = NULL;
   Gtk::MenuItem *mnuConIdiomas = NULL;
   Gtk::MenuItem *mnuConPaises = NULL;
   Gtk::MenuItem *mnuConProfissoes = NULL;
   Gtk::MenuItem *separator3 = NULL;
   Gtk::MenuItem *mnuConClientes = NULL;
   Gtk::MenuItem *mnuConLivros = NULL;
   Gtk::Menu *mnuPesquisas_menu = manage(new class Gtk::Menu());
   Gtk::MenuItem *mnuPesquisas = NULL;
   Gtk::MenuItem *mnuVenderLivros = NULL;
   Gtk::MenuItem *mnuVendasRealizadas = NULL;
   Gtk::Menu *mnuVendas_menu = manage(new class Gtk::Menu());
   Gtk::MenuItem *mnuVendas = NULL;
   Gtk::MenuItem *mnuJanHorizontal = NULL;
   Gtk::MenuItem *mnuJanVertical = NULL;
   Gtk::MenuItem *mnuJanCascata = NULL;
   Gtk::MenuItem *mnuJanOrganizarIcones = NULL;
   Gtk::Menu *mnuJanelas_menu = manage(new class Gtk::Menu());
   Gtk::MenuItem *mnuJanelas = NULL;
   Gtk::MenuItem *mnuAlterarsenha = NULL;
   Gtk::MenuItem *separator1 = NULL;
   Gtk::MenuItem *mnuSobre = NULL;
   Gtk::MenuItem *mnuSair = NULL;
   Gtk::Menu *mnuOpcoes_menu = manage(new class Gtk::Menu());
   Gtk::MenuItem *mnuOpcoes = NULL;
   Gtk::MenuBar *menubar1 = manage(new class Gtk::MenuBar());
   Gtk::VSeparator *vseparator1 = manage(new class Gtk::VSeparator());
   Gtk::Toolbar *toolbar1 = manage(new class Gtk::Toolbar(GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_BOTH));
   Gtk::Fixed *fixed1 = manage(new class Gtk::Fixed());
   Gtk::Statusbar *BarraStatus1 = manage(new class Gtk::Statusbar());
   Gtk::Statusbar *BarraStatus2 = manage(new class Gtk::Statusbar());
   Gtk::HBox *hbox1 = manage(new class Gtk::HBox(false, 0));
   Gtk::VBox *vbox1 = manage(new class Gtk::VBox(false, 0));
   
   mnuCadastros_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("_Assuntos"));
   mnuCadAssuntos = (Gtk::MenuItem *)mnuCadastros_menu->items().back();
   
   mnuCadastros_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("A_utores"));
   mnuCadAutores = (Gtk::MenuItem *)mnuCadastros_menu->items().back();
   
   mnuCadastros_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("_Editoras"));
   mnuCadEditoras = (Gtk::MenuItem *)mnuCadastros_menu->items().back();
   
   mnuCadastros_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("E_ndereços"));
   mnuCadEnderecos = (Gtk::MenuItem *)mnuCadastros_menu->items().back();
   
   mnuCadastros_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("_Idiomas"));
   mnuCadIdiomas = (Gtk::MenuItem *)mnuCadastros_menu->items().back();
   
   mnuCadastros_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("_Países"));
   mnuCadPaises = (Gtk::MenuItem *)mnuCadastros_menu->items().back();
   
   mnuCadastros_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("P_rofissões"));
   mnuCadProfissoes = (Gtk::MenuItem *)mnuCadastros_menu->items().back();
   
   mnuCadastros_menu->items().push_back(Gtk::Menu_Helpers::SeparatorElem());
   separator2 = (Gtk::MenuItem *)mnuCadastros_menu->items().back();
   
   mnuCadastros_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("_Clientes"));
   mnuCadClientes = (Gtk::MenuItem *)mnuCadastros_menu->items().back();
   
   mnuCadastros_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("_Livros"));
   mnuCadLivros = (Gtk::MenuItem *)mnuCadastros_menu->items().back();
   
   mnuPesquisas_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("_Assuntos"));
   mnuConAssuntos = (Gtk::MenuItem *)mnuPesquisas_menu->items().back();
   
   mnuPesquisas_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("A_utores"));
   mnuConAutores = (Gtk::MenuItem *)mnuPesquisas_menu->items().back();
   
   mnuPesquisas_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("_Editoras"));
   mnuConEditoras = (Gtk::MenuItem *)mnuPesquisas_menu->items().back();
   
   mnuPesquisas_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("E_ndereços"));
   mnuConEnderecos = (Gtk::MenuItem *)mnuPesquisas_menu->items().back();
   
   mnuPesquisas_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("_Idiomas"));
   mnuConIdiomas = (Gtk::MenuItem *)mnuPesquisas_menu->items().back();
   
   mnuPesquisas_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("_Países"));
   mnuConPaises = (Gtk::MenuItem *)mnuPesquisas_menu->items().back();
   
   mnuPesquisas_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("P_rofissões"));
   mnuConProfissoes = (Gtk::MenuItem *)mnuPesquisas_menu->items().back();
   
   mnuPesquisas_menu->items().push_back(Gtk::Menu_Helpers::SeparatorElem());
   separator3 = (Gtk::MenuItem *)mnuPesquisas_menu->items().back();
   
   mnuPesquisas_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("_Clientes"));
   mnuConClientes = (Gtk::MenuItem *)mnuPesquisas_menu->items().back();
   
   mnuPesquisas_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("_Livros"));
   mnuConLivros = (Gtk::MenuItem *)mnuPesquisas_menu->items().back();
   
   mnuVendas_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("_Vender Livros"));
   mnuVenderLivros = (Gtk::MenuItem *)mnuVendas_menu->items().back();
   
   mnuVendas_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("Vendas _realizadas"));
   mnuVendasRealizadas = (Gtk::MenuItem *)mnuVendas_menu->items().back();
   
   mnuJanelas_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("Lado a lado _horizontal"));
   mnuJanHorizontal = (Gtk::MenuItem *)mnuJanelas_menu->items().back();
   
   mnuJanelas_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("Lado a lado _vertical"));
   mnuJanVertical = (Gtk::MenuItem *)mnuJanelas_menu->items().back();
   
   mnuJanelas_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("Em _cascata"));
   mnuJanCascata = (Gtk::MenuItem *)mnuJanelas_menu->items().back();
   
   mnuJanelas_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("_Organizar Ícones"));
   mnuJanOrganizarIcones = (Gtk::MenuItem *)mnuJanelas_menu->items().back();
   
   mnuOpcoes_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("_Alterar Senha"));
   mnuAlterarsenha = (Gtk::MenuItem *)mnuOpcoes_menu->items().back();
   
   mnuOpcoes_menu->items().push_back(Gtk::Menu_Helpers::SeparatorElem());
   separator1 = (Gtk::MenuItem *)mnuOpcoes_menu->items().back();
   
   mnuOpcoes_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("_Sobre"));
   mnuSobre = (Gtk::MenuItem *)mnuOpcoes_menu->items().back();
   
   mnuOpcoes_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("Sa_ir"));
   mnuSair = (Gtk::MenuItem *)mnuOpcoes_menu->items().back();
   
   menubar1->items().push_back(Gtk::Menu_Helpers::MenuElem("_Cadastros", *mnuCadastros_menu));
   mnuCadastros = (Gtk::MenuItem *)menubar1->items().back();
   
   menubar1->items().push_back(Gtk::Menu_Helpers::MenuElem("_Pesquisas", *mnuPesquisas_menu));
   mnuPesquisas = (Gtk::MenuItem *)menubar1->items().back();
   
   menubar1->items().push_back(Gtk::Menu_Helpers::MenuElem("_Vendas", *mnuVendas_menu));
   mnuVendas = (Gtk::MenuItem *)menubar1->items().back();
   
   menubar1->items().push_back(Gtk::Menu_Helpers::MenuElem("_Janelas", *mnuJanelas_menu));
   mnuJanelas = (Gtk::MenuItem *)menubar1->items().back();
   
   menubar1->items().push_back(Gtk::Menu_Helpers::MenuElem("_Opções", *mnuOpcoes_menu));
   mnuOpcoes = (Gtk::MenuItem *)menubar1->items().back();
   
   toolbar1->tools().push_back(Gtk::Toolbar_Helpers::ButtonElem("button1", 0));
   Gtk::Button *button1 = static_cast<Gtk::Button *>(toolbar1->tools().back()->get_widget());
   
   toolbar1->tools().push_back(Gtk::Toolbar_Helpers::ButtonElem("button2", 0));
   Gtk::Button *button2 = static_cast<Gtk::Button *>(toolbar1->tools().back()->get_widget());
   
   toolbar1->tools().push_back(Gtk::Toolbar_Helpers::ButtonElem("button3", 0));
   Gtk::Button *button3 = static_cast<Gtk::Button *>(toolbar1->tools().back()->get_widget());
   toolbar1->tools().push_back(Gtk::Toolbar_Helpers::Element(*vseparator1));
   
   
   toolbar1->tools().push_back(Gtk::Toolbar_Helpers::ButtonElem("button4", 0));
   Gtk::Button *button4 = static_cast<Gtk::Button *>(toolbar1->tools().back()->get_widget());
   
   toolbar1->tools().push_back(Gtk::Toolbar_Helpers::ButtonElem("button5", 0));
   Gtk::Button *button5 = static_cast<Gtk::Button *>(toolbar1->tools().back()->get_widget());
   toolbar1->set_tooltips(true);
   BarraStatus1->set_usize(130,21);
   BarraStatus2->set_usize(130,21);
   hbox1->pack_start(*BarraStatus1, false, false, 0);
   hbox1->pack_start(*BarraStatus2);
   vbox1->pack_start(*menubar1, false, false, 0);
   vbox1->pack_start(*toolbar1, false, false, 0);
   vbox1->pack_start(*fixed1);
   vbox1->pack_start(*hbox1, false, false, 0);
   frmPrincipal->set_title("Livrus Virtus");
   frmPrincipal->set_default_size(500,400);
   frmPrincipal->set_modal(false);
   frmPrincipal->add(*vbox1);
   mnuCadAssuntos->show();
   mnuCadAutores->show();
   mnuCadEditoras->show();
   mnuCadEnderecos->show();
   mnuCadIdiomas->show();
   mnuCadPaises->show();
   mnuCadProfissoes->show();
   separator2->show();
   mnuCadClientes->show();
   mnuCadLivros->show();
   mnuCadastros_menu->show();
   mnuCadastros->show();
   mnuConAssuntos->show();
   mnuConAutores->show();
   mnuConEditoras->show();
   mnuConEnderecos->show();
   mnuConIdiomas->show();
   mnuConPaises->show();
   mnuConProfissoes->show();
   separator3->show();
   mnuConClientes->show();
   mnuConLivros->show();
   mnuPesquisas_menu->show();
   mnuPesquisas->show();
   mnuVenderLivros->show();
   mnuVendasRealizadas->show();
   mnuVendas_menu->show();
   mnuVendas->show();
   mnuJanHorizontal->show();
   mnuJanVertical->show();
   mnuJanCascata->show();
   mnuJanOrganizarIcones->show();
   mnuJanelas_menu->show();
   mnuJanelas->show();
   mnuAlterarsenha->show();
   separator1->show();
   mnuSobre->show();
   mnuSair->show();
   mnuOpcoes_menu->show();
   mnuOpcoes->show();
   menubar1->show();
   vseparator1->show();
   toolbar1->show();
   fixed1->show();
   BarraStatus1->show();
   BarraStatus2->show();
   hbox1->show();
   vbox1->show();
   frmPrincipal->show();
   mnuCadAssuntos->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuCadAssuntos_activate));
   mnuCadAutores->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuCadAutores_activate));
   mnuCadEditoras->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuCadEditoras_activate));
   mnuCadEnderecos->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuCadEnderecos_activate));
   mnuCadIdiomas->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuCadIdiomas_activate));
   mnuCadPaises->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuCadPaises_activate));
   mnuCadProfissoes->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuCadProfissoes_activate));
   mnuCadClientes->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuCadClientes_activate));
   mnuCadLivros->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuCadLivros_activate));
   mnuConAssuntos->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuConAssuntos_activate));
   mnuConAutores->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuConAutores_activate));
   mnuConEditoras->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuConEditoras_activate));
   mnuConEnderecos->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuConEnderecos_activate));
   mnuConIdiomas->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuConIdiomas_activate));
   mnuConPaises->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuConPaises_activate));
   mnuConProfissoes->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuConProfissoes_activate));
   mnuConClientes->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuConClientes_activate));
   mnuConLivros->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuConLivros_activate));
   mnuVenderLivros->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuVenderLivros_activate));
   mnuVendasRealizadas->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuVendasRealizadas_activate));
   mnuVendas->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuVendas_activate));
   mnuJanHorizontal->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuJanHorizontal_activate));
   mnuJanVertical->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuJanVertical_activate));
   mnuJanCascata->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuJanCascata_activate));
   mnuJanOrganizarIcones->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuJanOrganizarIcones_activate));
   mnuJanelas->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuJanelas_activate));
   mnuAlterarsenha->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuAlterarsenha_activate));
   mnuSobre->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuSobre_activate));
   mnuSair->activate.connect(SigC::slot(this, &frmPrincipal_glade::on_mnuSair_activate));
   frmPrincipal->show.connect(SigC::slot(this, &frmPrincipal_glade::on_frmPrincipal_show));
   frmPrincipal->destroy.connect(SigC::slot(this, &frmPrincipal_glade::on_frmPrincipal_destroy));
}

frmPrincipal_glade::~frmPrincipal_glade()
{  
}
