// generated 2005/1/16 14:04:21 BRST by hfs@localhost.(none)
// using glademm V1.1.2
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/hfs/KDevelop/glade2/plivrus.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./CPP/frmSplash.cc

#include "config.h"
#include "frmSplash.hh"

frmSplash_glade::frmSplash_glade(
) : Gtk::Window(GTK_WINDOW_TOPLEVEL)
{  
   
   Gtk::Window *frmSplash = this;
   frmSplash->set_title("");
   frmSplash->set_modal(false);
   frmSplash->show();
   frmSplash->show.connect(SigC::slot(this, &frmSplash_glade::on_frmSplash_show));
   frmSplash->destroy.connect(SigC::slot(this, &frmSplash_glade::on_frmSplash_destroy));
}

frmSplash_glade::~frmSplash_glade()
{  
}
