// generated 2005/1/16 14:04:21 BRST by hfs@localhost.(none)
// using glademm V1.1.2
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/hfs/KDevelop/glade2/plivrus.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./CPP/frmSplash.hh and./CPP/frmSplash.cc

#ifndef _FRMSPLASH_GLADE_HH
#  define _FRMSPLASH_GLADE_HH

#include <gtk--/window.h>

class frmSplash_glade : public Gtk::Window
{  
protected:
        
        
        frmSplash_glade();
        
        ~frmSplash_glade();
private:
        virtual void on_frmSplash_show() = 0;
        virtual void on_frmSplash_destroy() = 0;
};
#endif
