// generated 2005/1/16 14:04:21 BRST by hfs@localhost.(none)
// using glademm V1.1.2
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/hfs/KDevelop/glade2/plivrus.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./CPP/frmVenderLivros.hh and./CPP/frmVenderLivros.cc

#ifndef _FRMVENDERLIVROS_GLADE_HH
#  define _FRMVENDERLIVROS_GLADE_HH

#include <gtk--/window.h>

class frmVenderLivros_glade : public Gtk::Window
{  
protected:
        
        
        frmVenderLivros_glade();
        
        ~frmVenderLivros_glade();
private:
        virtual void on_frmVenderLivros_destroy_event() = 0;
};
#endif
