// generated 2005/1/16 14:04:21 BRST by hfs@localhost.(none)
// using glademm V1.1.2
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/hfs/KDevelop/glade2/plivrus.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./CPP/frmVenderLivros.cc

#include "config.h"
#include "frmVenderLivros.hh"

frmVenderLivros_glade::frmVenderLivros_glade(
) : Gtk::Window(GTK_WINDOW_TOPLEVEL)
{  
   
   Gtk::Window *frmVenderLivros = this;
   frmVenderLivros->set_title("");
   frmVenderLivros->set_modal(false);
   frmVenderLivros->show();
   frmVenderLivros->destroy_event.connect(SigC::slot(this, &frmVenderLivros_glade::on_frmVenderLivros_destroy_event));
}

frmVenderLivros_glade::~frmVenderLivros_glade()
{  
}
