#-----------------------------------------------------------------------------
# Perl source generated by wxDesigner from file: Livrus.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

use Wx;
use strict;

use Wx qw( wxDefaultSize wxDefaultPosition wxID_OK wxID_CANCEL wxID_YES );
use Wx qw( wxVERTICAL wxHORIZONTAL wxALL wxLEFT wxRIGHT wxTOP wxBOTTOM wxCENTRE wxGROW );
use Wx qw( wxALIGN_RIGHT wxALIGN_BOTTOM wxALIGN_CENTER wxALIGN_CENTER_VERTICAL wxALIGN_CENTER_HORIZONTAL );
use Wx qw( wxWANTS_CHARS wxTE_PASSWORD );

# Window functions

use vars qw($LAB_CODIGO); $LAB_CODIGO = 10000;
use vars qw($EDT_CODIGO); $EDT_CODIGO = 10001;
use vars qw($LAB_DESCRICAO); $LAB_DESCRICAO = 10002;
use vars qw($EDT_DESCRICAO); $EDT_DESCRICAO = 10003;
use vars qw($BTN_PESQUISAR); $BTN_PESQUISAR = 10004;
use vars qw($BTN_ANTERIOR); $BTN_ANTERIOR = 10005;
use vars qw($BTN_PROXIMO); $BTN_PROXIMO = 10006;
use vars qw($BTN_SALVAR); $BTN_SALVAR = 10007;
use vars qw($BTN_EXCLUIR); $BTN_EXCLUIR = 10008;
use vars qw($BTN_LIMPAR); $BTN_LIMPAR = 10009;
use vars qw($BTN_FECHAR); $BTN_FECHAR = 10010;

sub frmCadAssuntos {
    my( $item0 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item1 ) = Wx::FlexGridSizer->new( 0, 2, 0, 0 );
    
    my( $item2 ) = Wx::FlexGridSizer->new( 0, 1, 0, 0 );
    
    my( $item3 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item4 ) = Wx::StaticText->new( $_[0], $main::LAB_CODIGO, "Código:", wxDefaultPosition, wxDefaultSize, 0 );
    $item4->SetName( "labCodigo" );
    $item3->AddWindow( $item4, 5, wxALIGN_CENTER_VERTICAL, 0 );

    my( $item5 ) = Wx::TextCtrl->new( $_[0], $main::EDT_CODIGO, "", wxDefaultPosition, [80,-1], 0 );
    $item5->SetName( "edtCodigo" );
    $item3->AddWindow( $item5, 0, wxALIGN_CENTER, 0 );

    $item2->Add( $item3, 0, wxALIGN_CENTER_VERTICAL, 0 );

    my( $item6 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item7 ) = Wx::StaticText->new( $_[0], $main::LAB_DESCRICAO, "Assunto:", wxDefaultPosition, wxDefaultSize, 0 );
    $item7->SetName( "labDescricao" );
    $item6->AddWindow( $item7, 5, wxALIGN_CENTER_VERTICAL, 0 );

    my( $item8 ) = Wx::TextCtrl->new( $_[0], $main::EDT_DESCRICAO, "", wxDefaultPosition, [200,-1], 0 );
    $item8->SetName( "edtDescricao" );
    $item6->AddWindow( $item8, 0, wxALIGN_CENTER, 0 );

    $item2->Add( $item6, 0, wxALIGN_CENTER, 0 );

    $item1->Add( $item2, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    my( $item9 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item10 ) = Wx::Button->new( $_[0], $main::BTN_PESQUISAR, "Pesquisar", wxDefaultPosition, wxDefaultSize, 0 );
    $item10->SetDefault();
    $item10->SetName( "btnPesquisar" );
    $item9->AddWindow( $item10, 0, wxALIGN_CENTER|wxALL, 0 );

    my( $item11 ) = Wx::Button->new( $_[0], $main::BTN_ANTERIOR, "Anterior", wxDefaultPosition, wxDefaultSize, 0 );
    $item11->SetName( "btnAnterior" );
    $item11->Enable( 0 );
    $item9->AddWindow( $item11, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item12 ) = Wx::Button->new( $_[0], $main::BTN_PROXIMO, "Próximo", wxDefaultPosition, wxDefaultSize, 0 );
    $item12->SetName( "btnProximo" );
    $item12->Enable( 0 );
    $item9->AddWindow( $item12, 0, wxALIGN_CENTER|wxALL, 0 );

    $item1->Add( $item9, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    $item0->Add( $item1, 0, wxGROW|wxALIGN_CENTER_VERTICAL, 0 );

    my( $item13 ) = Wx::BoxSizer->new( wxHORIZONTAL );
    
    my( $item14 ) = Wx::Button->new( $_[0], $main::BTN_SALVAR, "Salvar", wxDefaultPosition, wxDefaultSize, 0 );
    $item14->SetName( "btnSalvar" );
    $item14->Enable( 0 );
    $item13->AddWindow( $item14, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item15 ) = Wx::Button->new( $_[0], $main::BTN_EXCLUIR, "Excluir", wxDefaultPosition, wxDefaultSize, 0 );
    $item15->SetName( "btnExcluir" );
    $item15->Enable( 0 );
    $item13->AddWindow( $item15, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item16 ) = Wx::Button->new( $_[0], $main::BTN_LIMPAR, "Limpar", wxDefaultPosition, wxDefaultSize, 0 );
    $item16->SetName( "btnLimpar" );
    $item13->AddWindow( $item16, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item17 ) = Wx::Button->new( $_[0], $main::BTN_FECHAR, "Fechar", wxDefaultPosition, wxDefaultSize, 0 );
    $item17->SetName( "btnFechar" );
    $item13->AddWindow( $item17, 0, wxALIGN_CENTER|wxALL, 5 );

    $item0->Add( $item13, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $set_size ) = @_ >= 3 ? $_[2] : 1;
    my( $call_fit ) = @_ >= 2 ? $_[1] : 1;
    if( $set_size == 1 ) {
         $_[0]->SetAutoLayout( 1 );
         $_[0]->SetSizer( $item0 );
         
         if( $call_fit == 1 ) {
             $item0->Fit( $_[0] );
             $item0->SetSizeHints( $_[0] );
         }
    }
    
    $item0;
}


sub frmCadAutores {
    my( $item0 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item1 ) = Wx::FlexGridSizer->new( 0, 2, 0, 0 );
    
    my( $item2 ) = Wx::FlexGridSizer->new( 0, 1, 0, 0 );
    
    my( $item3 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item4 ) = Wx::StaticText->new( $_[0], $main::LAB_CODIGO, "Código:", wxDefaultPosition, wxDefaultSize, 0 );
    $item4->SetName( "labCodigo" );
    $item3->AddWindow( $item4, 5, wxALIGN_CENTER_VERTICAL, 5 );

    my( $item5 ) = Wx::TextCtrl->new( $_[0], $main::EDT_CODIGO, "", wxDefaultPosition, [80,-1], 0 );
    $item5->SetName( "edtCodigo" );
    $item3->AddWindow( $item5, 0, wxALIGN_CENTER|wxALL, 0 );

    $item2->Add( $item3, 0, wxALIGN_CENTER_VERTICAL, 0 );

    my( $item6 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item7 ) = Wx::StaticText->new( $_[0], $main::LAB_DESCRICAO, "Autor:", wxDefaultPosition, [100,-1], 0 );
    $item7->SetName( "labDescricao" );
    $item6->AddWindow( $item7, 5, wxALIGN_CENTER_VERTICAL, 5 );

    my( $item8 ) = Wx::TextCtrl->new( $_[0], $main::EDT_DESCRICAO, "", wxDefaultPosition, [200,-1], 0 );
    $item8->SetName( "edtDescricao" );
    $item6->AddWindow( $item8, 0, wxALIGN_CENTER|wxALL, 0 );

    $item2->Add( $item6, 0, wxALIGN_CENTER, 0 );

    $item1->Add( $item2, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    my( $item9 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item10 ) = Wx::Button->new( $_[0], $main::BTN_PESQUISAR, "Pesquisar", wxDefaultPosition, wxDefaultSize, 0 );
    $item10->SetDefault();
    $item10->SetName( "btnPesquisar" );
    $item9->AddWindow( $item10, 0, wxALIGN_CENTER|wxALL, 0 );

    my( $item11 ) = Wx::Button->new( $_[0], $main::BTN_ANTERIOR, "Anterior", wxDefaultPosition, wxDefaultSize, 0 );
    $item11->SetName( "btnAnterior" );
    $item11->Enable( 0 );
    $item9->AddWindow( $item11, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item12 ) = Wx::Button->new( $_[0], $main::BTN_PROXIMO, "Próximo", wxDefaultPosition, wxDefaultSize, 0 );
    $item12->SetName( "btnProximo" );
    $item12->Enable( 0 );
    $item9->AddWindow( $item12, 0, wxALIGN_CENTER|wxALL, 0 );

    $item1->Add( $item9, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    $item0->Add( $item1, 0, wxGROW|wxALIGN_CENTER_VERTICAL, 0 );

    my( $item13 ) = Wx::BoxSizer->new( wxHORIZONTAL );
    
    my( $item14 ) = Wx::Button->new( $_[0], $main::BTN_SALVAR, "Salvar", wxDefaultPosition, wxDefaultSize, 0 );
    $item14->SetName( "btnSalvar" );
    $item14->Enable( 0 );
    $item13->AddWindow( $item14, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item15 ) = Wx::Button->new( $_[0], $main::BTN_EXCLUIR, "Excluir", wxDefaultPosition, wxDefaultSize, 0 );
    $item15->SetName( "btnExcluir" );
    $item15->Enable( 0 );
    $item13->AddWindow( $item15, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item16 ) = Wx::Button->new( $_[0], $main::BTN_LIMPAR, "Limpar", wxDefaultPosition, wxDefaultSize, 0 );
    $item16->SetName( "btnLimpar" );
    $item13->AddWindow( $item16, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item17 ) = Wx::Button->new( $_[0], $main::BTN_FECHAR, "Fechar", wxDefaultPosition, wxDefaultSize, 0 );
    $item17->SetName( "btnFechar" );
    $item13->AddWindow( $item17, 0, wxALIGN_CENTER|wxALL, 5 );

    $item0->Add( $item13, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $set_size ) = @_ >= 3 ? $_[2] : 1;
    my( $call_fit ) = @_ >= 2 ? $_[1] : 1;
    if( $set_size == 1 ) {
         $_[0]->SetAutoLayout( 1 );
         $_[0]->SetSizer( $item0 );
         
         if( $call_fit == 1 ) {
             $item0->Fit( $_[0] );
             $item0->SetSizeHints( $_[0] );
         }
    }
    
    $item0;
}

use vars qw($GRID_CONSULTA); $GRID_CONSULTA = 10011;
use vars qw($LAB_REGISTROS); $LAB_REGISTROS = 10012;
use vars qw($LAB_LIMPAR); $LAB_LIMPAR = 10013;

sub frmConAssuntos {
    my( $item0 ) = Wx::FlexGridSizer->new( 0, 1, 0, 0 );
    
    my( $item1 ) = Wx::BoxSizer->new( wxHORIZONTAL );
    
    my( $item2 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item3 ) = Wx::StaticText->new( $_[0], $main::LAB_DESCRICAO, "Assunto:", wxDefaultPosition, [40,-1], 0 );
    $item3->SetName( "labDescricao" );
    $item2->AddWindow( $item3, 5, wxALIGN_CENTER_VERTICAL, 5 );

    my( $item4 ) = Wx::TextCtrl->new( $_[0], $main::EDT_DESCRICAO, "", wxDefaultPosition, [250,-1], 0 );
    $item4->SetName( "edtDescricao" );
    $item2->AddWindow( $item4, 0, wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    $item1->Add( $item2, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    my( $item5 ) = Wx::Button->new( $_[0], $main::BTN_PESQUISAR, "Pesquisar", wxDefaultPosition, wxDefaultSize, 0 );
    $item5->SetName( "btnPesquisar" );
    $item1->AddWindow( $item5, 0, wxALIGN_BOTTOM|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    $item0->Add( $item1, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item6 ) = Wx::Grid->new( $_[0], $main::GRID_CONSULTA, wxDefaultPosition, [300,150], wxWANTS_CHARS );
    $item6->CreateGrid( 2, 2 );
    $item6->SetName( "gridConsulta" );
    $item0->AddWindow( $item6, 0, wxGROW, 0 );

    my( $item7 ) = Wx::FlexGridSizer->new( 0, 2, 0, 0 );
    
    my( $item8 ) = Wx::BoxSizer->new( wxHORIZONTAL );
    
    my( $item9 ) = Wx::StaticText->new( $_[0], $main::LAB_REGISTROS, "Registro: 0 de 0", wxDefaultPosition, wxDefaultSize, 0 );
    $item9->SetName( "labRegistros" );
    $item8->AddWindow( $item9, 0, wxALIGN_CENTER|wxALL, 5 );

    $item7->Add( $item8, 0, wxALIGN_BOTTOM|wxALL, 5 );

    my( $item10 ) = Wx::BoxSizer->new( wxHORIZONTAL );
    
    my( $item11 ) = Wx::Button->new( $_[0], $main::LAB_LIMPAR, "Limpar", wxDefaultPosition, wxDefaultSize, 0 );
    $item11->SetName( "btnLimpar" );
    $item10->AddWindow( $item11, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item12 ) = Wx::Button->new( $_[0], $main::BTN_FECHAR, "Fechar", wxDefaultPosition, wxDefaultSize, 0 );
    $item12->SetName( "btnFechar" );
    $item10->AddWindow( $item12, 0, wxALIGN_CENTER|wxALL, 5 );

    $item7->Add( $item10, 0, wxGROW|wxALIGN_BOTTOM|wxALL, 5 );

    $item0->Add( $item7, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $set_size ) = @_ >= 3 ? $_[2] : 1;
    my( $call_fit ) = @_ >= 2 ? $_[1] : 1;
    if( $set_size == 1 ) {
         $_[0]->SetAutoLayout( 1 );
         $_[0]->SetSizer( $item0 );
         
         if( $call_fit == 1 ) {
             $item0->Fit( $_[0] );
             $item0->SetSizeHints( $_[0] );
         }
    }
    
    $item0;
}

use vars qw($ID_STATICBITMAP); $ID_STATICBITMAP = 10014;

sub frmSplash {
    my( $item0 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item1 ) = Wx::StaticBitmap->new( $_[0], $main::ID_STATICBITMAP, ListaBitmaps( 6 ), wxDefaultPosition, wxDefaultSize );
    $item0->AddWindow( $item1, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $set_size ) = @_ >= 3 ? $_[2] : 1;
    my( $call_fit ) = @_ >= 2 ? $_[1] : 1;
    if( $set_size == 1 ) {
         $_[0]->SetAutoLayout( 1 );
         $_[0]->SetSizer( $item0 );
         
         if( $call_fit == 1 ) {
             $item0->Fit( $_[0] );
             $item0->SetSizeHints( $_[0] );
         }
    }
    
    $item0;
}

use vars qw($LAB_LOGIN); $LAB_LOGIN = 10015;
use vars qw($EDT_LOGIN); $EDT_LOGIN = 10016;
use vars qw($LAB_SENHA); $LAB_SENHA = 10017;
use vars qw($EDT_SENHA); $EDT_SENHA = 10018;
use vars qw($BTN_LOGIN); $BTN_LOGIN = 10019;
use vars qw($BTN_CANCELAR); $BTN_CANCELAR = 10020;

sub frmLogin {
    my( $item0 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item1 ) = Wx::BoxSizer->new( wxHORIZONTAL );
    
    my( $item2 ) = Wx::StaticBitmap->new( $_[0], $main::ID_STATICBITMAP, ListaBitmaps( 5 ), wxDefaultPosition, wxDefaultSize );
    $item1->AddWindow( $item2, 0, wxALIGN_CENTER|wxALL, 0 );

    my( $item3 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item4 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item5 ) = Wx::StaticText->new( $_[0], $main::LAB_LOGIN, "Login:", wxDefaultPosition, wxDefaultSize, 0 );
    $item5->SetName( "labLogin" );
    $item4->AddWindow( $item5, 0, wxALIGN_CENTER_VERTICAL|wxRIGHT|wxBOTTOM, 5 );

    my( $item6 ) = Wx::TextCtrl->new( $_[0], $main::EDT_LOGIN, "", wxDefaultPosition, [80,-1], 0 );
    $item6->SetName( "edtLogin" );
    $item4->AddWindow( $item6, 0, wxALIGN_CENTER|wxALL, 0 );

    $item3->Add( $item4, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item7 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item8 ) = Wx::StaticText->new( $_[0], $main::LAB_SENHA, "Senha:", wxDefaultPosition, wxDefaultSize, 0 );
    $item8->SetName( "labSenha" );
    $item7->AddWindow( $item8, 0, wxALIGN_CENTER_VERTICAL|wxRIGHT|wxBOTTOM, 5 );

    my( $item9 ) = Wx::TextCtrl->new( $_[0], $main::EDT_SENHA, "", wxDefaultPosition, [80,-1], wxTE_PASSWORD );
    $item9->SetName( "edtSenha" );
    $item7->AddWindow( $item9, 0, wxALIGN_CENTER|wxALL, 0 );

    $item3->Add( $item7, 0, wxALIGN_CENTER|wxALL, 5 );

    $item1->Add( $item3, 0, wxALIGN_CENTER|wxALL, 0 );

    $item0->Add( $item1, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item10 ) = Wx::BoxSizer->new( wxHORIZONTAL );
    
    my( $item11 ) = Wx::Button->new( $_[0], $main::BTN_LOGIN, "Login", wxDefaultPosition, wxDefaultSize, 0 );
    $item11->SetDefault();
    $item11->SetName( "btnLogin" );
    $item10->AddWindow( $item11, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item12 ) = Wx::Button->new( $_[0], $main::BTN_CANCELAR, "Cancelar", wxDefaultPosition, wxDefaultSize, 0 );
    $item12->SetName( "btnCancelar" );
    $item10->AddWindow( $item12, 0, wxALIGN_CENTER|wxALL, 5 );

    $item0->Add( $item10, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $set_size ) = @_ >= 3 ? $_[2] : 1;
    my( $call_fit ) = @_ >= 2 ? $_[1] : 1;
    if( $set_size == 1 ) {
         $_[0]->SetAutoLayout( 1 );
         $_[0]->SetSizer( $item0 );
         
         if( $call_fit == 1 ) {
             $item0->Fit( $_[0] );
             $item0->SetSizeHints( $_[0] );
         }
    }
    
    $item0;
}

use vars qw($ID_TEXT); $ID_TEXT = 10021;
use vars qw($BTN_OK); $BTN_OK = 10022;

sub frmSobre {
    my( $item0 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item2 ) = Wx::StaticBox->new( $_[0], -1, "" );
    my( $item1 ) = Wx::StaticBoxSizer->new( $item2, wxVERTICAL );
    
    my( $item3 ) = Wx::StaticBitmap->new( $_[0], $main::ID_STATICBITMAP, ListaBitmaps( 6 ), wxDefaultPosition, wxDefaultSize );
    $item1->AddWindow( $item3, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item4 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Versão: 1.0.0", wxDefaultPosition, wxDefaultSize, 0 );
    $item1->AddWindow( $item4, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item5 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Todos os direitos reservados para: Henrique F. de Souza", wxDefaultPosition, wxDefaultSize, 0 );
    $item1->AddWindow( $item5, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item6 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Sistema integrante do projeto Livrus Virtus,", wxDefaultPosition, wxDefaultSize, 0 );
    $item1->AddWindow( $item6, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item7 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "versão programado no wxDesigner.", wxDefaultPosition, wxDefaultSize, 0 );
    $item1->AddWindow( $item7, 0, wxALIGN_CENTER|wxALL, 5 );

    $item0->Add( $item1, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item8 ) = Wx::Button->new( $_[0], $main::BTN_OK, "OK", wxDefaultPosition, wxDefaultSize, 0 );
    $item8->SetName( "btnOk" );
    $item0->AddWindow( $item8, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $set_size ) = @_ >= 3 ? $_[2] : 1;
    my( $call_fit ) = @_ >= 2 ? $_[1] : 1;
    if( $set_size == 1 ) {
         $_[0]->SetAutoLayout( 1 );
         $_[0]->SetSizer( $item0 );
         
         if( $call_fit == 1 ) {
             $item0->Fit( $_[0] );
             $item0->SetSizeHints( $_[0] );
         }
    }
    
    $item0;
}

use vars qw($EDT_SENHAATUAL); $EDT_SENHAATUAL = 10023;
use vars qw($EDT_NOVASENHA); $EDT_NOVASENHA = 10024;
use vars qw($EDT_CONFIRMSENHA); $EDT_CONFIRMSENHA = 10025;

sub frmAlterarSenha {
    my( $item0 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item1 ) = Wx::GridSizer->new( 0, 2, 0, 0 );
    
    my( $item2 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item3 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Login:", wxDefaultPosition, wxDefaultSize, 0 );
    $item2->AddWindow( $item3, 0, wxALIGN_CENTER_VERTICAL|wxRIGHT|wxBOTTOM, 5 );

    my( $item4 ) = Wx::TextCtrl->new( $_[0], $main::EDT_LOGIN, "", wxDefaultPosition, [100,-1], 0 );
    $item4->SetName( "edtLogin" );
    $item2->AddWindow( $item4, 0, wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    $item1->Add( $item2, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item5 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item6 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Senha atual:", wxDefaultPosition, wxDefaultSize, 0 );
    $item5->AddWindow( $item6, 0, wxALIGN_CENTER_VERTICAL|wxRIGHT|wxBOTTOM, 5 );

    my( $item7 ) = Wx::TextCtrl->new( $_[0], $main::EDT_SENHAATUAL, "", wxDefaultPosition, [100,-1], 0 );
    $item7->SetName( "edtSenhaAtual" );
    $item5->AddWindow( $item7, 0, wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    $item1->Add( $item5, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item8 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item9 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Nova senha:", wxDefaultPosition, wxDefaultSize, 0 );
    $item8->AddWindow( $item9, 0, wxALIGN_CENTER_VERTICAL|wxRIGHT|wxBOTTOM, 5 );

    my( $item10 ) = Wx::TextCtrl->new( $_[0], $main::EDT_NOVASENHA, "", wxDefaultPosition, [100,-1], 0 );
    $item10->SetName( "edtNovaSenha" );
    $item8->AddWindow( $item10, 0, wxALIGN_CENTER|wxALL, 0 );

    $item1->Add( $item8, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item11 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item12 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Confirmar senha:", wxDefaultPosition, wxDefaultSize, 0 );
    $item11->AddWindow( $item12, 0, wxALIGN_CENTER_VERTICAL|wxRIGHT|wxBOTTOM, 5 );

    my( $item13 ) = Wx::TextCtrl->new( $_[0], $main::EDT_CONFIRMSENHA, "", wxDefaultPosition, [100,-1], 0 );
    $item13->SetName( "edtConfirmarSenha" );
    $item11->AddWindow( $item13, 0, wxALIGN_CENTER_VERTICAL, 5 );

    $item1->Add( $item11, 0, wxALIGN_CENTER|wxALL, 5 );

    $item0->Add( $item1, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item14 ) = Wx::BoxSizer->new( wxHORIZONTAL );
    
    my( $item15 ) = Wx::Button->new( $_[0], $main::BTN_SALVAR, "Salvar", wxDefaultPosition, wxDefaultSize, 0 );
    $item15->SetName( "btnSalvar" );
    $item14->AddWindow( $item15, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item16 ) = Wx::Button->new( $_[0], $main::BTN_LIMPAR, "Limpar", wxDefaultPosition, wxDefaultSize, 0 );
    $item16->SetName( "btnLimpar" );
    $item14->AddWindow( $item16, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item17 ) = Wx::Button->new( $_[0], $main::BTN_FECHAR, "Fechar", wxDefaultPosition, wxDefaultSize, 0 );
    $item17->SetName( "btnFechar" );
    $item14->AddWindow( $item17, 0, wxALIGN_CENTER|wxALL, 5 );

    $item0->Add( $item14, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $set_size ) = @_ >= 3 ? $_[2] : 1;
    my( $call_fit ) = @_ >= 2 ? $_[1] : 1;
    if( $set_size == 1 ) {
         $_[0]->SetAutoLayout( 1 );
         $_[0]->SetSizer( $item0 );
         
         if( $call_fit == 1 ) {
             $item0->Fit( $_[0] );
             $item0->SetSizeHints( $_[0] );
         }
    }
    
    $item0;
}

# Menu bar functions

use vars qw($MNU_CADASTROS); $MNU_CADASTROS = 10;
use vars qw($MNU_CADASSUNTOS); $MNU_CADASSUNTOS = 11;
use vars qw($MNU_CADAUTORES); $MNU_CADAUTORES = 12;
use vars qw($MNU_CADENDERECOS); $MNU_CADENDERECOS = 13;
use vars qw($MNU_CADIDIOMAS); $MNU_CADIDIOMAS = 14;
use vars qw($MNU_CADPAISES); $MNU_CADPAISES = 15;
use vars qw($MNU_CADPROFISSOES); $MNU_CADPROFISSOES = 16;
use vars qw($ID_MENU); $ID_MENU = 10026;
use vars qw($MNU_CADCLIENTES); $MNU_CADCLIENTES = 17;
use vars qw($MNU_CADLIVROS); $MNU_CADLIVROS = 18;
use vars qw($MNU_PESQUISAS); $MNU_PESQUISAS = 20;
use vars qw($MNU_CONASSUNTOS); $MNU_CONASSUNTOS = 21;
use vars qw($MNU_CONAUTORES); $MNU_CONAUTORES = 22;
use vars qw($MNU_CONENDERECOS); $MNU_CONENDERECOS = 23;
use vars qw($MNU_CONIDIOMAS); $MNU_CONIDIOMAS = 24;
use vars qw($MNU_CONPAISES); $MNU_CONPAISES = 25;
use vars qw($MNU_CONPROFISSOES); $MNU_CONPROFISSOES = 26;
use vars qw($MNU_CONCLIENTES); $MNU_CONCLIENTES = 27;
use vars qw($MNU_CONLIVROS); $MNU_CONLIVROS = 28;
use vars qw($MNU_VENDAS); $MNU_VENDAS = 30;
use vars qw($MNU_VENDER); $MNU_VENDER = 31;
use vars qw($MNU_VENDASREALIZADAS); $MNU_VENDASREALIZADAS = 32;
use vars qw($MNU_JANELAS); $MNU_JANELAS = 40;
use vars qw($MNU_LADOALADOHORIZONTAL); $MNU_LADOALADOHORIZONTAL = 41;
use vars qw($MNU_LADOALADOVERTICAL); $MNU_LADOALADOVERTICAL = 42;
use vars qw($MNU_EMCASCATA); $MNU_EMCASCATA = 43;
use vars qw($MNU_ORGANIZARICONES); $MNU_ORGANIZARICONES = 44;
use vars qw($MNU_OPCOES); $MNU_OPCOES = 50;
use vars qw($MNU_ALTERARSENHA); $MNU_ALTERARSENHA = 51;
use vars qw($MNU_SOBRE); $MNU_SOBRE = 52;
use vars qw($MNU_SAIR); $MNU_SAIR = 53;

sub MontaBarraDeMenu {
    my( $item0 ) = Wx::MenuBar->new();
    
    my( $item1 ) = Wx::Menu->new();
    $item1->Append( $main::MNU_CADASSUNTOS, "Assuntos", "" );
    $item1->Append( $main::MNU_CADAUTORES, "Autores", "" );
    $item1->Append( $main::MNU_CADENDERECOS, "Endereços", "" );
    $item1->Append( $main::MNU_CADIDIOMAS, "Idiomas", "" );
    $item1->Append( $main::MNU_CADPAISES, "Países", "" );
    $item1->Append( $main::MNU_CADPROFISSOES, "Profissões", "" );
    $item1->AppendSeparator();
    $item1->Append( $main::MNU_CADCLIENTES, "Clientes", "" );
    $item1->Append( $main::MNU_CADLIVROS, "Livros", "" );
    $item0->Append( $item1, "Cadastros" );
    
    my( $item2 ) = Wx::Menu->new();
    $item2->Append( $main::MNU_CONASSUNTOS, "Assuntos", "" );
    $item2->Append( $main::MNU_CONAUTORES, "Autores", "" );
    $item2->Append( $main::MNU_CONENDERECOS, "Endereços", "" );
    $item2->Append( $main::MNU_CONIDIOMAS, "Idiomas", "" );
    $item2->Append( $main::MNU_CONPAISES, "Países", "" );
    $item2->Append( $main::MNU_CONPROFISSOES, "Profissões", "" );
    $item2->AppendSeparator();
    $item2->Append( $main::MNU_CONCLIENTES, "Clientes", "" );
    $item2->Append( $main::MNU_CONLIVROS, "Livros", "" );
    $item0->Append( $item2, "Pesquisas" );
    
    my( $item3 ) = Wx::Menu->new();
    $item3->Append( $main::MNU_VENDER, "Vender", "" );
    $item3->Append( $main::MNU_VENDASREALIZADAS, "Vendas Realizadas", "" );
    $item0->Append( $item3, "Vendas" );
    
    my( $item4 ) = Wx::Menu->new();
    $item4->Append( $main::MNU_LADOALADOHORIZONTAL, "Lado a lado horizontal", "" );
    $item4->Append( $main::MNU_LADOALADOVERTICAL, "Lado a lado vertical", "" );
    $item4->Append( $main::MNU_EMCASCATA, "Em cascata", "" );
    $item4->Append( $main::MNU_ORGANIZARICONES, "Organizar Ícones", "" );
    $item0->Append( $item4, "Janelas" );
    
    my( $item5 ) = Wx::Menu->new();
    $item5->Append( $main::MNU_ALTERARSENHA, "Alterar Senha", "" );
    $item5->AppendSeparator();
    $item5->Append( $main::MNU_SOBRE, "Sobre", "" );
    $item5->Append( $main::MNU_SAIR, "Sair", "" );
    $item0->Append( $item5, "Opções" );
    
    $item0;
}

# Bitmap functions

use Wx qw( wxNullBitmap wxBITMAP_TYPE_PNG );

use vars qw($BMP_CLIENTE); $BMP_CLIENTE = 0;
use vars qw($BMP_LIVRO); $BMP_LIVRO = 1;
use vars qw($BMP_LIVROS); $BMP_LIVROS = 2;
use vars qw($BMP_SOBRE); $BMP_SOBRE = 3;
use vars qw($BMP_SAIR); $BMP_SAIR = 4;
use vars qw($BMP_LOGIN); $BMP_LOGIN = 5;
use vars qw($BMP_SPLASH); $BMP_SPLASH = 6;
use vars qw($BMP_LIVRUSVIRTUS); $BMP_LIVRUSVIRTUS = 7;

sub ListaBitmaps {
    if (($_[0] == 0) ||
        ($_[0] == BMP_CLIENTE)) {
        my( $bitmap ) = Wx::Bitmap->new( "Livrus_wdr/ListaBitmaps_0.png", wxBITMAP_TYPE_PNG );
        return $bitmap;
    }
    if (($_[0] == 1) ||
        ($_[0] == BMP_LIVRO)) {
        my( $bitmap ) = Wx::Bitmap->new( "Livrus_wdr/ListaBitmaps_1.png", wxBITMAP_TYPE_PNG );
        return $bitmap;
    }
    if (($_[0] == 2) ||
        ($_[0] == BMP_LIVROS)) {
        my( $bitmap ) = Wx::Bitmap->new( "Livrus_wdr/ListaBitmaps_2.png", wxBITMAP_TYPE_PNG );
        return $bitmap;
    }
    if (($_[0] == 3) ||
        ($_[0] == BMP_SOBRE)) {
        my( $bitmap ) = Wx::Bitmap->new( "Livrus_wdr/ListaBitmaps_3.png", wxBITMAP_TYPE_PNG );
        return $bitmap;
    }
    if (($_[0] == 4) ||
        ($_[0] == BMP_SAIR)) {
        my( $bitmap ) = Wx::Bitmap->new( "Livrus_wdr/ListaBitmaps_4.png", wxBITMAP_TYPE_PNG );
        return $bitmap;
    }
    if (($_[0] == 5) ||
        ($_[0] == BMP_LOGIN)) {
        my( $bitmap ) = Wx::Bitmap->new( "Livrus_wdr/ListaBitmaps_5.png", wxBITMAP_TYPE_PNG );
        return $bitmap;
    }
    if (($_[0] == 6) ||
        ($_[0] == BMP_SPLASH)) {
        my( $bitmap ) = Wx::Bitmap->new( "Livrus_wdr/ListaBitmaps_6.png", wxBITMAP_TYPE_PNG );
        return $bitmap;
    }
    if (($_[0] == 7) ||
        ($_[0] == BMP_LIVRUSVIRTUS)) {
        my( $bitmap ) = Wx::Bitmap->new( "Livrus_wdr/ListaBitmaps_7.png", wxBITMAP_TYPE_PNG );
        return $bitmap;
    }
    wxNullBitmap;
}

# Toolbar functions

use vars qw($TLB_CLIENTE); $TLB_CLIENTE = 0;
use vars qw($TLB_LIVRO); $TLB_LIVRO = 1;
use vars qw($TLB_VENDAS); $TLB_VENDAS = 2;
use vars qw($TLB_SOBRE); $TLB_SOBRE = 3;
use vars qw($TLB_SAIR); $TLB_SAIR = 4;

sub MontaBarraDeFerramentas {
    $_[0]->SetMargins( 2, 2 );
    
    $_[0]->AddTool( $main::TLB_CLIENTE, ListaBitmaps( 0 ), wxNullBitmap, 0, undef, "" );
    $_[0]->AddTool( $main::TLB_LIVRO, ListaBitmaps( 1 ), wxNullBitmap, 0, undef, "" );
    $_[0]->AddTool( $main::TLB_VENDAS, ListaBitmaps( 2 ), wxNullBitmap, 0, undef, "" );
    $_[0]->AddSeparator();
    $_[0]->AddTool( $main::TLB_SOBRE, ListaBitmaps( 3 ), wxNullBitmap, 0, undef, "" );
    $_[0]->AddTool( $main::TLB_SAIR, ListaBitmaps( 4 ), wxNullBitmap, 0, undef, "" );
    
    $_[0]->Realize();
}


# End of generated file
