set PATH=C:\COMPS\ADA\GNAT310\bin;%path%
set PATH=C:\COMPS\ADA\GNAT310\gw-gnat;%path%
set TMPDIR=C:\COMPS\ADA\GNAT310\tmp
set DJGPP=C:\COMPS\ADA\GNAT310\djgpp.env
set ADA_INCLUDE_PATH=C:\COMPS\ADA\GNAT310\adainc
set ADA_OBJECTS_PATH=C:\COMPS\ADA\GNAT310\lib\adalib
set GW-GNAT=C:\COMPS\ADA\GNAT310\gw-gnat
