// generated 2005/1/16 14:23:02 BRST by hfs@localhost.(none)
// using glademm V1.1.2
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/hfs/KDevelop/glade1/plivrus2/livrus.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./src/frmPrincipal.hh and./src/frmPrincipal.cc

#ifndef _FRMPRINCIPAL_GLADE_HH
#  define _FRMPRINCIPAL_GLADE_HH

#include <gtk--/window.h>

class frmPrincipal_glade : public Gtk::Window
{  
protected:
        
        
        frmPrincipal_glade();
        
        ~frmPrincipal_glade();
private:
        virtual void on_mnuCadAssuntos_activate() = 0;
        virtual void on_mnuCadastros_activate() = 0;
};
#endif
