# generated 2005/1/16 14:23:02 BRST by hfs@localhost.(none)
# using glademm V1.1.2
#
# newer (non customized) versions of this file go to Makefile.am_new
bin_PROGRAMS = livrus

livrus_SOURCES = \
	livrus.cc\
	frmPrincipal_glade.cc \
	frmPrincipal.cc 

noinst_HEADERS = \
	frmPrincipal_glade.hh \
	frmPrincipal.hh 

CXXFLAGS = @CXXFLAGS@ @GTKMM_CFLAGS@

livrus_LDADD = @LIBS@ @GTKMM_LIBS@
