//-----------------------------------------------------------------------------
// C# source generated by wxDesigner from file: Livrus.wdr
// Do not modify this file, all changes will be lost!
//-----------------------------------------------------------------------------

using System;
using System.Drawing;
using wx;

public class LivrusWdrClass
{
   // Window functions

    public const int LAB_CODIGO = 10000;
    public const int EDT_CODIGO = 10001;
    public const int LAB_DESCRICAO = 10002;
    public const int EDT_DESCRICAO = 10003;
    public const int BTN_PESQUISAR = 10004;
    public const int BTN_ANTERIOR = 10005;
    public const int BTN_PROXIMO = 10006;
    public const int BTN_SALVAR = 10007;
    public const int BTN_EXCLUIR = 10008;
    public const int BTN_LIMPAR = 10009;
    public const int BTN_FECHAR = 10010;

    public static Sizer frmCadAssuntos( Window parent )
    { return frmCadAssuntos( parent, true, true ); }

    public static Sizer frmCadAssuntos( Window parent, bool call_fit )
    { return frmCadAssuntos( parent, call_fit, true ); }

    public static Sizer frmCadAssuntos( Window parent, bool call_fit, bool set_sizer )
    {
        BoxSizer item0 = new BoxSizer( Orientation.wxVERTICAL );
    
        FlexGridSizer item1 = new FlexGridSizer( 0, 2, 0, 0 );
        item1.AddGrowableCol( 0 );
    
        FlexGridSizer item2 = new FlexGridSizer( 0, 1, 0, 0 );
        item2.AddGrowableRow( 0 );
        item2.AddGrowableRow( 1 );
    
        BoxSizer item3 = new BoxSizer( Orientation.wxVERTICAL );
    
        StaticText item4 = new StaticText( parent, LAB_CODIGO, "Código:", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item4.Name = "labCodigo";
        item3.Add( item4, 5, Alignment.wxALIGN_CENTER_VERTICAL, 0 );

        TextCtrl item5 = new TextCtrl( parent, EDT_CODIGO, "", Window.wxDefaultPosition, new Size(80,-1), 0 );
        item5.Name = "edtCodigo";
        item3.Add( item5, 0, Alignment.wxALIGN_CENTER, 0 );

        item2.Add( item3, 0, Alignment.wxALIGN_CENTER_VERTICAL, 0 );

        BoxSizer item6 = new BoxSizer( Orientation.wxVERTICAL );
    
        StaticText item7 = new StaticText( parent, LAB_DESCRICAO, "Assunto:", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item7.Name = "labDescricao";
        item6.Add( item7, 5, Alignment.wxALIGN_CENTER_VERTICAL, 0 );

        TextCtrl item8 = new TextCtrl( parent, EDT_DESCRICAO, "", Window.wxDefaultPosition, new Size(200,-1), 0 );
        item8.Name = "edtDescricao";
        item6.Add( item8, 0, Alignment.wxALIGN_CENTER, 0 );

        item2.Add( item6, 0, Alignment.wxALIGN_CENTER, 0 );

        item1.Add( item2, 0, Alignment.wxALIGN_CENTER_HORIZONTAL|Direction.wxALL, 5 );

        BoxSizer item9 = new BoxSizer( Orientation.wxVERTICAL );
    
        Button item10 = new Button( parent, BTN_PESQUISAR, "Pesquisar", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item10.SetDefault();
        item10.Name = "btnPesquisar";
        item9.Add( item10, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 0 );

        Button item11 = new Button( parent, BTN_ANTERIOR, "Anterior", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item11.Name = "btnAnterior";
        item11.Enabled = false;
        item9.Add( item11, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        Button item12 = new Button( parent, BTN_PROXIMO, "Próximo", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item12.Name = "btnProximo";
        item12.Enabled = false;
        item9.Add( item12, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 0 );

        item1.Add( item9, 0, Alignment.wxALIGN_CENTER_HORIZONTAL|Direction.wxALL, 5 );

        item0.Add( item1, 0, Stretch.wxGROW|Alignment.wxALIGN_CENTER_VERTICAL, 0 );

        BoxSizer item13 = new BoxSizer( Orientation.wxHORIZONTAL );
    
        Button item14 = new Button( parent, BTN_SALVAR, "Salvar", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item14.Name = "btnSalvar";
        item14.Enabled = false;
        item13.Add( item14, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        Button item15 = new Button( parent, BTN_EXCLUIR, "Excluir", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item15.Name = "btnExcluir";
        item15.Enabled = false;
        item13.Add( item15, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        Button item16 = new Button( parent, BTN_LIMPAR, "Limpar", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item16.Name = "btnLimpar";
        item13.Add( item16, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        Button item17 = new Button( parent, BTN_FECHAR, "Fechar", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item17.Name = "btnFechar";
        item13.Add( item17, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        item0.Add( item13, 0, Alignment.wxALIGN_RIGHT|Alignment.wxALIGN_CENTER_VERTICAL|Direction.wxALL, 5 );

        if (set_sizer)
        {
            // parent.SetAutoLayout( true );
            parent.SetSizer( item0 );
            if (call_fit)
            {
                item0.Fit( parent );
                item0.SetSizeHints( parent );
            }
        }
        
        return item0;
    }


    public static Sizer frmCadAutores( Window parent )
    { return frmCadAutores( parent, true, true ); }

    public static Sizer frmCadAutores( Window parent, bool call_fit )
    { return frmCadAutores( parent, call_fit, true ); }

    public static Sizer frmCadAutores( Window parent, bool call_fit, bool set_sizer )
    {
        BoxSizer item0 = new BoxSizer( Orientation.wxVERTICAL );
    
        FlexGridSizer item1 = new FlexGridSizer( 0, 2, 0, 0 );
        item1.AddGrowableCol( 0 );
    
        FlexGridSizer item2 = new FlexGridSizer( 0, 1, 0, 0 );
        item2.AddGrowableRow( 0 );
        item2.AddGrowableRow( 1 );
    
        BoxSizer item3 = new BoxSizer( Orientation.wxVERTICAL );
    
        StaticText item4 = new StaticText( parent, LAB_CODIGO, "Código:", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item4.Name = "labCodigo";
        item3.Add( item4, 5, Alignment.wxALIGN_CENTER_VERTICAL, 5 );

        TextCtrl item5 = new TextCtrl( parent, EDT_CODIGO, "", Window.wxDefaultPosition, new Size(80,-1), 0 );
        item5.Name = "edtCodigo";
        item3.Add( item5, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 0 );

        item2.Add( item3, 0, Alignment.wxALIGN_CENTER_VERTICAL, 0 );

        BoxSizer item6 = new BoxSizer( Orientation.wxVERTICAL );
    
        StaticText item7 = new StaticText( parent, LAB_DESCRICAO, "Autor:", Window.wxDefaultPosition, new Size(100,-1), 0 );
        item7.Name = "labDescricao";
        item6.Add( item7, 5, Alignment.wxALIGN_CENTER_VERTICAL, 5 );

        TextCtrl item8 = new TextCtrl( parent, EDT_DESCRICAO, "", Window.wxDefaultPosition, new Size(200,-1), 0 );
        item8.Name = "edtDescricao";
        item6.Add( item8, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 0 );

        item2.Add( item6, 0, Alignment.wxALIGN_CENTER, 0 );

        item1.Add( item2, 0, Alignment.wxALIGN_CENTER_HORIZONTAL|Direction.wxALL, 5 );

        BoxSizer item9 = new BoxSizer( Orientation.wxVERTICAL );
    
        Button item10 = new Button( parent, BTN_PESQUISAR, "Pesquisar", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item10.SetDefault();
        item10.Name = "btnPesquisar";
        item9.Add( item10, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 0 );

        Button item11 = new Button( parent, BTN_ANTERIOR, "Anterior", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item11.Name = "btnAnterior";
        item11.Enabled = false;
        item9.Add( item11, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        Button item12 = new Button( parent, BTN_PROXIMO, "Próximo", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item12.Name = "btnProximo";
        item12.Enabled = false;
        item9.Add( item12, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 0 );

        item1.Add( item9, 0, Alignment.wxALIGN_CENTER_HORIZONTAL|Direction.wxALL, 5 );

        item0.Add( item1, 0, Stretch.wxGROW|Alignment.wxALIGN_CENTER_VERTICAL, 0 );

        BoxSizer item13 = new BoxSizer( Orientation.wxHORIZONTAL );
    
        Button item14 = new Button( parent, BTN_SALVAR, "Salvar", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item14.Name = "btnSalvar";
        item14.Enabled = false;
        item13.Add( item14, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        Button item15 = new Button( parent, BTN_EXCLUIR, "Excluir", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item15.Name = "btnExcluir";
        item15.Enabled = false;
        item13.Add( item15, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        Button item16 = new Button( parent, BTN_LIMPAR, "Limpar", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item16.Name = "btnLimpar";
        item13.Add( item16, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        Button item17 = new Button( parent, BTN_FECHAR, "Fechar", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item17.Name = "btnFechar";
        item13.Add( item17, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        item0.Add( item13, 0, Alignment.wxALIGN_RIGHT|Alignment.wxALIGN_CENTER_VERTICAL|Direction.wxALL, 5 );

        if (set_sizer)
        {
            // parent.SetAutoLayout( true );
            parent.SetSizer( item0 );
            if (call_fit)
            {
                item0.Fit( parent );
                item0.SetSizeHints( parent );
            }
        }
        
        return item0;
    }

    public const int GRID_CONSULTA = 10011;
    public const int LAB_REGISTROS = 10012;
    public const int LAB_LIMPAR = 10013;

    public static Sizer frmConAssuntos( Window parent )
    { return frmConAssuntos( parent, true, true ); }

    public static Sizer frmConAssuntos( Window parent, bool call_fit )
    { return frmConAssuntos( parent, call_fit, true ); }

    public static Sizer frmConAssuntos( Window parent, bool call_fit, bool set_sizer )
    {
        FlexGridSizer item0 = new FlexGridSizer( 0, 1, 0, 0 );
        item0.AddGrowableRow( 1 );
    
        BoxSizer item1 = new BoxSizer( Orientation.wxHORIZONTAL );
    
        BoxSizer item2 = new BoxSizer( Orientation.wxVERTICAL );
    
        StaticText item3 = new StaticText( parent, LAB_DESCRICAO, "Assunto:", Window.wxDefaultPosition, new Size(40,-1), 0 );
        item3.Name = "labDescricao";
        item2.Add( item3, 5, Alignment.wxALIGN_CENTER_VERTICAL, 5 );

        TextCtrl item4 = new TextCtrl( parent, EDT_DESCRICAO, "", Window.wxDefaultPosition, new Size(250,-1), 0 );
        item4.Name = "edtDescricao";
        item2.Add( item4, 0, Alignment.wxALIGN_CENTER_VERTICAL|Direction.wxALL, 0 );

        item1.Add( item2, 0, Alignment.wxALIGN_CENTER_HORIZONTAL|Direction.wxALL, 5 );

        Button item5 = new Button( parent, BTN_PESQUISAR, "Pesquisar", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item5.Name = "btnPesquisar";
        item1.Add( item5, 0, Alignment.wxALIGN_BOTTOM|Alignment.wxALIGN_CENTER_HORIZONTAL|Direction.wxALL, 5 );

        item0.Add( item1, 0, Alignment.wxALIGN_CENTER_VERTICAL|Direction.wxALL, 5 );

        item6.Name = "gridConsulta";
        item0.Add( item6, 0, Stretch.wxGROW, 0 );

        FlexGridSizer item7 = new FlexGridSizer( 0, 2, 0, 0 );
        item7.AddGrowableCol( 0 );
    
        BoxSizer item8 = new BoxSizer( Orientation.wxHORIZONTAL );
    
        StaticText item9 = new StaticText( parent, LAB_REGISTROS, "Registro: 0 de 0", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item9.Name = "labRegistros";
        item8.Add( item9, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        item7.Add( item8, 0, Alignment.wxALIGN_BOTTOM|Direction.wxALL, 5 );

        BoxSizer item10 = new BoxSizer( Orientation.wxHORIZONTAL );
    
        Button item11 = new Button( parent, LAB_LIMPAR, "Limpar", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item11.Name = "btnLimpar";
        item10.Add( item11, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        Button item12 = new Button( parent, BTN_FECHAR, "Fechar", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item12.Name = "btnFechar";
        item10.Add( item12, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        item7.Add( item10, 0, Stretch.wxGROW|Alignment.wxALIGN_BOTTOM|Direction.wxALL, 5 );

        item0.Add( item7, 0, Stretch.wxGROW|Alignment.wxALIGN_CENTER_VERTICAL|Direction.wxALL, 5 );

        if (set_sizer)
        {
            // parent.SetAutoLayout( true );
            parent.SetSizer( item0 );
            if (call_fit)
            {
                item0.Fit( parent );
                item0.SetSizeHints( parent );
            }
        }
        
        return item0;
    }

    public const int ID_STATICBITMAP = 10014;

    public static Sizer frmSplash( Window parent )
    { return frmSplash( parent, true, true ); }

    public static Sizer frmSplash( Window parent, bool call_fit )
    { return frmSplash( parent, call_fit, true ); }

    public static Sizer frmSplash( Window parent, bool call_fit, bool set_sizer )
    {
        BoxSizer item0 = new BoxSizer( Orientation.wxVERTICAL );
    
        StaticBitmap item1 = new StaticBitmap( parent, ID_STATICBITMAP, ListaBitmaps( 6 ), Window.wxDefaultPosition, Window.wxDefaultSize );
        item0.Add( item1, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        if (set_sizer)
        {
            // parent.SetAutoLayout( true );
            parent.SetSizer( item0 );
            if (call_fit)
            {
                item0.Fit( parent );
                item0.SetSizeHints( parent );
            }
        }
        
        return item0;
    }

    public const int LAB_LOGIN = 10015;
    public const int EDT_LOGIN = 10016;
    public const int LAB_SENHA = 10017;
    public const int EDT_SENHA = 10018;
    public const int BTN_LOGIN = 10019;
    public const int BTN_CANCELAR = 10020;

    public static Sizer frmLogin( Window parent )
    { return frmLogin( parent, true, true ); }

    public static Sizer frmLogin( Window parent, bool call_fit )
    { return frmLogin( parent, call_fit, true ); }

    public static Sizer frmLogin( Window parent, bool call_fit, bool set_sizer )
    {
        BoxSizer item0 = new BoxSizer( Orientation.wxVERTICAL );
    
        BoxSizer item1 = new BoxSizer( Orientation.wxHORIZONTAL );
    
        StaticBitmap item2 = new StaticBitmap( parent, ID_STATICBITMAP, ListaBitmaps( 5 ), Window.wxDefaultPosition, Window.wxDefaultSize );
        item1.Add( item2, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 0 );

        BoxSizer item3 = new BoxSizer( Orientation.wxVERTICAL );
    
        BoxSizer item4 = new BoxSizer( Orientation.wxVERTICAL );
    
        StaticText item5 = new StaticText( parent, LAB_LOGIN, "Login:", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item5.Name = "labLogin";
        item4.Add( item5, 0, Alignment.wxALIGN_CENTER_VERTICAL|Direction.wxRIGHT|Direction.wxBOTTOM, 5 );

        TextCtrl item6 = new TextCtrl( parent, EDT_LOGIN, "", Window.wxDefaultPosition, new Size(80,-1), 0 );
        item6.Name = "edtLogin";
        item4.Add( item6, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 0 );

        item3.Add( item4, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        BoxSizer item7 = new BoxSizer( Orientation.wxVERTICAL );
    
        StaticText item8 = new StaticText( parent, LAB_SENHA, "Senha:", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item8.Name = "labSenha";
        item7.Add( item8, 0, Alignment.wxALIGN_CENTER_VERTICAL|Direction.wxRIGHT|Direction.wxBOTTOM, 5 );

        TextCtrl item9 = new TextCtrl( parent, EDT_SENHA, "", Window.wxDefaultPosition, new Size(80,-1), TextCtrl.wxTE_PASSWORD );
        item9.Name = "edtSenha";
        item7.Add( item9, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 0 );

        item3.Add( item7, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        item1.Add( item3, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 0 );

        item0.Add( item1, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        BoxSizer item10 = new BoxSizer( Orientation.wxHORIZONTAL );
    
        Button item11 = new Button( parent, BTN_LOGIN, "Login", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item11.SetDefault();
        item11.Name = "btnLogin";
        item10.Add( item11, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        Button item12 = new Button( parent, BTN_CANCELAR, "Cancelar", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item12.Name = "btnCancelar";
        item10.Add( item12, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        item0.Add( item10, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        if (set_sizer)
        {
            // parent.SetAutoLayout( true );
            parent.SetSizer( item0 );
            if (call_fit)
            {
                item0.Fit( parent );
                item0.SetSizeHints( parent );
            }
        }
        
        return item0;
    }

    public const int ID_TEXT = 10021;
    public const int BTN_OK = 10022;

    public static Sizer frmSobre( Window parent )
    { return frmSobre( parent, true, true ); }

    public static Sizer frmSobre( Window parent, bool call_fit )
    { return frmSobre( parent, call_fit, true ); }

    public static Sizer frmSobre( Window parent, bool call_fit, bool set_sizer )
    {
        BoxSizer item0 = new BoxSizer( Orientation.wxVERTICAL );
    
        StaticBox item2 = new StaticBox( parent, -1, "" );
        StaticBoxSizer item1 = new StaticBoxSizer( item2, Orientation.wxVERTICAL );
    
        StaticBitmap item3 = new StaticBitmap( parent, ID_STATICBITMAP, ListaBitmaps( 6 ), Window.wxDefaultPosition, Window.wxDefaultSize );
        item1.Add( item3, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        StaticText item4 = new StaticText( parent, ID_TEXT, "Versão: 1.0.0", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item1.Add( item4, 0, Alignment.wxALIGN_RIGHT|Alignment.wxALIGN_CENTER_VERTICAL|Direction.wxALL, 5 );

        StaticText item5 = new StaticText( parent, ID_TEXT, "Todos os direitos reservados para: Henrique F. de Souza", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item1.Add( item5, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        StaticText item6 = new StaticText( parent, ID_TEXT, "Sistema integrante do projeto Livrus Virtus,", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item1.Add( item6, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        StaticText item7 = new StaticText( parent, ID_TEXT, "versão programado no wxDesigner.", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item1.Add( item7, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        item0.Add( item1, 0, Stretch.wxGROW|Alignment.wxALIGN_CENTER_VERTICAL|Direction.wxALL, 5 );

        Button item8 = new Button( parent, BTN_OK, "OK", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item8.Name = "btnOk";
        item0.Add( item8, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        if (set_sizer)
        {
            // parent.SetAutoLayout( true );
            parent.SetSizer( item0 );
            if (call_fit)
            {
                item0.Fit( parent );
                item0.SetSizeHints( parent );
            }
        }
        
        return item0;
    }

    public const int EDT_SENHAATUAL = 10023;
    public const int EDT_NOVASENHA = 10024;
    public const int EDT_CONFIRMSENHA = 10025;

    public static Sizer frmAlterarSenha( Window parent )
    { return frmAlterarSenha( parent, true, true ); }

    public static Sizer frmAlterarSenha( Window parent, bool call_fit )
    { return frmAlterarSenha( parent, call_fit, true ); }

    public static Sizer frmAlterarSenha( Window parent, bool call_fit, bool set_sizer )
    {
        BoxSizer item0 = new BoxSizer( Orientation.wxVERTICAL );
    
        GridSizer item1 = new GridSizer( 0, 2, 0, 0 );
    
        BoxSizer item2 = new BoxSizer( Orientation.wxVERTICAL );
    
        StaticText item3 = new StaticText( parent, ID_TEXT, "Login:", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item2.Add( item3, 0, Alignment.wxALIGN_CENTER_VERTICAL|Direction.wxRIGHT|Direction.wxBOTTOM, 5 );

        TextCtrl item4 = new TextCtrl( parent, EDT_LOGIN, "", Window.wxDefaultPosition, new Size(100,-1), 0 );
        item4.Name = "edtLogin";
        item2.Add( item4, 0, Alignment.wxALIGN_CENTER_VERTICAL|Direction.wxALL, 0 );

        item1.Add( item2, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        BoxSizer item5 = new BoxSizer( Orientation.wxVERTICAL );
    
        StaticText item6 = new StaticText( parent, ID_TEXT, "Senha atual:", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item5.Add( item6, 0, Alignment.wxALIGN_CENTER_VERTICAL|Direction.wxRIGHT|Direction.wxBOTTOM, 5 );

        TextCtrl item7 = new TextCtrl( parent, EDT_SENHAATUAL, "", Window.wxDefaultPosition, new Size(100,-1), 0 );
        item7.Name = "edtSenhaAtual";
        item5.Add( item7, 0, Alignment.wxALIGN_CENTER_VERTICAL|Direction.wxALL, 0 );

        item1.Add( item5, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        BoxSizer item8 = new BoxSizer( Orientation.wxVERTICAL );
    
        StaticText item9 = new StaticText( parent, ID_TEXT, "Nova senha:", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item8.Add( item9, 0, Alignment.wxALIGN_CENTER_VERTICAL|Direction.wxRIGHT|Direction.wxBOTTOM, 5 );

        TextCtrl item10 = new TextCtrl( parent, EDT_NOVASENHA, "", Window.wxDefaultPosition, new Size(100,-1), 0 );
        item10.Name = "edtNovaSenha";
        item8.Add( item10, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 0 );

        item1.Add( item8, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        BoxSizer item11 = new BoxSizer( Orientation.wxVERTICAL );
    
        StaticText item12 = new StaticText( parent, ID_TEXT, "Confirmar senha:", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item11.Add( item12, 0, Alignment.wxALIGN_CENTER_VERTICAL|Direction.wxRIGHT|Direction.wxBOTTOM, 5 );

        TextCtrl item13 = new TextCtrl( parent, EDT_CONFIRMSENHA, "", Window.wxDefaultPosition, new Size(100,-1), 0 );
        item13.Name = "edtConfirmarSenha";
        item11.Add( item13, 0, Alignment.wxALIGN_CENTER_VERTICAL, 5 );

        item1.Add( item11, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        item0.Add( item1, 0, Alignment.wxALIGN_CENTER_VERTICAL|Direction.wxALL, 5 );

        BoxSizer item14 = new BoxSizer( Orientation.wxHORIZONTAL );
    
        Button item15 = new Button( parent, BTN_SALVAR, "Salvar", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item15.Name = "btnSalvar";
        item14.Add( item15, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        Button item16 = new Button( parent, BTN_LIMPAR, "Limpar", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item16.Name = "btnLimpar";
        item14.Add( item16, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        Button item17 = new Button( parent, BTN_FECHAR, "Fechar", Window.wxDefaultPosition, Window.wxDefaultSize, 0 );
        item17.Name = "btnFechar";
        item14.Add( item17, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        item0.Add( item14, 0, Alignment.wxALIGN_CENTER|Direction.wxALL, 5 );

        if (set_sizer)
        {
            // parent.SetAutoLayout( true );
            parent.SetSizer( item0 );
            if (call_fit)
            {
                item0.Fit( parent );
                item0.SetSizeHints( parent );
            }
        }
        
        return item0;
    }

    // Menubar functions

    public const int MNU_CADASSUNTOS = 11;
    public const int MNU_CADAUTORES = 12;
    public const int MNU_CADENDERECOS = 13;
    public const int MNU_CADIDIOMAS = 14;
    public const int MNU_CADPAISES = 15;
    public const int MNU_CADPROFISSOES = 16;
    public const int ID_MENU = 10026;
    public const int MNU_CADCLIENTES = 17;
    public const int MNU_CADLIVROS = 18;
    public const int MNU_CADASTROS = 10;
    public const int MNU_CONASSUNTOS = 21;
    public const int MNU_CONAUTORES = 22;
    public const int MNU_CONENDERECOS = 23;
    public const int MNU_CONIDIOMAS = 24;
    public const int MNU_CONPAISES = 25;
    public const int MNU_CONPROFISSOES = 26;
    public const int MNU_CONCLIENTES = 27;
    public const int MNU_CONLIVROS = 28;
    public const int MNU_PESQUISAS = 20;
    public const int MNU_VENDER = 31;
    public const int MNU_VENDASREALIZADAS = 32;
    public const int MNU_VENDAS = 30;
    public const int MNU_LADOALADOHORIZONTAL = 41;
    public const int MNU_LADOALADOVERTICAL = 42;
    public const int MNU_EMCASCATA = 43;
    public const int MNU_ORGANIZARICONES = 44;
    public const int MNU_JANELAS = 40;
    public const int MNU_ALTERARSENHA = 51;
    public const int MNU_SOBRE = 52;
    public const int MNU_SAIR = 53;
    public const int MNU_OPCOES = 50;

    public static MenuBar MontaBarraDeMenu()
    {
        MenuBar item0 = new MenuBar();
    
        Menu item1 = new Menu();
        item1.Append( MNU_CADASSUNTOS, "Assuntos", "");
        item1.Append( MNU_CADAUTORES, "Autores", "");
        item1.Append( MNU_CADENDERECOS, "Endereços", "");
        item1.Append( MNU_CADIDIOMAS, "Idiomas", "");
        item1.Append( MNU_CADPAISES, "Países", "");
        item1.Append( MNU_CADPROFISSOES, "Profissões", "");
        item1.AppendSeparator();
        item1.Append( MNU_CADCLIENTES, "Clientes", "");
        item1.Append( MNU_CADLIVROS, "Livros", "");
        item0.Append( item1, "Cadastros" );
    
        Menu item2 = new Menu();
        item2.Append( MNU_CONASSUNTOS, "Assuntos", "");
        item2.Append( MNU_CONAUTORES, "Autores", "");
        item2.Append( MNU_CONENDERECOS, "Endereços", "");
        item2.Append( MNU_CONIDIOMAS, "Idiomas", "");
        item2.Append( MNU_CONPAISES, "Países", "");
        item2.Append( MNU_CONPROFISSOES, "Profissões", "");
        item2.AppendSeparator();
        item2.Append( MNU_CONCLIENTES, "Clientes", "");
        item2.Append( MNU_CONLIVROS, "Livros", "");
        item0.Append( item2, "Pesquisas" );
    
        Menu item3 = new Menu();
        item3.Append( MNU_VENDER, "Vender", "");
        item3.Append( MNU_VENDASREALIZADAS, "Vendas Realizadas", "");
        item0.Append( item3, "Vendas" );
    
        Menu item4 = new Menu();
        item4.Append( MNU_LADOALADOHORIZONTAL, "Lado a lado horizontal", "");
        item4.Append( MNU_LADOALADOVERTICAL, "Lado a lado vertical", "");
        item4.Append( MNU_EMCASCATA, "Em cascata", "");
        item4.Append( MNU_ORGANIZARICONES, "Organizar Ícones", "");
        item0.Append( item4, "Janelas" );
    
        Menu item5 = new Menu();
        item5.Append( MNU_ALTERARSENHA, "Alterar Senha", "");
        item5.AppendSeparator();
        item5.Append( MNU_SOBRE, "Sobre", "");
        item5.Append( MNU_SAIR, "Sair", "");
        item0.Append( item5, "Opções" );
        
        return item0;

    }
    // Toolbar functions

    public const int TLB_CLIENTE = 0;
    public const int TLB_LIVRO = 1;
    public const int TLB_VENDAS = 2;
    public const int TLB_SOBRE = 3;
    public const int TLB_SAIR = 4;
    public static void MontaBarraDeFerramentas( ToolBar parent )
    {
        parent.Margins = new Size( 2,2 );
        
        parent.AddTool( TLB_CLIENTE, "", ListaBitmaps( 0 ), null, 0, "", "", null );
        parent.AddTool( TLB_LIVRO, "", ListaBitmaps( 1 ), null, 0, "", "", null );
        parent.AddTool( TLB_VENDAS, "", ListaBitmaps( 2 ), null, 0, "", "", null );
        parent.AddSeparator();
        parent.AddTool( TLB_SOBRE, "", ListaBitmaps( 3 ), null, 0, "", "", null );
        parent.AddTool( TLB_SAIR, "", ListaBitmaps( 4 ), null, 0, "", "", null );
        
        parent.Realize();
    }
    
    // Bitmap functions

    public const int BMP_CLIENTE = 0;
    public const int BMP_LIVRO = 1;
    public const int BMP_LIVROS = 2;
    public const int BMP_SOBRE = 3;
    public const int BMP_SAIR = 4;
    public const int BMP_LOGIN = 5;
    public const int BMP_SPLASH = 6;
    public const int BMP_LIVRUSVIRTUS = 7;
    
    public static wx.Bitmap ListaBitmaps( int index )
    {
        if ((index == 0) ||
            (index == BMP_CLIENTE))
        {
             wx.Image image = new wx.Image( "Livrus_wdr/ListaBitmaps_0.png" );
             wx.Bitmap bitmap = new wx.Bitmap( image );
             return bitmap;
        }
        if ((index == 1) ||
            (index == BMP_LIVRO))
        {
             wx.Image image = new wx.Image( "Livrus_wdr/ListaBitmaps_1.png" );
             wx.Bitmap bitmap = new wx.Bitmap( image );
             return bitmap;
        }
        if ((index == 2) ||
            (index == BMP_LIVROS))
        {
             wx.Image image = new wx.Image( "Livrus_wdr/ListaBitmaps_2.png" );
             wx.Bitmap bitmap = new wx.Bitmap( image );
             return bitmap;
        }
        if ((index == 3) ||
            (index == BMP_SOBRE))
        {
             wx.Image image = new wx.Image( "Livrus_wdr/ListaBitmaps_3.png" );
             wx.Bitmap bitmap = new wx.Bitmap( image );
             return bitmap;
        }
        if ((index == 4) ||
            (index == BMP_SAIR))
        {
             wx.Image image = new wx.Image( "Livrus_wdr/ListaBitmaps_4.png" );
             wx.Bitmap bitmap = new wx.Bitmap( image );
             return bitmap;
        }
        if ((index == 5) ||
            (index == BMP_LOGIN))
        {
             wx.Image image = new wx.Image( "Livrus_wdr/ListaBitmaps_5.png" );
             wx.Bitmap bitmap = new wx.Bitmap( image );
             return bitmap;
        }
        if ((index == 6) ||
            (index == BMP_SPLASH))
        {
             wx.Image image = new wx.Image( "Livrus_wdr/ListaBitmaps_6.png" );
             wx.Bitmap bitmap = new wx.Bitmap( image );
             return bitmap;
        }
        if ((index == 7) ||
            (index == BMP_LIVRUSVIRTUS))
        {
             wx.Image image = new wx.Image( "Livrus_wdr/ListaBitmaps_7.png" );
             wx.Bitmap bitmap = new wx.Bitmap( image );
             return bitmap;
        }
        return new wx.Bitmap();
    }
}

// End of generated file
