# generated by wxGlade 0.3.1 on Mon Dec 27 07:02:32 2004

from wxPython.wx import *

# begin wxGlade: dependencies
# end wxGlade

class frmAlterarSenha(wxPanel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: frmAlterarSenha.__init__
        kwds["style"] = wxTAB_TRAVERSAL
        wxPanel.__init__(self, *args, **kwds)
        self.labLogin = wxStaticText(self, ID_FRMALTERARSENHA_LABLOGIN, "Login: ")
        self.edtLogin = wxTextCtrl(self, ID_FRMALTERARSENHA_EDTLOGIN, "")
        self.labNovaSenha = wxStaticText(self, ID_FRMALTERARSENHA_LABNOVASENHA, "Nova Senha:")
        self.edtNovaSenha = wxTextCtrl(self, ID_FRMALTERARSENHA_EDTNOVASENHA, "")
        self.labSenhaAtual = wxStaticText(self, ID_FRMALTERARSENHA_LABSENHAATUAL, "Senha atual:")
        self.edtSenhaAtual = wxTextCtrl(self, ID_FRMALTERARSENHA_EDTSENHAATUAL, "")
        self.labConfirmarSenha = wxStaticText(self, ID_FRMALTERARSENHA_LABCONFIRMARSENHA, "Confirmar senha:")
        self.edtConfirmaSenha = wxTextCtrl(self, ID_FRMALTERARSENHA_EDTCONFIRMARSENHA, "")
        self.btnSalvar = wxButton(self, ID_FRMALTERARSENHA_BTNSALVAR, "&Salvar")
        self.btnLimpar = wxButton(self, ID_FRMALTERARSENHA_BTNLIMPAR, "&Limpar")
        self.btnFechar = wxButton(self, ID_FRMALTERARSENHA_BTNFECHAR, "&Fechar")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: frmAlterarSenha.__set_properties
        self.edtLogin.SetSize((100, 21))
        self.edtLogin.Enable(0)
        self.edtNovaSenha.SetSize((100, 21))
        self.edtSenhaAtual.SetSize((100, 21))
        self.edtSenhaAtual.SetFocus()
        self.edtConfirmaSenha.SetSize((100, 21))
        self.btnSalvar.SetSize((75, 25))
        self.btnLimpar.SetSize((75, 25))
        self.btnFechar.SetSize((75, 25))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: frmAlterarSenha.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        sizer_2 = wxBoxSizer(wxHORIZONTAL)
        sizer_9 = wxBoxSizer(wxHORIZONTAL)
        grid_sizer_10 = wxGridSizer(4, 1, 0, 0)
        grid_sizer_3 = wxGridSizer(4, 1, 0, 0)
        grid_sizer_3.Add(self.labLogin, 0, wxLEFT|wxALIGN_BOTTOM, 8)
        grid_sizer_3.Add(self.edtLogin, 0, wxLEFT, 8)
        grid_sizer_3.Add(self.labNovaSenha, 0, wxLEFT|wxALIGN_BOTTOM, 8)
        grid_sizer_3.Add(self.edtNovaSenha, 0, wxLEFT, 8)
        sizer_9.Add(grid_sizer_3, 0, 0, 0)
        grid_sizer_10.Add(self.labSenhaAtual, 0, wxLEFT|wxALIGN_BOTTOM, 4)
        grid_sizer_10.Add(self.edtSenhaAtual, 0, wxLEFT, 4)
        grid_sizer_10.Add(self.labConfirmarSenha, 0, wxLEFT|wxALIGN_BOTTOM, 4)
        grid_sizer_10.Add(self.edtConfirmaSenha, 0, wxLEFT, 4)
        sizer_9.Add(grid_sizer_10, 0, 0, 0)
        sizer_1.Add(sizer_9, 1, 0, 0)
        sizer_2.Add(self.btnSalvar, 0, wxALL, 2)
        sizer_2.Add(self.btnLimpar, 0, wxALL, 2)
        sizer_2.Add(self.btnFechar, 0, wxALL, 2)
        sizer_1.Add(sizer_2, 0, wxALL, 4)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        # end wxGlade

# end of class frmAlterarSenha


