// -*- C++ -*- generated by wxGlade 0.3.1 on Mon Dec 27 07:02:26 2004

#include <wx/wx.h>
#include <wx/image.h>

#ifndef FRMALTERARSENHA_H
#define FRMALTERARSENHA_H

// begin wxGlade: dependencies
// end wxGlade


class frmAlterarSenha: public wxPanel {
public:
    // begin wxGlade: frmAlterarSenha::ids
    // end wxGlade

    frmAlterarSenha(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: frmAlterarSenha::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: frmAlterarSenha::attributes
    wxStaticText* labLogin;
    wxTextCtrl* edtLogin;
    wxStaticText* labNovaSenha;
    wxTextCtrl* edtNovaSenha;
    wxStaticText* labSenhaAtual;
    wxTextCtrl* edtSenhaAtual;
    wxStaticText* labConfirmarSenha;
    wxTextCtrl* edtConfirmaSenha;
    wxButton* btnSalvar;
    wxButton* btnLimpar;
    wxButton* btnFechar;
    // end wxGlade
};


#endif // FRMALTERARSENHA_H
