# generated by wxGlade 0.3.1 on Fri Jan 14 19:47:45 2005
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;
package frmAlterarSenha;

use Wx qw[:everything];
use base qw(Wx::Panel);
use strict;

# begin wxGlade: ::dependencies
# end wxGlade

sub new {
	my( $self, $parent, $id, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: frmAlterarSenha::new

	$style = wxTAB_TRAVERSAL 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $pos, $size, $style, $name );
	$self->{labLogin} = Wx::StaticText->new($self, ID_FRMALTERARSENHA_LABLOGIN, "Login: ", wxDefaultPosition, wxDefaultSize, );
	$self->{edtLogin} = Wx::TextCtrl->new($self, ID_FRMALTERARSENHA_EDTLOGIN, "", wxDefaultPosition, wxDefaultSize, );
	$self->{labNovaSenha} = Wx::StaticText->new($self, ID_FRMALTERARSENHA_LABNOVASENHA, "Nova Senha:", wxDefaultPosition, wxDefaultSize, );
	$self->{edtNovaSenha} = Wx::TextCtrl->new($self, ID_FRMALTERARSENHA_EDTNOVASENHA, "", wxDefaultPosition, wxDefaultSize, );
	$self->{labSenhaAtual} = Wx::StaticText->new($self, ID_FRMALTERARSENHA_LABSENHAATUAL, "Senha atual:", wxDefaultPosition, wxDefaultSize, );
	$self->{edtSenhaAtual} = Wx::TextCtrl->new($self, ID_FRMALTERARSENHA_EDTSENHAATUAL, "", wxDefaultPosition, wxDefaultSize, );
	$self->{labConfirmarSenha} = Wx::StaticText->new($self, ID_FRMALTERARSENHA_LABCONFIRMARSENHA, "Confirmar senha:", wxDefaultPosition, wxDefaultSize, );
	$self->{edtConfirmaSenha} = Wx::TextCtrl->new($self, ID_FRMALTERARSENHA_EDTCONFIRMARSENHA, "", wxDefaultPosition, wxDefaultSize, );
		$self->{btnSalvar} = Wx::Button->new($self, ID_FRMALTERARSENHA_BTNSALVAR, "&Salvar");
		$self->{btnLimpar} = Wx::Button->new($self, ID_FRMALTERARSENHA_BTNLIMPAR, "&Limpar");
		$self->{btnFechar} = Wx::Button->new($self, ID_FRMALTERARSENHA_BTNFECHAR, "&Fechar");

	$self->__set_properties();
	$self->__do_layout();

	return $self;

# end wxGlade
}


sub __set_properties {
	my $self = shift;

# begin wxGlade: frmAlterarSenha::__set_properties

		$self->{edtLogin}->SetSize(100, 21);
		$self->{edtLogin}->Enable(0);
		$self->{edtNovaSenha}->SetSize(100, 21);
		$self->{edtSenhaAtual}->SetSize(100, 21);
		$self->{edtSenhaAtual}->SetFocus();
		$self->{edtConfirmaSenha}->SetSize(100, 21);
		$self->{btnSalvar}->SetSize(75, 25);
		$self->{btnLimpar}->SetSize(75, 25);
		$self->{btnFechar}->SetSize(75, 25);

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: frmAlterarSenha::__do_layout

		$self->{sizer_1} = Wx::BoxSizer->new(wxVERTICAL);
		$self->{sizer_2} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{sizer_9} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{grid_sizer_10} = Wx::GridSizer->new(4, 1, 0, 0);
		$self->{grid_sizer_3} = Wx::GridSizer->new(4, 1, 0, 0);
		$self->{grid_sizer_3}->Add($self->{labLogin}, 0, wxLEFT|wxALIGN_BOTTOM, 8);
		$self->{grid_sizer_3}->Add($self->{edtLogin}, 0, wxLEFT, 8);
		$self->{grid_sizer_3}->Add($self->{labNovaSenha}, 0, wxLEFT|wxALIGN_BOTTOM, 8);
		$self->{grid_sizer_3}->Add($self->{edtNovaSenha}, 0, wxLEFT, 8);
		$self->{sizer_9}->Add($self->{grid_sizer_3}, 0, 0, 0);
		$self->{grid_sizer_10}->Add($self->{labSenhaAtual}, 0, wxLEFT|wxALIGN_BOTTOM, 4);
		$self->{grid_sizer_10}->Add($self->{edtSenhaAtual}, 0, wxLEFT, 4);
		$self->{grid_sizer_10}->Add($self->{labConfirmarSenha}, 0, wxLEFT|wxALIGN_BOTTOM, 4);
		$self->{grid_sizer_10}->Add($self->{edtConfirmaSenha}, 0, wxLEFT, 4);
		$self->{sizer_9}->Add($self->{grid_sizer_10}, 0, 0, 0);
		$self->{sizer_1}->Add($self->{sizer_9}, 1, 0, 0);
		$self->{sizer_2}->Add($self->{btnSalvar}, 0, wxALL, 2);
		$self->{sizer_2}->Add($self->{btnLimpar}, 0, wxALL, 2);
		$self->{sizer_2}->Add($self->{btnFechar}, 0, wxALL, 2);
		$self->{sizer_1}->Add($self->{sizer_2}, 0, wxALL, 4);
		$self->SetAutoLayout(1);
		$self->SetSizer($self->{sizer_1});
		$self->{sizer_1}->Fit($self);
		$self->{sizer_1}->SetSizeHints($self);

# end wxGlade
}

# end of class frmAlterarSenha

1;

