// -*- C++ -*- generated by wxGlade 0.3.1 on Mon Dec 27 07:02:26 2004

#include "frmAlterarSenha.h"


frmAlterarSenha::frmAlterarSenha(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: frmAlterarSenha::frmAlterarSenha
    labLogin = new wxStaticText(this, ID_FRMALTERARSENHA_LABLOGIN, wxT("Login: "));
    edtLogin = new wxTextCtrl(this, ID_FRMALTERARSENHA_EDTLOGIN, wxT(""));
    labNovaSenha = new wxStaticText(this, ID_FRMALTERARSENHA_LABNOVASENHA, wxT("Nova Senha:"));
    edtNovaSenha = new wxTextCtrl(this, ID_FRMALTERARSENHA_EDTNOVASENHA, wxT(""));
    labSenhaAtual = new wxStaticText(this, ID_FRMALTERARSENHA_LABSENHAATUAL, wxT("Senha atual:"));
    edtSenhaAtual = new wxTextCtrl(this, ID_FRMALTERARSENHA_EDTSENHAATUAL, wxT(""));
    labConfirmarSenha = new wxStaticText(this, ID_FRMALTERARSENHA_LABCONFIRMARSENHA, wxT("Confirmar senha:"));
    edtConfirmaSenha = new wxTextCtrl(this, ID_FRMALTERARSENHA_EDTCONFIRMARSENHA, wxT(""));
    btnSalvar = new wxButton(this, ID_FRMALTERARSENHA_BTNSALVAR, wxT("&Salvar"));
    btnLimpar = new wxButton(this, ID_FRMALTERARSENHA_BTNLIMPAR, wxT("&Limpar"));
    btnFechar = new wxButton(this, ID_FRMALTERARSENHA_BTNFECHAR, wxT("&Fechar"));

    set_properties();
    do_layout();
    // end wxGlade
}


void frmAlterarSenha::set_properties()
{
    // begin wxGlade: frmAlterarSenha::set_properties
    edtLogin->SetSize(wxSize(100, 21));
    edtLogin->Enable(false);
    edtNovaSenha->SetSize(wxSize(100, 21));
    edtSenhaAtual->SetSize(wxSize(100, 21));
    edtSenhaAtual->SetFocus();
    edtConfirmaSenha->SetSize(wxSize(100, 21));
    btnSalvar->SetSize(wxSize(75, 25));
    btnLimpar->SetSize(wxSize(75, 25));
    btnFechar->SetSize(wxSize(75, 25));
    // end wxGlade
}


void frmAlterarSenha::do_layout()
{
    // begin wxGlade: frmAlterarSenha::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_9 = new wxBoxSizer(wxHORIZONTAL);
    wxGridSizer* grid_sizer_10 = new wxGridSizer(4, 1, 0, 0);
    wxGridSizer* grid_sizer_3 = new wxGridSizer(4, 1, 0, 0);
    grid_sizer_3->Add(labLogin, 0, wxLEFT|wxALIGN_BOTTOM, 8);
    grid_sizer_3->Add(edtLogin, 0, wxLEFT, 8);
    grid_sizer_3->Add(labNovaSenha, 0, wxLEFT|wxALIGN_BOTTOM, 8);
    grid_sizer_3->Add(edtNovaSenha, 0, wxLEFT, 8);
    sizer_9->Add(grid_sizer_3, 0, 0, 0);
    grid_sizer_10->Add(labSenhaAtual, 0, wxLEFT|wxALIGN_BOTTOM, 4);
    grid_sizer_10->Add(edtSenhaAtual, 0, wxLEFT, 4);
    grid_sizer_10->Add(labConfirmarSenha, 0, wxLEFT|wxALIGN_BOTTOM, 4);
    grid_sizer_10->Add(edtConfirmaSenha, 0, wxLEFT, 4);
    sizer_9->Add(grid_sizer_10, 0, 0, 0);
    sizer_1->Add(sizer_9, 1, 0, 0);
    sizer_2->Add(btnSalvar, 0, wxALL, 2);
    sizer_2->Add(btnLimpar, 0, wxALL, 2);
    sizer_2->Add(btnFechar, 0, wxALL, 2);
    sizer_1->Add(sizer_2, 0, wxALL, 4);
    SetAutoLayout(true);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    sizer_1->SetSizeHints(this);
    // end wxGlade
}

