// -*- C++ -*- generated by wxGlade 0.3.1 on Mon Dec 27 07:02:26 2004

#include <wx/wx.h>
#include <wx/image.h>

#ifndef FRMCONSULTAS_H
#define FRMCONSULTAS_H

// begin wxGlade: dependencies
#include <wx/grid.h>
// end wxGlade


class frmConsultas: public wxDialog {
public:
    // begin wxGlade: frmConsultas::ids
    // end wxGlade

    frmConsultas(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: frmConsultas::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: frmConsultas::attributes
    wxStaticText* labDescricao;
    wxTextCtrl* edtDescricao;
    wxButton* btnPesquisar;
    wxGrid* gridConsulta;
    wxStaticText* labRegistro;
    wxButton* btnLimpar;
    wxButton* btnFechar;
    // end wxGlade
};


#endif // FRMCONSULTAS_H
