# generated by wxGlade 0.3.1 on Fri Jan 14 19:47:45 2005
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;
package frmConsultas;

use Wx qw[:everything];
use base qw(Wx::Dialog);
use strict;

# begin wxGlade: ::dependencies
use Wx::Grid;
# end wxGlade

sub new {
	my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$title  = ""                 unless defined $title;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: frmConsultas::new

	$style = wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxTHICK_FRAME 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
	$self->{labDescricao} = Wx::StaticText->new($self, ID_FRMCONSULTAS_LABDESCRICAO, "Descrição:", wxDefaultPosition, wxDefaultSize, );
	$self->{edtDescricao} = Wx::TextCtrl->new($self, ID_FRMCONSULTAS_EDTDESCRICAO, "", wxDefaultPosition, wxDefaultSize, );
		$self->{btnPesquisar} = Wx::Button->new($self, ID_FRMCONSULTAS_BTNPESQUISAR, "&Pesquisar");
	$self->{gridConsulta} = Wx::Grid->new($self, ID_FRMCONSULTAS_GRIDCONSULTA);
	$self->{labRegistro} = Wx::StaticText->new($self, ID_FRMCONSULTAS_LABREGISTRO, "Registro 0 de 0", wxDefaultPosition, wxDefaultSize, );
		$self->{btnLimpar} = Wx::Button->new($self, ID_FRMCONSULTAS_BTNLIMPAR, "&Limpar");
		$self->{btnFechar} = Wx::Button->new($self, ID_FRMCONSULTAS_BTNFECHAR, "&Fechar");

	$self->__set_properties();
	$self->__do_layout();

	return $self;

# end wxGlade
}


sub __set_properties {
	my $self = shift;

# begin wxGlade: frmConsultas::__set_properties

	$self->SetTitle("Consulta de");
		$self->{labDescricao}->SetSize(51, 13);
		$self->{edtDescricao}->SetSize(257, 21);
		$self->{btnPesquisar}->SetSize(75, 25);
	$self->{gridConsulta}->CreateGrid(1, 2);
	$self->{gridConsulta}->SetColLabelSize(21);
	$self->{gridConsulta}->EnableEditing(0);
	$self->{gridConsulta}->SetSelectionMode(wxGridSelectRows);
	$self->{gridConsulta}->SetColLabelValue(0, "Código");
	$self->{gridConsulta}->SetColSize(0, 80);
	$self->{gridConsulta}->SetColLabelValue(1, "Descrição");
	$self->{gridConsulta}->SetColSize(1, 180);
		$self->{gridConsulta}->SetSize(355, 125);
		$self->{labRegistro}->SetSize(144, 13);
		$self->{btnLimpar}->SetSize(75, 25);
		$self->{btnFechar}->SetSize(75, 25);

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: frmConsultas::__do_layout

		$self->{sizer_1} = Wx::BoxSizer->new(wxVERTICAL);
		$self->{gird_sizer_2} = Wx::GridSizer->new(1, 2, 0, 0);
		$self->{sizer_2} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{sizer_3} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{sizer_4} = Wx::BoxSizer->new(wxVERTICAL);
		$self->{grid_sizer_1} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_1}->Add($self->{labDescricao}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_1}->Add($self->{edtDescricao}, 0, 0, 0);
		$self->{sizer_3}->Add($self->{grid_sizer_1}, 0, wxALL, 2);
		$self->{sizer_4}->Add(20, 20, 0, 0, 0);
		$self->{sizer_4}->Add($self->{btnPesquisar}, 0, wxLEFT|wxTOP|wxBOTTOM, 5);
		$self->{sizer_3}->Add($self->{sizer_4}, 0, 0, 0);
		$self->{sizer_1}->Add($self->{sizer_3}, 0, wxALL, 4);
		$self->{sizer_1}->Add($self->{gridConsulta}, 1, wxEXPAND, 0);
		$self->{gird_sizer_2}->Add($self->{labRegistro}, 0, wxALL, 10);
		$self->{sizer_2}->Add($self->{btnLimpar}, 0, wxALIGN_RIGHT|wxALIGN_BOTTOM, 8);
		$self->{sizer_2}->Add($self->{btnFechar}, 0, wxLEFT|wxALIGN_RIGHT|wxALIGN_BOTTOM, 8);
		$self->{gird_sizer_2}->Add($self->{sizer_2}, 1, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 4);
		$self->{sizer_1}->Add($self->{gird_sizer_2}, 0, wxALL|wxEXPAND|wxALIGN_BOTTOM, 0);
		$self->SetAutoLayout(1);
		$self->SetSizer($self->{sizer_1});
		$self->{sizer_1}->Fit($self);
		$self->{sizer_1}->SetSizeHints($self);
	$self->Layout();

# end wxGlade
}

# end of class frmConsultas

1;

