# generated by wxGlade 0.3.1 on Mon Dec 27 07:02:32 2004

from wxPython.wx import *

# begin wxGlade: dependencies
# end wxGlade

class frmCadEnderecos(wxPanel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: frmCadEnderecos.__init__
        kwds["style"] = wxTAB_TRAVERSAL
        wxPanel.__init__(self, *args, **kwds)
        self.labCodigo = wxStaticText(self, ID_FRMCADASTROS_LABCODIGO, "Código:")
        self.edtCodigo = wxTextCtrl(self, ID_FRMCADASTROS_EDTCODIGO, "")
        self.btnNovo = wxButton(self, ID_FRMCADASTROS_BTNNOVO, "&Novo")
        self.labDescricao = wxStaticText(self, ID_FRMCADASTROS_LABDESCRICAO, "Logradouro: ")
        self.edtDescricao = wxTextCtrl(self, ID_FRMCADASTROS_EDTDESCRICAO, "")
        self.labBairro = wxStaticText(self, ID_FRMCADENDERECOS_LABBAIRRO, "Bairro:")
        self.edtBairro = wxTextCtrl(self, ID_FRMCADENDERECOS_EDTBAIRRO, "")
        self.labCEP = wxStaticText(self, ID_FRMCADENDERECOS_LABCEP, "CEP: ")
        self.edtCEP = wxTextCtrl(self, ID_FRMCADENDERECOS_EDTCEP, "")
        self.labCidade = wxStaticText(self, ID_FRMCADENDERECOS_LABCIDADE, "Cidade: ")
        self.edtCidade = wxTextCtrl(self, ID_FRMCADENDERECOS_EDTCIDADE, "")
        self.labEstado = wxStaticText(self, ID_FRMCADENDERECOS_LABESTADO, "Estado: ")
        self.cmbEstado = wxChoice(self, ID_FRMCADENDERECOS_CMBESTADO, choices=["choice 1"])
        self.btnPesquisar = wxButton(self, ID_FRMCADASTROS_BTNPESQUISAR, "&Pesquisar")
        self.btnAnterior = wxButton(self, ID_FRMCADASTROS_BTNANTERIOR, "&Anterior")
        self.btnProximo = wxButton(self, ID_FRMCADASTROS_BTNPROXIMO, "Próxi&mo")
        self.btnSalvar = wxButton(self, ID_FRMCADASTROS_BTNSALVAR, "&Salvar")
        self.btnExcluir = wxButton(self, ID_FRMCADASTROS_BTNEXCLUIR, "&Excluir")
        self.btnLimpar = wxButton(self, ID_FRMCADASTROS_BTNLIMPAR, "&Limpar")
        self.btnFechar = wxButton(self, ID_FRMCADASTROS_BTNFECHAR, "&Fechar")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: frmCadEnderecos.__set_properties
        self.labCodigo.SetSize((36, 13))
        self.edtCodigo.SetSize((121, 21))
        self.btnNovo.SetSize((75, 25))
        self.labDescricao.SetSize((57, 13))
        self.edtDescricao.SetSize((264, 21))
        self.edtDescricao.Enable(0)
        self.labBairro.SetSize((48, 13))
        self.edtBairro.SetSize((144, 21))
        self.edtBairro.Enable(0)
        self.labCEP.SetSize((40, 13))
        self.edtCEP.SetSize((72, 21))
        self.edtCEP.Enable(0)
        self.labCidade.SetSize((39, 13))
        self.edtCidade.SetSize((184, 21))
        self.edtCidade.Enable(0)
        self.labEstado.SetSize((56, 13))
        self.cmbEstado.SetSize((144, 21))
        self.cmbEstado.Enable(0)
        self.cmbEstado.SetSelection(0)
        self.btnPesquisar.SetSize((75, 25))
        self.btnAnterior.SetSize((75, 25))
        self.btnAnterior.Enable(0)
        self.btnProximo.SetSize((75, 25))
        self.btnProximo.Enable(0)
        self.btnSalvar.SetSize((75, 25))
        self.btnSalvar.Enable(0)
        self.btnExcluir.SetSize((75, 25))
        self.btnExcluir.Enable(0)
        self.btnLimpar.SetSize((75, 25))
        self.btnFechar.SetSize((75, 25))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: frmCadEnderecos.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        sizer_2 = wxBoxSizer(wxHORIZONTAL)
        sizer_3 = wxBoxSizer(wxHORIZONTAL)
        sizer_4 = wxBoxSizer(wxVERTICAL)
        sizer_5 = wxBoxSizer(wxVERTICAL)
        sizer_6 = wxBoxSizer(wxHORIZONTAL)
        grid_sizer_6 = wxGridSizer(2, 1, 0, 0)
        grid_sizer_5 = wxGridSizer(2, 1, 0, 0)
        grid_sizer_4 = wxGridSizer(2, 1, 0, 0)
        sizer_8 = wxBoxSizer(wxHORIZONTAL)
        grid_sizer_9 = wxGridSizer(2, 1, 0, 0)
        grid_sizer_8 = wxGridSizer(2, 1, 0, 0)
        sizer_7 = wxBoxSizer(wxHORIZONTAL)
        grid_sizer_7 = wxGridSizer(2, 1, 0, 0)
        grid_sizer_7.Add(self.labCodigo, 0, wxALIGN_BOTTOM, 0)
        grid_sizer_7.Add(self.edtCodigo, 0, 0, 0)
        sizer_7.Add(grid_sizer_7, 0, 0, 0)
        sizer_7.Add(self.btnNovo, 0, wxLEFT|wxALIGN_BOTTOM, 5)
        sizer_5.Add(sizer_7, 1, 0, 0)
        grid_sizer_8.Add(self.labDescricao, 0, wxALIGN_BOTTOM, 0)
        grid_sizer_8.Add(self.edtDescricao, 0, 0, 0)
        sizer_8.Add(grid_sizer_8, 0, 0, 0)
        grid_sizer_9.Add(self.labBairro, 0, wxALIGN_BOTTOM, 0)
        grid_sizer_9.Add(self.edtBairro, 0, 0, 0)
        sizer_8.Add(grid_sizer_9, 0, wxLEFT, 2)
        sizer_5.Add(sizer_8, 1, wxEXPAND, 0)
        grid_sizer_4.Add(self.labCEP, 0, wxALIGN_BOTTOM, 0)
        grid_sizer_4.Add(self.edtCEP, 0, 0, 0)
        sizer_6.Add(grid_sizer_4, 0, 0, 0)
        grid_sizer_5.Add(self.labCidade, 0, wxALIGN_BOTTOM, 0)
        grid_sizer_5.Add(self.edtCidade, 0, 0, 0)
        sizer_6.Add(grid_sizer_5, 0, wxLEFT, 4)
        grid_sizer_6.Add(self.labEstado, 0, wxALIGN_BOTTOM, 0)
        grid_sizer_6.Add(self.cmbEstado, 0, 0, 0)
        sizer_6.Add(grid_sizer_6, 0, wxLEFT, 5)
        sizer_5.Add(sizer_6, 0, 0, 0)
        sizer_3.Add(sizer_5, 0, 0, 0)
        sizer_4.Add(self.btnPesquisar, 0, wxALL|wxALIGN_RIGHT, 2)
        sizer_4.Add(self.btnAnterior, 0, wxALL|wxALIGN_RIGHT, 2)
        sizer_4.Add(self.btnProximo, 0, wxALL|wxALIGN_RIGHT, 2)
        sizer_3.Add(sizer_4, 1, 0, 0)
        sizer_1.Add(sizer_3, 1, wxALL|wxEXPAND, 4)
        sizer_2.Add(self.btnSalvar, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2)
        sizer_2.Add(self.btnExcluir, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2)
        sizer_2.Add(self.btnLimpar, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2)
        sizer_2.Add(self.btnFechar, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2)
        sizer_1.Add(sizer_2, 0, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT|wxALIGN_BOTTOM, 4)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        # end wxGlade

# end of class frmCadEnderecos


