# generated by wxGlade 0.3.1 on Fri Jan 14 19:47:45 2005
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;
package frmCadastros;

use Wx qw[:everything];
use base qw(Wx::Panel);
use strict;

# begin wxGlade: ::dependencies
# end wxGlade

sub new {
	my( $self, $parent, $id, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: frmCadastros::new

	$style = wxTAB_TRAVERSAL 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $pos, $size, $style, $name );
	$self->{labCodigo} = Wx::StaticText->new($self, ID_FRMCADASTROS_LABCODIGO, "Código:", wxDefaultPosition, wxDefaultSize, );
	$self->{edtCodigo} = Wx::TextCtrl->new($self, ID_FRMCADASTROS_EDTCODIGO, "", wxDefaultPosition, wxDefaultSize, );
		$self->{btnNovo} = Wx::Button->new($self, ID_FRMCADASTROS_BTNNOVO, "&Novo");
	$self->{labDescricao} = Wx::StaticText->new($self, ID_FRMCADASTROS_LABDESCRICAO, "Descrição:", wxDefaultPosition, wxDefaultSize, );
	$self->{edtDescricao} = Wx::TextCtrl->new($self, ID_FRMCADASTROS_EDTDESCRICAO, "", wxDefaultPosition, wxDefaultSize, );
		$self->{btnPesquisar} = Wx::Button->new($self, ID_FRMCADASTROS_BTNPESQUISAR, "&Pesquisar");
		$self->{btnAnterior} = Wx::Button->new($self, ID_FRMCADASTROS_BTNANTERIOR, "&Anterior");
		$self->{btnProximo} = Wx::Button->new($self, ID_FRMCADASTROS_BTNPROXIMO, "Próxi&mo");
		$self->{btnSalvar} = Wx::Button->new($self, ID_FRMCADASTROS_BTNSALVAR, "&Salvar");
		$self->{btnExcluir} = Wx::Button->new($self, ID_FRMCADASTROS_BTNEXCLUIR, "&Excluir");
		$self->{btnLimpar} = Wx::Button->new($self, ID_FRMCADASTROS_BTNLIMPAR, "&Limpar");
		$self->{btnFechar} = Wx::Button->new($self, ID_FRMCADASTROS_BTNFECHAR, "&Fechar");

	$self->__set_properties();
	$self->__do_layout();

	return $self;

# end wxGlade
}


sub __set_properties {
	my $self = shift;

# begin wxGlade: frmCadastros::__set_properties

		$self->{labCodigo}->SetSize(121, 13);
		$self->{edtCodigo}->SetSize(121, 21);
		$self->{btnNovo}->SetSize(75, 25);
		$self->{labDescricao}->SetSize(51, 13);
		$self->{edtDescricao}->SetSize(217, 21);
		$self->{edtDescricao}->Enable(0);
		$self->{btnPesquisar}->SetSize(75, 25);
		$self->{btnAnterior}->SetSize(75, 25);
		$self->{btnAnterior}->Enable(0);
		$self->{btnProximo}->SetSize(75, 25);
		$self->{btnProximo}->Enable(0);
		$self->{btnSalvar}->SetSize(75, 25);
		$self->{btnSalvar}->Enable(0);
		$self->{btnExcluir}->SetSize(75, 25);
		$self->{btnExcluir}->Enable(0);
		$self->{btnLimpar}->SetSize(75, 25);
		$self->{btnFechar}->SetSize(75, 25);

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: frmCadastros::__do_layout

		$self->{sizer_1} = Wx::BoxSizer->new(wxVERTICAL);
		$self->{sizer_2} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{sizer_3} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{sizer_4} = Wx::BoxSizer->new(wxVERTICAL);
		$self->{sizer_5} = Wx::BoxSizer->new(wxVERTICAL);
		$self->{grid_sizer_2} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_1} = Wx::GridSizer->new(2, 2, 0, 1);
		$self->{grid_sizer_1}->Add($self->{labCodigo}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_1}->Add(20, 10, 0, 0, 0);
		$self->{grid_sizer_1}->Add($self->{edtCodigo}, 0, 0, 0);
		$self->{grid_sizer_1}->Add($self->{btnNovo}, 0, wxLEFT, 6);
		$self->{sizer_5}->Add($self->{grid_sizer_1}, 0, 0, 0);
		$self->{grid_sizer_2}->Add($self->{labDescricao}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_2}->Add($self->{edtDescricao}, 0, 0, 2);
		$self->{sizer_5}->Add($self->{grid_sizer_2}, 0, 0, 0);
		$self->{sizer_3}->Add($self->{sizer_5}, 1, 0, 0);
		$self->{sizer_4}->Add($self->{btnPesquisar}, 0, wxALL|wxALIGN_RIGHT, 2);
		$self->{sizer_4}->Add($self->{btnAnterior}, 0, wxALL|wxALIGN_RIGHT, 2);
		$self->{sizer_4}->Add($self->{btnProximo}, 0, wxALL|wxALIGN_RIGHT, 2);
		$self->{sizer_3}->Add($self->{sizer_4}, 0, wxALIGN_RIGHT, 0);
		$self->{sizer_1}->Add($self->{sizer_3}, 1, wxALL|wxEXPAND, 4);
		$self->{sizer_2}->Add($self->{btnSalvar}, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2);
		$self->{sizer_2}->Add($self->{btnExcluir}, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2);
		$self->{sizer_2}->Add($self->{btnLimpar}, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2);
		$self->{sizer_2}->Add($self->{btnFechar}, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2);
		$self->{sizer_1}->Add($self->{sizer_2}, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 4);
		$self->SetAutoLayout(1);
		$self->SetSizer($self->{sizer_1});
		$self->{sizer_1}->Fit($self);
		$self->{sizer_1}->SetSizeHints($self);

# end wxGlade
}

# end of class frmCadastros

1;

