// -*- C++ -*- generated by wxGlade 0.3.1 on Mon Dec 27 07:02:26 2004

#include "frmConVendas.h"


frmConVendas::frmConVendas(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: frmConVendas::frmConVendas
    labDtHrVenda = new wxStaticText(this, ID_FRMCONVENDAS_LABDTHRVENDA, wxT("Data/Hora Venda: "));
    edtDtHrVenda = new wxTextCtrl(this, ID_FRMCONVENDAS_EDTDTHRVENDA, wxT(""));
    btnPesquisar = new wxButton(this, ID_FRMCONVENDAS_BTNPESQUISAR, wxT("&Pesquisar"));
    labCPF = new wxStaticText(this, ID_FRMCONVENDAS_LABCPF, wxT("CPF: "));
    edtCPF = new wxTextCtrl(this, ID_FRMCONVENDAS_EDTCPF, wxT(""));
    labCliente = new wxStaticText(this, ID_FRMCONVENDAS_LABCLIENTE, wxT("Cliente: "));
    edtCliente = new wxTextCtrl(this, ID_FRMCONVENDAS_EDTCLIENTE, wxT(""));
    btnPCliente = new wxButton(this, ID_FRMCONVENDAS_BTNPCLIENTE, wxT("..."));
    labISBN = new wxStaticText(this, ID_FRMCONVENDAS_LABISBN, wxT("ISBN: "));
    edtISBN = new wxTextCtrl(this, ID_FRMCONVENDAS_EDTISBN, wxT(""));
    labLivro = new wxStaticText(this, ID_FRMCONVENDAS_LABLIVRO, wxT("Livro: "));
    edtLivro = new wxTextCtrl(this, ID_FRMCONVENDAS_EDTLIVRO, wxT(""));
    btnPLivro = new wxButton(this, ID_FRMCONVENDAS_BTNPLIVRO, wxT("..."));
    gridVendas = new wxGrid(this, ID_FRMCONVENDAS_GRIDVENDAS);
    labRegistro = new wxStaticText(this, ID_FRMCONVENDAS_LABREGISTRO, wxT("Registro 0 de 0"));
    labPrecoTotal = new wxStaticText(this, ID_FRMCONVENDAS_LABPRECOTOTAL, wxT("Preço Total: "));
    edtPrecoTotal = new wxTextCtrl(this, ID_FRMCONVENDAS_EDTPRECOTOTAL, wxT(""));
    btnLimpar = new wxButton(this, ID_FRMCONVENDAS_BTNLIMPAR, wxT("&Limpar"));
    btnFechar = new wxButton(this, ID_FRMCONVENDAS_BTNFECHAR, wxT("&Fechar"));

    set_properties();
    do_layout();
    // end wxGlade
}


void frmConVendas::set_properties()
{
    // begin wxGlade: frmConVendas::set_properties
    labDtHrVenda->SetSize(wxSize(91, 13));
    edtDtHrVenda->SetSize(wxSize(128, 21));
    btnPesquisar->SetSize(wxSize(75, 25));
    edtCPF->SetSize(wxSize(128, 21));
    edtCliente->SetSize(wxSize(306, 21));
    edtCliente->Enable(false);
    btnPCliente->SetSize(wxSize(21, 21));
    edtISBN->SetSize(wxSize(128, 21));
    edtLivro->SetSize(wxSize(306, 21));
    edtLivro->Enable(false);
    btnPLivro->SetSize(wxSize(21, 21));
    gridVendas->CreateGrid(10, 6);
    gridVendas->SetColLabelSize(21);
    gridVendas->EnableEditing(false);
    gridVendas->SetSelectionMode(wxGrid::wxGridSelectRows);
    gridVendas->SetSize(wxSize(467, 137));
    labRegistro->SetSize(wxSize(144, 13));
    labPrecoTotal->SetSize(wxSize(61,13));
    edtPrecoTotal->SetSize(wxSize(127, 21));
    edtPrecoTotal->Enable(false);
    btnLimpar->SetSize(wxSize(75, 25));
    btnFechar->SetSize(wxSize(75, 25));
    // end wxGlade
}


void frmConVendas::do_layout()
{
    // begin wxGlade: frmConVendas::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_6 = new wxBoxSizer(wxVERTICAL);
    wxGridSizer* sizer_22 = new wxGridSizer(1, 2, 0, 0);
    wxBoxSizer* sizer_23 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_8 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_7 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_24 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxHORIZONTAL);
    wxGridSizer* grid_sizer_8 = new wxGridSizer(2, 1, 0, 0);
    wxGridSizer* grid_sizer_6 = new wxGridSizer(2, 1, 0, 0);
    wxGridSizer* grid_sizer_5 = new wxGridSizer(2, 1, 0, 0);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    wxGridSizer* grid_sizer_4 = new wxGridSizer(2, 1, 0, 0);
    wxGridSizer* grid_sizer_3 = new wxGridSizer(2, 1, 0, 0);
    wxGridSizer* grid_sizer_2 = new wxGridSizer(2, 1, 0, 0);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    wxGridSizer* grid_sizer_1 = new wxGridSizer(2, 1, 0, 0);
    grid_sizer_1->Add(labDtHrVenda, 0, wxALIGN_BOTTOM, 0);
    grid_sizer_1->Add(edtDtHrVenda, 0, 0, 0);
    sizer_2->Add(grid_sizer_1, 0, wxLEFT, 2);
    sizer_2->Add(btnPesquisar, 0, wxLEFT|wxTOP|wxALIGN_BOTTOM, 10);
    sizer_1->Add(sizer_2, 0, 0, 0);
    grid_sizer_2->Add(labCPF, 0, wxALIGN_BOTTOM, 0);
    grid_sizer_2->Add(edtCPF, 0, 0, 0);
    sizer_3->Add(grid_sizer_2, 0, wxLEFT, 2);
    grid_sizer_3->Add(labCliente, 0, wxALIGN_BOTTOM, 0);
    grid_sizer_3->Add(edtCliente, 0, 0, 0);
    sizer_3->Add(grid_sizer_3, 0, wxLEFT, 2);
    grid_sizer_4->Add(20, 20, 0, 0, 0);
    grid_sizer_4->Add(btnPCliente, 0, 0, 0);
    sizer_3->Add(grid_sizer_4, 0, 0, 0);
    sizer_1->Add(sizer_3, 0, 0, 0);
    grid_sizer_5->Add(labISBN, 0, wxALIGN_BOTTOM, 0);
    grid_sizer_5->Add(edtISBN, 0, 0, 0);
    sizer_4->Add(grid_sizer_5, 0, wxLEFT, 2);
    grid_sizer_6->Add(labLivro, 0, wxALIGN_BOTTOM, 0);
    grid_sizer_6->Add(edtLivro, 0, 0, 0);
    sizer_4->Add(grid_sizer_6, 0, wxLEFT, 2);
    grid_sizer_8->Add(20, 20, 0, 0, 0);
    grid_sizer_8->Add(btnPLivro, 0, 0, 0);
    sizer_4->Add(grid_sizer_8, 0, 0, 0);
    sizer_1->Add(sizer_4, 0, 0, 0);
    sizer_1->Add(gridVendas, 1, wxALL|wxEXPAND, 2);
    sizer_24->Add(labRegistro, 0, wxALL, 4);
    sizer_24->Add(20, 20, 0, 0, 0);
    sizer_22->Add(sizer_24, 0, 0, 0);
    sizer_7->Add(labPrecoTotal, 0, wxALL, 2);
    sizer_7->Add(edtPrecoTotal, 0, wxALL, 2);
    sizer_23->Add(sizer_7, 0, wxALL|wxALIGN_RIGHT, 2);
    sizer_8->Add(btnLimpar, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2);
    sizer_8->Add(btnFechar, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2);
    sizer_23->Add(sizer_8, 0, wxALL|wxALIGN_RIGHT, 2);
    sizer_22->Add(sizer_23, 1, wxALIGN_RIGHT|wxALIGN_BOTTOM, 0);
    sizer_6->Add(sizer_22, 0, wxEXPAND, 0);
    sizer_1->Add(sizer_6, 0, wxEXPAND, 0);
    SetAutoLayout(true);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    sizer_1->SetSizeHints(this);
    // end wxGlade
}

