// -*- C++ -*- generated by wxGlade 0.3.1 on Mon Dec 27 07:02:26 2004

#include <wx/wx.h>
#include <wx/image.h>

#ifndef FRMCADASTROS_H
#define FRMCADASTROS_H

// begin wxGlade: dependencies
// end wxGlade


class frmCadastros: public wxPanel {
public:
    // begin wxGlade: frmCadastros::ids
    // end wxGlade

    frmCadastros(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: frmCadastros::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: frmCadastros::attributes
    wxStaticText* labCodigo;
    wxTextCtrl* edtCodigo;
    wxButton* btnNovo;
    wxStaticText* labDescricao;
    wxTextCtrl* edtDescricao;
    wxButton* btnPesquisar;
    wxButton* btnAnterior;
    wxButton* btnProximo;
    wxButton* btnSalvar;
    wxButton* btnExcluir;
    wxButton* btnLimpar;
    wxButton* btnFechar;
    // end wxGlade
};


#endif // FRMCADASTROS_H
