// -*- C++ -*- generated by wxGlade 0.3.1 on Mon Dec 27 07:02:26 2004

#include "frmCadClientes.h"


frmCadClientes::frmCadClientes(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: frmCadClientes::frmCadClientes
    labCodigo = new wxStaticText(this, ID_FRMCADASTROS_LABCODIGO, wxT("Código:"));
    edtCodigo = new wxTextCtrl(this, ID_FRMCADASTROS_EDTCODIGO, wxT(""));
    btnNovo = new wxButton(this, ID_FRMCADASTROS_BTNNOVO, wxT("&Novo"));
    labDescricao = new wxStaticText(this, ID_FRMCADASTROS_LABDESCRICAO, wxT("Logradouro: "));
    edtDescricao = new wxTextCtrl(this, ID_FRMCADASTROS_EDTDESCRICAO, wxT(""));
    labEmail = new wxStaticText(this, ID_FRMCADCLIENTES_LABEMAIL, wxT("E-mail:"));
    edtEmail = new wxTextCtrl(this, ID_FRMCADCLIENTES_EDTEMAIL, wxT(""));
    labIdentidade = new wxStaticText(this, ID_FRMCADCLIENTES_LABIDENTIDADE, wxT("Identidade: "));
    edtIdentidade = new wxTextCtrl(this, ID_FRMCADCLIENTES_EDTIDENTIDADE, wxT(""));
    const wxString rbSexo_choices[] = {
        wxT("Masculino"),
        wxT("Feminino")
    };
    rbSexo = new wxRadioBox(this, ID_FRMCADCLIENTES_RBSEXO, wxT("Sexo"), wxDefaultPosition, wxDefaultSize, 2, rbSexo_choices, 2, wxRA_SPECIFY_COLS);
    labTelefone = new wxStaticText(this, ID_FRMCADCLIENTES_LABTELEFONE, wxT("Telefone: "));
    edtTelefone = new wxTextCtrl(this, ID_FRMCADCLIENTES_EDTTELEFONE, wxT(""));
    labDtNasc = new wxStaticText(this, ID_FRMCADCLIENTES_LABDTNASC, wxT("Dt. Nascimento"));
    edtDtNasc = new wxTextCtrl(this, ID_FRMCADCLIENTES_EDTDTNASC, wxT(""));
    edtCodEndereco = new wxTextCtrl(this, ID_FRMCADCLIENTES_EDTCODENDERECO, wxT(""));
    btnPEndereco = new wxButton(this, ID_FRMCADCLIENTES_BTNPENDERECO, wxT("..."));
    labLogradouro = new wxStaticText(this, ID_FRMCADCLIENTES_LABLOGRADOURO, wxT("Logradouro: "));
    edtLogradouro = new wxTextCtrl(this, ID_FRMCADCLIENTES_EDTLOGRADOURO, wxT(""));
    labBairro = new wxStaticText(this, ID_FRMCADCLIENTES_LABBAIRRO, wxT("Bairro:"));
    edtBairro = new wxTextCtrl(this, ID_FRMCADCLIENTES_EDTBAIRRO, wxT(""));
    labCEP = new wxStaticText(this, ID_FRMCADCLIENTES_LABCEP, wxT("CEP:"));
    edtCEP = new wxTextCtrl(this, ID_FRMCADCLIENTES_EDTCEP, wxT(""));
    labCidade = new wxStaticText(this, ID_FRMCADCLIENTES_LABCIDADE, wxT("Cidade: "));
    edtCidade = new wxTextCtrl(this, ID_FRMCADCLIENTES_EDTCIDADE, wxT(""));
    labEstado = new wxStaticText(this, ID_FRMCADCLIENTES_LABESTADO, wxT("Estado: "));
    edtEstado = new wxTextCtrl(this, ID_FRMCADCLIENTES_EDTESTADO, wxT(""));
    labPais = new wxStaticText(this, ID_FRMCADCLIENTES_LABPAIS, wxT("País de origem: "));
    edtCodPais = new wxTextCtrl(this, ID_FRMCADCLIENTES_EDTCODPAIS, wxT(""));
    edtPais = new wxTextCtrl(this, ID_FRMCADCLIENTES_EDTPAIS, wxT(""));
    btnPPais = new wxButton(this, ID_FRMCADCLIENTES_BTNPPAIS, wxT("..."));
    labProfissao = new wxStaticText(this, ID_FRMCADCLIENTES_LABPROFISSAO, wxT("Profissão: "));
    edtCodProfissao = new wxTextCtrl(this, ID_FRMCADCLIENTES_EDTCODPROFISSAO, wxT(""));
    edtProfissao = new wxTextCtrl(this, ID_FRMCADCLIENTES_EDTPROFISSAO, wxT(""));
    btnPProfissao = new wxButton(this, ID_FRMCADCLIENTES_BTNPPROFISSAO, wxT("..."));
    btnPesquisar = new wxButton(this, ID_FRMCADASTROS_BTNPESQUISAR, wxT("&Pesquisar"));
    btnAnterior = new wxButton(this, ID_FRMCADASTROS_BTNANTERIOR, wxT("&Anterior"));
    btnProximo = new wxButton(this, ID_FRMCADASTROS_BTNPROXIMO, wxT("Próxi&mo"));
    btnSalvar = new wxButton(this, ID_FRMCADASTROS_BTNSALVAR, wxT("&Salvar"));
    btnExcluir = new wxButton(this, ID_FRMCADASTROS_BTNEXCLUIR, wxT("&Excluir"));
    btnLimpar = new wxButton(this, ID_FRMCADASTROS_BTNLIMPAR, wxT("&Limpar"));
    btnFechar = new wxButton(this, ID_FRMCADASTROS_BTNFECHAR, wxT("&Fechar"));

    set_properties();
    do_layout();
    // end wxGlade
}


void frmCadClientes::set_properties()
{
    // begin wxGlade: frmCadClientes::set_properties
    labCodigo->SetSize(wxSize(36, 13));
    edtCodigo->SetSize(wxSize(121, 21));
    btnNovo->SetSize(wxSize(75, 25));
    labDescricao->SetSize(wxSize(57, 13));
    edtDescricao->SetSize(wxSize(264, 21));
    edtDescricao->Enable(false);
    labEmail->SetSize(wxSize(40, 13));
    edtEmail->SetSize(wxSize(312, 21));
    edtEmail->Enable(false);
    edtIdentidade->SetSize(wxSize(100, 21));
    edtIdentidade->Enable(false);
    rbSexo->SetSize(wxSize(200, 44));
    rbSexo->Enable(false);
    rbSexo->SetSelection(0);
    labTelefone->SetSize(wxSize(48, 13));
    edtTelefone->SetSize(wxSize(104, 21));
    edtTelefone->Enable(false);
    labDtNasc->SetSize(wxSize(73, 13));
    edtDtNasc->SetSize(wxSize(100, 21));
    edtDtNasc->Enable(false);
    edtCodEndereco->SetSize(wxSize(88, 21));
    edtCodEndereco->Enable(false);
    btnPEndereco->SetSize(wxSize(21, 21));
    btnPEndereco->Enable(false);
    edtLogradouro->SetSize(wxSize(264, 21));
    edtLogradouro->Enable(false);
    labBairro->SetSize(wxSize(48, 13));
    edtBairro->SetSize(wxSize(144, 21));
    edtBairro->Enable(false);
    labCEP->SetSize(wxSize(40, 13));
    edtCEP->SetSize(wxSize(78, 21));
    edtCEP->Enable(false);
    edtCidade->SetSize(wxSize(184, 21));
    edtCidade->Enable(false);
    edtEstado->SetSize(wxSize(144, 21));
    edtEstado->Enable(false);
    edtCodPais->SetSize(wxSize(78, 21));
    edtCodPais->Enable(false);
    edtPais->SetSize(wxSize(240, 21));
    edtPais->Enable(false);
    btnPPais->SetSize(wxSize(21, 21));
    btnPPais->Enable(false);
    edtCodProfissao->SetSize(wxSize(78, 21));
    edtCodProfissao->Enable(false);
    edtProfissao->SetSize(wxSize(240, 21));
    edtProfissao->Enable(false);
    btnPProfissao->SetSize(wxSize(21, 21));
    btnPProfissao->Enable(false);
    btnPesquisar->SetSize(wxSize(75, 25));
    btnAnterior->SetSize(wxSize(75, 25));
    btnAnterior->Enable(false);
    btnProximo->SetSize(wxSize(75, 25));
    btnProximo->Enable(false);
    btnSalvar->SetSize(wxSize(75, 25));
    btnSalvar->Enable(false);
    btnExcluir->SetSize(wxSize(75, 25));
    btnExcluir->Enable(false);
    btnLimpar->SetSize(wxSize(75, 25));
    btnFechar->SetSize(wxSize(75, 25));
    // end wxGlade
}


void frmCadClientes::do_layout()
{
    // begin wxGlade: frmCadClientes::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_5 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_16 = new wxBoxSizer(wxHORIZONTAL);
    wxGridSizer* grid_sizer_23 = new wxGridSizer(2, 1, 0, 0);
    wxGridSizer* grid_sizer_22 = new wxGridSizer(2, 1, 0, 0);
    wxGridSizer* grid_sizer_19 = new wxGridSizer(2, 1, 0, 0);
    wxBoxSizer* sizer_15 = new wxBoxSizer(wxHORIZONTAL);
    wxGridSizer* grid_sizer_21 = new wxGridSizer(2, 1, 0, 0);
    wxGridSizer* grid_sizer_20 = new wxGridSizer(2, 1, 0, 0);
    wxGridSizer* grid_sizer_18 = new wxGridSizer(2, 1, 0, 0);
    wxStaticBoxSizer* sizer_11 = new wxStaticBoxSizer(new wxStaticBox(this, -1, wxT("Endereço")), wxVERTICAL);
    wxBoxSizer* sizer_14 = new wxBoxSizer(wxHORIZONTAL);
    wxGridSizer* grid_sizer_17 = new wxGridSizer(2, 1, 0, 0);
    wxGridSizer* grid_sizer_16 = new wxGridSizer(2, 1, 0, 0);
    wxGridSizer* grid_sizer_15 = new wxGridSizer(2, 1, 0, 0);
    wxBoxSizer* sizer_13 = new wxBoxSizer(wxHORIZONTAL);
    wxGridSizer* grid_sizer_14 = new wxGridSizer(2, 1, 0, 0);
    wxGridSizer* grid_sizer_13 = new wxGridSizer(2, 1, 0, 0);
    wxBoxSizer* sizer_12 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_10 = new wxBoxSizer(wxHORIZONTAL);
    wxGridSizer* grid_sizer_12 = new wxGridSizer(2, 1, 0, 0);
    wxGridSizer* grid_sizer_11 = new wxGridSizer(2, 1, 0, 0);
    wxBoxSizer* sizer_6 = new wxBoxSizer(wxHORIZONTAL);
    wxGridSizer* grid_sizer_5 = new wxGridSizer(2, 1, 0, 0);
    wxGridSizer* grid_sizer_4 = new wxGridSizer(2, 1, 0, 0);
    wxBoxSizer* sizer_8 = new wxBoxSizer(wxHORIZONTAL);
    wxGridSizer* grid_sizer_8 = new wxGridSizer(2, 1, 0, 0);
    wxBoxSizer* sizer_7 = new wxBoxSizer(wxHORIZONTAL);
    wxGridSizer* grid_sizer_7 = new wxGridSizer(2, 1, 0, 0);
    grid_sizer_7->Add(labCodigo, 0, wxALIGN_BOTTOM, 0);
    grid_sizer_7->Add(edtCodigo, 0, 0, 0);
    sizer_7->Add(grid_sizer_7, 0, 0, 0);
    sizer_7->Add(btnNovo, 0, wxLEFT|wxALIGN_BOTTOM, 5);
    sizer_5->Add(sizer_7, 1, 0, 0);
    grid_sizer_8->Add(labDescricao, 0, wxALIGN_BOTTOM, 0);
    grid_sizer_8->Add(edtDescricao, 0, 0, 0);
    sizer_8->Add(grid_sizer_8, 0, 0, 0);
    sizer_5->Add(sizer_8, 1, wxEXPAND, 0);
    grid_sizer_4->Add(labEmail, 0, wxALIGN_BOTTOM, 0);
    grid_sizer_4->Add(edtEmail, 0, 0, 0);
    sizer_6->Add(grid_sizer_4, 0, 0, 0);
    grid_sizer_5->Add(labIdentidade, 0, wxALIGN_BOTTOM, 0);
    grid_sizer_5->Add(edtIdentidade, 0, 0, 0);
    sizer_6->Add(grid_sizer_5, 0, wxLEFT, 4);
    sizer_5->Add(sizer_6, 0, 0, 0);
    sizer_10->Add(rbSexo, 0, 0, 0);
    grid_sizer_11->Add(labTelefone, 0, wxALIGN_BOTTOM, 0);
    grid_sizer_11->Add(edtTelefone, 0, 0, 0);
    sizer_10->Add(grid_sizer_11, 1, wxLEFT|wxEXPAND, 4);
    grid_sizer_12->Add(labDtNasc, 0, wxALIGN_BOTTOM, 0);
    grid_sizer_12->Add(edtDtNasc, 0, 0, 0);
    sizer_10->Add(grid_sizer_12, 1, wxLEFT|wxEXPAND, 4);
    sizer_5->Add(sizer_10, 1, wxEXPAND, 0);
    sizer_12->Add(edtCodEndereco, 0, 0, 0);
    sizer_12->Add(btnPEndereco, 0, 0, 0);
    sizer_11->Add(sizer_12, 0, wxALL, 2);
    grid_sizer_13->Add(labLogradouro, 0, wxALIGN_BOTTOM, 0);
    grid_sizer_13->Add(edtLogradouro, 0, 0, 0);
    sizer_13->Add(grid_sizer_13, 0, 0, 0);
    grid_sizer_14->Add(labBairro, 0, wxALIGN_BOTTOM, 0);
    grid_sizer_14->Add(edtBairro, 0, 0, 0);
    sizer_13->Add(grid_sizer_14, 0, wxLEFT, 4);
    sizer_11->Add(sizer_13, 0, 0, 0);
    grid_sizer_15->Add(labCEP, 0, wxALIGN_BOTTOM, 0);
    grid_sizer_15->Add(edtCEP, 0, 0, 0);
    sizer_14->Add(grid_sizer_15, 0, 0, 0);
    grid_sizer_16->Add(labCidade, 0, wxALIGN_BOTTOM, 0);
    grid_sizer_16->Add(edtCidade, 0, 0, 0);
    sizer_14->Add(grid_sizer_16, 0, wxLEFT, 4);
    grid_sizer_17->Add(labEstado, 0, wxALIGN_BOTTOM, 0);
    grid_sizer_17->Add(edtEstado, 0, 0, 0);
    sizer_14->Add(grid_sizer_17, 0, wxLEFT, 4);
    sizer_11->Add(sizer_14, 1, 0, 0);
    sizer_5->Add(sizer_11, 0, 0, 0);
    grid_sizer_18->Add(labPais, 0, wxALIGN_BOTTOM, 0);
    grid_sizer_18->Add(edtCodPais, 0, 0, 0);
    sizer_15->Add(grid_sizer_18, 0, 0, 0);
    grid_sizer_20->Add(20, 20, 0, 0, 0);
    grid_sizer_20->Add(edtPais, 0, 0, 0);
    sizer_15->Add(grid_sizer_20, 0, wxLEFT, 2);
    grid_sizer_21->Add(20, 20, 0, 0, 0);
    grid_sizer_21->Add(btnPPais, 0, 0, 0);
    sizer_15->Add(grid_sizer_21, 0, 0, 0);
    sizer_5->Add(sizer_15, 0, 0, 0);
    grid_sizer_19->Add(labProfissao, 0, wxALIGN_BOTTOM, 0);
    grid_sizer_19->Add(edtCodProfissao, 0, 0, 0);
    sizer_16->Add(grid_sizer_19, 0, 0, 0);
    grid_sizer_22->Add(20, 20, 0, 0, 0);
    grid_sizer_22->Add(edtProfissao, 0, 0, 0);
    sizer_16->Add(grid_sizer_22, 0, wxLEFT, 2);
    grid_sizer_23->Add(20, 20, 0, 0, 0);
    grid_sizer_23->Add(btnPProfissao, 0, 0, 0);
    sizer_16->Add(grid_sizer_23, 0, 0, 0);
    sizer_5->Add(sizer_16, 0, 0, 0);
    sizer_3->Add(sizer_5, 0, 0, 0);
    sizer_4->Add(btnPesquisar, 0, wxALL|wxALIGN_RIGHT, 2);
    sizer_4->Add(btnAnterior, 0, wxALL|wxALIGN_RIGHT, 2);
    sizer_4->Add(btnProximo, 0, wxALL|wxALIGN_RIGHT, 2);
    sizer_3->Add(sizer_4, 1, 0, 0);
    sizer_1->Add(sizer_3, 1, wxALL|wxEXPAND, 4);
    sizer_2->Add(btnSalvar, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2);
    sizer_2->Add(btnExcluir, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2);
    sizer_2->Add(btnLimpar, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2);
    sizer_2->Add(btnFechar, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2);
    sizer_1->Add(sizer_2, 0, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT|wxALIGN_BOTTOM, 4);
    SetAutoLayout(true);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    sizer_1->SetSizeHints(this);
    // end wxGlade
}

