# generated by wxGlade 0.3.1 on Mon Dec 27 07:02:32 2004

from wxPython.wx import *

# begin wxGlade: dependencies
from wxPython.grid import *
# end wxGlade

class frmConsultas(wxDialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: frmConsultas.__init__
        kwds["style"] = wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxTHICK_FRAME
        wxDialog.__init__(self, *args, **kwds)
        self.labDescricao = wxStaticText(self, ID_FRMCONSULTAS_LABDESCRICAO, "Descrição:")
        self.edtDescricao = wxTextCtrl(self, ID_FRMCONSULTAS_EDTDESCRICAO, "")
        self.btnPesquisar = wxButton(self, ID_FRMCONSULTAS_BTNPESQUISAR, "&Pesquisar")
        self.gridConsulta = wxGrid(self, ID_FRMCONSULTAS_GRIDCONSULTA)
        self.labRegistro = wxStaticText(self, ID_FRMCONSULTAS_LABREGISTRO, "Registro 0 de 0")
        self.btnLimpar = wxButton(self, ID_FRMCONSULTAS_BTNLIMPAR, "&Limpar")
        self.btnFechar = wxButton(self, ID_FRMCONSULTAS_BTNFECHAR, "&Fechar")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: frmConsultas.__set_properties
        self.SetTitle("Consulta de")
        self.labDescricao.SetSize((51, 13))
        self.edtDescricao.SetSize((257, 21))
        self.btnPesquisar.SetSize((75, 25))
        self.gridConsulta.CreateGrid(1, 2)
        self.gridConsulta.SetColLabelSize(21)
        self.gridConsulta.EnableEditing(0)
        self.gridConsulta.SetSelectionMode(wxGrid.wxGridSelectRows)
        self.gridConsulta.SetColLabelValue(0, "Código")
        self.gridConsulta.SetColSize(0, 80)
        self.gridConsulta.SetColLabelValue(1, "Descrição")
        self.gridConsulta.SetColSize(1, 180)
        self.gridConsulta.SetSize((355, 125))
        self.labRegistro.SetSize((144, 13))
        self.btnLimpar.SetSize((75, 25))
        self.btnFechar.SetSize((75, 25))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: frmConsultas.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        gird_sizer_2 = wxGridSizer(1, 2, 0, 0)
        sizer_2 = wxBoxSizer(wxHORIZONTAL)
        sizer_3 = wxBoxSizer(wxHORIZONTAL)
        sizer_4 = wxBoxSizer(wxVERTICAL)
        grid_sizer_1 = wxGridSizer(2, 1, 0, 0)
        grid_sizer_1.Add(self.labDescricao, 0, wxALIGN_BOTTOM, 0)
        grid_sizer_1.Add(self.edtDescricao, 0, 0, 0)
        sizer_3.Add(grid_sizer_1, 0, wxALL, 2)
        sizer_4.Add(20, 20, 0, 0, 0)
        sizer_4.Add(self.btnPesquisar, 0, wxLEFT|wxTOP|wxBOTTOM, 5)
        sizer_3.Add(sizer_4, 0, 0, 0)
        sizer_1.Add(sizer_3, 0, wxALL, 4)
        sizer_1.Add(self.gridConsulta, 1, wxEXPAND, 0)
        gird_sizer_2.Add(self.labRegistro, 0, wxALL, 10)
        sizer_2.Add(self.btnLimpar, 0, wxALIGN_RIGHT|wxALIGN_BOTTOM, 8)
        sizer_2.Add(self.btnFechar, 0, wxLEFT|wxALIGN_RIGHT|wxALIGN_BOTTOM, 8)
        gird_sizer_2.Add(sizer_2, 1, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 4)
        sizer_1.Add(gird_sizer_2, 0, wxALL|wxEXPAND|wxALIGN_BOTTOM, 0)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class frmConsultas


