# generated by wxGlade 0.3.1 on Fri Jan 14 19:47:45 2005
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;
package frmCadClientes;

use Wx qw[:everything];
use base qw(Wx::Panel);
use strict;

# begin wxGlade: ::dependencies
# end wxGlade

sub new {
	my( $self, $parent, $id, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: frmCadClientes::new

	$style = wxTAB_TRAVERSAL 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $pos, $size, $style, $name );
	$self->{labCodigo} = Wx::StaticText->new($self, ID_FRMCADASTROS_LABCODIGO, "Código:", wxDefaultPosition, wxDefaultSize, );
	$self->{edtCodigo} = Wx::TextCtrl->new($self, ID_FRMCADASTROS_EDTCODIGO, "", wxDefaultPosition, wxDefaultSize, );
		$self->{btnNovo} = Wx::Button->new($self, ID_FRMCADASTROS_BTNNOVO, "&Novo");
	$self->{labDescricao} = Wx::StaticText->new($self, ID_FRMCADASTROS_LABDESCRICAO, "Logradouro: ", wxDefaultPosition, wxDefaultSize, );
	$self->{edtDescricao} = Wx::TextCtrl->new($self, ID_FRMCADASTROS_EDTDESCRICAO, "", wxDefaultPosition, wxDefaultSize, );
	$self->{labEmail} = Wx::StaticText->new($self, ID_FRMCADCLIENTES_LABEMAIL, "E-mail:", wxDefaultPosition, wxDefaultSize, );
	$self->{edtEmail} = Wx::TextCtrl->new($self, ID_FRMCADCLIENTES_EDTEMAIL, "", wxDefaultPosition, wxDefaultSize, );
	$self->{labIdentidade} = Wx::StaticText->new($self, ID_FRMCADCLIENTES_LABIDENTIDADE, "Identidade: ", wxDefaultPosition, wxDefaultSize, );
	$self->{edtIdentidade} = Wx::TextCtrl->new($self, ID_FRMCADCLIENTES_EDTIDENTIDADE, "", wxDefaultPosition, wxDefaultSize, );
	$self->{rbSexo} = Wx::RadioBox->new($self, ID_FRMCADCLIENTES_RBSEXO, "Sexo", wxDefaultPosition, wxDefaultSize, ["Masculino", "Feminino"], 2, wxRA_SPECIFY_COLS);
	$self->{labTelefone} = Wx::StaticText->new($self, ID_FRMCADCLIENTES_LABTELEFONE, "Telefone: ", wxDefaultPosition, wxDefaultSize, );
	$self->{edtTelefone} = Wx::TextCtrl->new($self, ID_FRMCADCLIENTES_EDTTELEFONE, "", wxDefaultPosition, wxDefaultSize, );
	$self->{labDtNasc} = Wx::StaticText->new($self, ID_FRMCADCLIENTES_LABDTNASC, "Dt. Nascimento", wxDefaultPosition, wxDefaultSize, );
	$self->{edtDtNasc} = Wx::TextCtrl->new($self, ID_FRMCADCLIENTES_EDTDTNASC, "", wxDefaultPosition, wxDefaultSize, );
	$self->{edtCodEndereco} = Wx::TextCtrl->new($self, ID_FRMCADCLIENTES_EDTCODENDERECO, "", wxDefaultPosition, wxDefaultSize, );
		$self->{btnPEndereco} = Wx::Button->new($self, ID_FRMCADCLIENTES_BTNPENDERECO, "...");
	$self->{labLogradouro} = Wx::StaticText->new($self, ID_FRMCADCLIENTES_LABLOGRADOURO, "Logradouro: ", wxDefaultPosition, wxDefaultSize, );
	$self->{edtLogradouro} = Wx::TextCtrl->new($self, ID_FRMCADCLIENTES_EDTLOGRADOURO, "", wxDefaultPosition, wxDefaultSize, );
	$self->{labBairro} = Wx::StaticText->new($self, ID_FRMCADCLIENTES_LABBAIRRO, "Bairro:", wxDefaultPosition, wxDefaultSize, );
	$self->{edtBairro} = Wx::TextCtrl->new($self, ID_FRMCADCLIENTES_EDTBAIRRO, "", wxDefaultPosition, wxDefaultSize, );
	$self->{labCEP} = Wx::StaticText->new($self, ID_FRMCADCLIENTES_LABCEP, "CEP:", wxDefaultPosition, wxDefaultSize, );
	$self->{edtCEP} = Wx::TextCtrl->new($self, ID_FRMCADCLIENTES_EDTCEP, "", wxDefaultPosition, wxDefaultSize, );
	$self->{labCidade} = Wx::StaticText->new($self, ID_FRMCADCLIENTES_LABCIDADE, "Cidade: ", wxDefaultPosition, wxDefaultSize, );
	$self->{edtCidade} = Wx::TextCtrl->new($self, ID_FRMCADCLIENTES_EDTCIDADE, "", wxDefaultPosition, wxDefaultSize, );
	$self->{labEstado} = Wx::StaticText->new($self, ID_FRMCADCLIENTES_LABESTADO, "Estado: ", wxDefaultPosition, wxDefaultSize, );
	$self->{edtEstado} = Wx::TextCtrl->new($self, ID_FRMCADCLIENTES_EDTESTADO, "", wxDefaultPosition, wxDefaultSize, );
	$self->{labPais} = Wx::StaticText->new($self, ID_FRMCADCLIENTES_LABPAIS, "País de origem: ", wxDefaultPosition, wxDefaultSize, );
	$self->{edtCodPais} = Wx::TextCtrl->new($self, ID_FRMCADCLIENTES_EDTCODPAIS, "", wxDefaultPosition, wxDefaultSize, );
	$self->{edtPais} = Wx::TextCtrl->new($self, ID_FRMCADCLIENTES_EDTPAIS, "", wxDefaultPosition, wxDefaultSize, );
		$self->{btnPPais} = Wx::Button->new($self, ID_FRMCADCLIENTES_BTNPPAIS, "...");
	$self->{labProfissao} = Wx::StaticText->new($self, ID_FRMCADCLIENTES_LABPROFISSAO, "Profissão: ", wxDefaultPosition, wxDefaultSize, );
	$self->{edtCodProfissao} = Wx::TextCtrl->new($self, ID_FRMCADCLIENTES_EDTCODPROFISSAO, "", wxDefaultPosition, wxDefaultSize, );
	$self->{edtProfissao} = Wx::TextCtrl->new($self, ID_FRMCADCLIENTES_EDTPROFISSAO, "", wxDefaultPosition, wxDefaultSize, );
		$self->{btnPProfissao} = Wx::Button->new($self, ID_FRMCADCLIENTES_BTNPPROFISSAO, "...");
		$self->{btnPesquisar} = Wx::Button->new($self, ID_FRMCADASTROS_BTNPESQUISAR, "&Pesquisar");
		$self->{btnAnterior} = Wx::Button->new($self, ID_FRMCADASTROS_BTNANTERIOR, "&Anterior");
		$self->{btnProximo} = Wx::Button->new($self, ID_FRMCADASTROS_BTNPROXIMO, "Próxi&mo");
		$self->{btnSalvar} = Wx::Button->new($self, ID_FRMCADASTROS_BTNSALVAR, "&Salvar");
		$self->{btnExcluir} = Wx::Button->new($self, ID_FRMCADASTROS_BTNEXCLUIR, "&Excluir");
		$self->{btnLimpar} = Wx::Button->new($self, ID_FRMCADASTROS_BTNLIMPAR, "&Limpar");
		$self->{btnFechar} = Wx::Button->new($self, ID_FRMCADASTROS_BTNFECHAR, "&Fechar");

	$self->__set_properties();
	$self->__do_layout();

	return $self;

# end wxGlade
}


sub __set_properties {
	my $self = shift;

# begin wxGlade: frmCadClientes::__set_properties

		$self->{labCodigo}->SetSize(36, 13);
		$self->{edtCodigo}->SetSize(121, 21);
		$self->{btnNovo}->SetSize(75, 25);
		$self->{labDescricao}->SetSize(57, 13);
		$self->{edtDescricao}->SetSize(264, 21);
		$self->{edtDescricao}->Enable(0);
		$self->{labEmail}->SetSize(40, 13);
		$self->{edtEmail}->SetSize(312, 21);
		$self->{edtEmail}->Enable(0);
		$self->{edtIdentidade}->SetSize(100, 21);
		$self->{edtIdentidade}->Enable(0);
		$self->{rbSexo}->SetSize(200, 44);
		$self->{rbSexo}->Enable(0);
	$self->{rbSexo}->SetSelection(0);
		$self->{labTelefone}->SetSize(48, 13);
		$self->{edtTelefone}->SetSize(104, 21);
		$self->{edtTelefone}->Enable(0);
		$self->{labDtNasc}->SetSize(73, 13);
		$self->{edtDtNasc}->SetSize(100, 21);
		$self->{edtDtNasc}->Enable(0);
		$self->{edtCodEndereco}->SetSize(88, 21);
		$self->{edtCodEndereco}->Enable(0);
		$self->{btnPEndereco}->SetSize(21, 21);
		$self->{btnPEndereco}->Enable(0);
		$self->{edtLogradouro}->SetSize(264, 21);
		$self->{edtLogradouro}->Enable(0);
		$self->{labBairro}->SetSize(48, 13);
		$self->{edtBairro}->SetSize(144, 21);
		$self->{edtBairro}->Enable(0);
		$self->{labCEP}->SetSize(40, 13);
		$self->{edtCEP}->SetSize(78, 21);
		$self->{edtCEP}->Enable(0);
		$self->{edtCidade}->SetSize(184, 21);
		$self->{edtCidade}->Enable(0);
		$self->{edtEstado}->SetSize(144, 21);
		$self->{edtEstado}->Enable(0);
		$self->{edtCodPais}->SetSize(78, 21);
		$self->{edtCodPais}->Enable(0);
		$self->{edtPais}->SetSize(240, 21);
		$self->{edtPais}->Enable(0);
		$self->{btnPPais}->SetSize(21, 21);
		$self->{btnPPais}->Enable(0);
		$self->{edtCodProfissao}->SetSize(78, 21);
		$self->{edtCodProfissao}->Enable(0);
		$self->{edtProfissao}->SetSize(240, 21);
		$self->{edtProfissao}->Enable(0);
		$self->{btnPProfissao}->SetSize(21, 21);
		$self->{btnPProfissao}->Enable(0);
		$self->{btnPesquisar}->SetSize(75, 25);
		$self->{btnAnterior}->SetSize(75, 25);
		$self->{btnAnterior}->Enable(0);
		$self->{btnProximo}->SetSize(75, 25);
		$self->{btnProximo}->Enable(0);
		$self->{btnSalvar}->SetSize(75, 25);
		$self->{btnSalvar}->Enable(0);
		$self->{btnExcluir}->SetSize(75, 25);
		$self->{btnExcluir}->Enable(0);
		$self->{btnLimpar}->SetSize(75, 25);
		$self->{btnFechar}->SetSize(75, 25);

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: frmCadClientes::__do_layout

		$self->{sizer_1} = Wx::BoxSizer->new(wxVERTICAL);
		$self->{sizer_2} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{sizer_3} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{sizer_4} = Wx::BoxSizer->new(wxVERTICAL);
		$self->{sizer_5} = Wx::BoxSizer->new(wxVERTICAL);
		$self->{sizer_16} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{grid_sizer_23} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_22} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_19} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{sizer_15} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{grid_sizer_21} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_20} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_18} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{sizer_11}= Wx::StaticBoxSizer->new(Wx::StaticBox->new($self, -1,"Endereço"), wxVERTICAL);
		$self->{sizer_14} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{grid_sizer_17} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_16} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_15} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{sizer_13} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{grid_sizer_14} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_13} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{sizer_12} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{sizer_10} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{grid_sizer_12} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_11} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{sizer_6} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{grid_sizer_5} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_4} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{sizer_8} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{grid_sizer_8} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{sizer_7} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{grid_sizer_7} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_7}->Add($self->{labCodigo}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_7}->Add($self->{edtCodigo}, 0, 0, 0);
		$self->{sizer_7}->Add($self->{grid_sizer_7}, 0, 0, 0);
		$self->{sizer_7}->Add($self->{btnNovo}, 0, wxLEFT|wxALIGN_BOTTOM, 5);
		$self->{sizer_5}->Add($self->{sizer_7}, 1, 0, 0);
		$self->{grid_sizer_8}->Add($self->{labDescricao}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_8}->Add($self->{edtDescricao}, 0, 0, 0);
		$self->{sizer_8}->Add($self->{grid_sizer_8}, 0, 0, 0);
		$self->{sizer_5}->Add($self->{sizer_8}, 1, wxEXPAND, 0);
		$self->{grid_sizer_4}->Add($self->{labEmail}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_4}->Add($self->{edtEmail}, 0, 0, 0);
		$self->{sizer_6}->Add($self->{grid_sizer_4}, 0, 0, 0);
		$self->{grid_sizer_5}->Add($self->{labIdentidade}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_5}->Add($self->{edtIdentidade}, 0, 0, 0);
		$self->{sizer_6}->Add($self->{grid_sizer_5}, 0, wxLEFT, 4);
		$self->{sizer_5}->Add($self->{sizer_6}, 0, 0, 0);
		$self->{sizer_10}->Add($self->{rbSexo}, 0, 0, 0);
		$self->{grid_sizer_11}->Add($self->{labTelefone}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_11}->Add($self->{edtTelefone}, 0, 0, 0);
		$self->{sizer_10}->Add($self->{grid_sizer_11}, 1, wxLEFT|wxEXPAND, 4);
		$self->{grid_sizer_12}->Add($self->{labDtNasc}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_12}->Add($self->{edtDtNasc}, 0, 0, 0);
		$self->{sizer_10}->Add($self->{grid_sizer_12}, 1, wxLEFT|wxEXPAND, 4);
		$self->{sizer_5}->Add($self->{sizer_10}, 1, wxEXPAND, 0);
		$self->{sizer_12}->Add($self->{edtCodEndereco}, 0, 0, 0);
		$self->{sizer_12}->Add($self->{btnPEndereco}, 0, 0, 0);
		$self->{sizer_11}->Add($self->{sizer_12}, 0, wxALL, 2);
		$self->{grid_sizer_13}->Add($self->{labLogradouro}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_13}->Add($self->{edtLogradouro}, 0, 0, 0);
		$self->{sizer_13}->Add($self->{grid_sizer_13}, 0, 0, 0);
		$self->{grid_sizer_14}->Add($self->{labBairro}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_14}->Add($self->{edtBairro}, 0, 0, 0);
		$self->{sizer_13}->Add($self->{grid_sizer_14}, 0, wxLEFT, 4);
		$self->{sizer_11}->Add($self->{sizer_13}, 0, 0, 0);
		$self->{grid_sizer_15}->Add($self->{labCEP}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_15}->Add($self->{edtCEP}, 0, 0, 0);
		$self->{sizer_14}->Add($self->{grid_sizer_15}, 0, 0, 0);
		$self->{grid_sizer_16}->Add($self->{labCidade}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_16}->Add($self->{edtCidade}, 0, 0, 0);
		$self->{sizer_14}->Add($self->{grid_sizer_16}, 0, wxLEFT, 4);
		$self->{grid_sizer_17}->Add($self->{labEstado}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_17}->Add($self->{edtEstado}, 0, 0, 0);
		$self->{sizer_14}->Add($self->{grid_sizer_17}, 0, wxLEFT, 4);
		$self->{sizer_11}->Add($self->{sizer_14}, 1, 0, 0);
		$self->{sizer_5}->Add($self->{sizer_11}, 0, 0, 0);
		$self->{grid_sizer_18}->Add($self->{labPais}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_18}->Add($self->{edtCodPais}, 0, 0, 0);
		$self->{sizer_15}->Add($self->{grid_sizer_18}, 0, 0, 0);
		$self->{grid_sizer_20}->Add(20, 20, 0, 0, 0);
		$self->{grid_sizer_20}->Add($self->{edtPais}, 0, 0, 0);
		$self->{sizer_15}->Add($self->{grid_sizer_20}, 0, wxLEFT, 2);
		$self->{grid_sizer_21}->Add(20, 20, 0, 0, 0);
		$self->{grid_sizer_21}->Add($self->{btnPPais}, 0, 0, 0);
		$self->{sizer_15}->Add($self->{grid_sizer_21}, 0, 0, 0);
		$self->{sizer_5}->Add($self->{sizer_15}, 0, 0, 0);
		$self->{grid_sizer_19}->Add($self->{labProfissao}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_19}->Add($self->{edtCodProfissao}, 0, 0, 0);
		$self->{sizer_16}->Add($self->{grid_sizer_19}, 0, 0, 0);
		$self->{grid_sizer_22}->Add(20, 20, 0, 0, 0);
		$self->{grid_sizer_22}->Add($self->{edtProfissao}, 0, 0, 0);
		$self->{sizer_16}->Add($self->{grid_sizer_22}, 0, wxLEFT, 2);
		$self->{grid_sizer_23}->Add(20, 20, 0, 0, 0);
		$self->{grid_sizer_23}->Add($self->{btnPProfissao}, 0, 0, 0);
		$self->{sizer_16}->Add($self->{grid_sizer_23}, 0, 0, 0);
		$self->{sizer_5}->Add($self->{sizer_16}, 0, 0, 0);
		$self->{sizer_3}->Add($self->{sizer_5}, 0, 0, 0);
		$self->{sizer_4}->Add($self->{btnPesquisar}, 0, wxALL|wxALIGN_RIGHT, 2);
		$self->{sizer_4}->Add($self->{btnAnterior}, 0, wxALL|wxALIGN_RIGHT, 2);
		$self->{sizer_4}->Add($self->{btnProximo}, 0, wxALL|wxALIGN_RIGHT, 2);
		$self->{sizer_3}->Add($self->{sizer_4}, 1, 0, 0);
		$self->{sizer_1}->Add($self->{sizer_3}, 1, wxALL|wxEXPAND, 4);
		$self->{sizer_2}->Add($self->{btnSalvar}, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2);
		$self->{sizer_2}->Add($self->{btnExcluir}, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2);
		$self->{sizer_2}->Add($self->{btnLimpar}, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2);
		$self->{sizer_2}->Add($self->{btnFechar}, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2);
		$self->{sizer_1}->Add($self->{sizer_2}, 0, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT|wxALIGN_BOTTOM, 4);
		$self->SetAutoLayout(1);
		$self->SetSizer($self->{sizer_1});
		$self->{sizer_1}->Fit($self);
		$self->{sizer_1}->SetSizeHints($self);

# end wxGlade
}

# end of class frmCadClientes

1;

