# generated by wxGlade 0.3.1 on Mon Dec 27 07:02:32 2004

from wxPython.wx import *

# begin wxGlade: dependencies
# end wxGlade

class frmCadastros(wxPanel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: frmCadastros.__init__
        kwds["style"] = wxTAB_TRAVERSAL
        wxPanel.__init__(self, *args, **kwds)
        self.labCodigo = wxStaticText(self, ID_FRMCADASTROS_LABCODIGO, "Código:")
        self.edtCodigo = wxTextCtrl(self, ID_FRMCADASTROS_EDTCODIGO, "")
        self.btnNovo = wxButton(self, ID_FRMCADASTROS_BTNNOVO, "&Novo")
        self.labDescricao = wxStaticText(self, ID_FRMCADASTROS_LABDESCRICAO, "Descrição:")
        self.edtDescricao = wxTextCtrl(self, ID_FRMCADASTROS_EDTDESCRICAO, "")
        self.btnPesquisar = wxButton(self, ID_FRMCADASTROS_BTNPESQUISAR, "&Pesquisar")
        self.btnAnterior = wxButton(self, ID_FRMCADASTROS_BTNANTERIOR, "&Anterior")
        self.btnProximo = wxButton(self, ID_FRMCADASTROS_BTNPROXIMO, "Próxi&mo")
        self.btnSalvar = wxButton(self, ID_FRMCADASTROS_BTNSALVAR, "&Salvar")
        self.btnExcluir = wxButton(self, ID_FRMCADASTROS_BTNEXCLUIR, "&Excluir")
        self.btnLimpar = wxButton(self, ID_FRMCADASTROS_BTNLIMPAR, "&Limpar")
        self.btnFechar = wxButton(self, ID_FRMCADASTROS_BTNFECHAR, "&Fechar")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: frmCadastros.__set_properties
        self.labCodigo.SetSize((121, 13))
        self.edtCodigo.SetSize((121, 21))
        self.btnNovo.SetSize((75, 25))
        self.labDescricao.SetSize((51, 13))
        self.edtDescricao.SetSize((217, 21))
        self.edtDescricao.Enable(0)
        self.btnPesquisar.SetSize((75, 25))
        self.btnAnterior.SetSize((75, 25))
        self.btnAnterior.Enable(0)
        self.btnProximo.SetSize((75, 25))
        self.btnProximo.Enable(0)
        self.btnSalvar.SetSize((75, 25))
        self.btnSalvar.Enable(0)
        self.btnExcluir.SetSize((75, 25))
        self.btnExcluir.Enable(0)
        self.btnLimpar.SetSize((75, 25))
        self.btnFechar.SetSize((75, 25))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: frmCadastros.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        sizer_2 = wxBoxSizer(wxHORIZONTAL)
        sizer_3 = wxBoxSizer(wxHORIZONTAL)
        sizer_4 = wxBoxSizer(wxVERTICAL)
        sizer_5 = wxBoxSizer(wxVERTICAL)
        grid_sizer_2 = wxGridSizer(2, 1, 0, 0)
        grid_sizer_1 = wxGridSizer(2, 2, 0, 1)
        grid_sizer_1.Add(self.labCodigo, 0, wxALIGN_BOTTOM, 0)
        grid_sizer_1.Add(20, 10, 0, 0, 0)
        grid_sizer_1.Add(self.edtCodigo, 0, 0, 0)
        grid_sizer_1.Add(self.btnNovo, 0, wxLEFT, 6)
        sizer_5.Add(grid_sizer_1, 0, 0, 0)
        grid_sizer_2.Add(self.labDescricao, 0, wxALIGN_BOTTOM, 0)
        grid_sizer_2.Add(self.edtDescricao, 0, 0, 2)
        sizer_5.Add(grid_sizer_2, 0, 0, 0)
        sizer_3.Add(sizer_5, 1, 0, 0)
        sizer_4.Add(self.btnPesquisar, 0, wxALL|wxALIGN_RIGHT, 2)
        sizer_4.Add(self.btnAnterior, 0, wxALL|wxALIGN_RIGHT, 2)
        sizer_4.Add(self.btnProximo, 0, wxALL|wxALIGN_RIGHT, 2)
        sizer_3.Add(sizer_4, 0, wxALIGN_RIGHT, 0)
        sizer_1.Add(sizer_3, 1, wxALL|wxEXPAND, 4)
        sizer_2.Add(self.btnSalvar, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2)
        sizer_2.Add(self.btnExcluir, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2)
        sizer_2.Add(self.btnLimpar, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2)
        sizer_2.Add(self.btnFechar, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2)
        sizer_1.Add(sizer_2, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 4)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        # end wxGlade

# end of class frmCadastros


