# generated by wxGlade 0.3.1 on Fri Jan 14 19:47:45 2005
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;
package frmConVendas;

use Wx qw[:everything];
use base qw(Wx::Panel);
use strict;

# begin wxGlade: ::dependencies
use Wx::Grid;
# end wxGlade

sub new {
	my( $self, $parent, $id, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: frmConVendas::new

	$style = wxTAB_TRAVERSAL 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $pos, $size, $style, $name );
	$self->{labDtHrVenda} = Wx::StaticText->new($self, ID_FRMCONVENDAS_LABDTHRVENDA, "Data/Hora Venda: ", wxDefaultPosition, wxDefaultSize, );
	$self->{edtDtHrVenda} = Wx::TextCtrl->new($self, ID_FRMCONVENDAS_EDTDTHRVENDA, "", wxDefaultPosition, wxDefaultSize, );
		$self->{btnPesquisar} = Wx::Button->new($self, ID_FRMCONVENDAS_BTNPESQUISAR, "&Pesquisar");
	$self->{labCPF} = Wx::StaticText->new($self, ID_FRMCONVENDAS_LABCPF, "CPF: ", wxDefaultPosition, wxDefaultSize, );
	$self->{edtCPF} = Wx::TextCtrl->new($self, ID_FRMCONVENDAS_EDTCPF, "", wxDefaultPosition, wxDefaultSize, );
	$self->{labCliente} = Wx::StaticText->new($self, ID_FRMCONVENDAS_LABCLIENTE, "Cliente: ", wxDefaultPosition, wxDefaultSize, );
	$self->{edtCliente} = Wx::TextCtrl->new($self, ID_FRMCONVENDAS_EDTCLIENTE, "", wxDefaultPosition, wxDefaultSize, );
		$self->{btnPCliente} = Wx::Button->new($self, ID_FRMCONVENDAS_BTNPCLIENTE, "...");
	$self->{labISBN} = Wx::StaticText->new($self, ID_FRMCONVENDAS_LABISBN, "ISBN: ", wxDefaultPosition, wxDefaultSize, );
	$self->{edtISBN} = Wx::TextCtrl->new($self, ID_FRMCONVENDAS_EDTISBN, "", wxDefaultPosition, wxDefaultSize, );
	$self->{labLivro} = Wx::StaticText->new($self, ID_FRMCONVENDAS_LABLIVRO, "Livro: ", wxDefaultPosition, wxDefaultSize, );
	$self->{edtLivro} = Wx::TextCtrl->new($self, ID_FRMCONVENDAS_EDTLIVRO, "", wxDefaultPosition, wxDefaultSize, );
		$self->{btnPLivro} = Wx::Button->new($self, ID_FRMCONVENDAS_BTNPLIVRO, "...");
	$self->{gridVendas} = Wx::Grid->new($self, ID_FRMCONVENDAS_GRIDVENDAS);
	$self->{labRegistro} = Wx::StaticText->new($self, ID_FRMCONVENDAS_LABREGISTRO, "Registro 0 de 0", wxDefaultPosition, wxDefaultSize, );
	$self->{labPrecoTotal} = Wx::StaticText->new($self, ID_FRMCONVENDAS_LABPRECOTOTAL, "Preço Total: ", wxDefaultPosition, wxDefaultSize, );
	$self->{edtPrecoTotal} = Wx::TextCtrl->new($self, ID_FRMCONVENDAS_EDTPRECOTOTAL, "", wxDefaultPosition, wxDefaultSize, );
		$self->{btnLimpar} = Wx::Button->new($self, ID_FRMCONVENDAS_BTNLIMPAR, "&Limpar");
		$self->{btnFechar} = Wx::Button->new($self, ID_FRMCONVENDAS_BTNFECHAR, "&Fechar");

	$self->__set_properties();
	$self->__do_layout();

	return $self;

# end wxGlade
}


sub __set_properties {
	my $self = shift;

# begin wxGlade: frmConVendas::__set_properties

		$self->{labDtHrVenda}->SetSize(91, 13);
		$self->{edtDtHrVenda}->SetSize(128, 21);
		$self->{btnPesquisar}->SetSize(75, 25);
		$self->{edtCPF}->SetSize(128, 21);
		$self->{edtCliente}->SetSize(306, 21);
		$self->{edtCliente}->Enable(0);
		$self->{btnPCliente}->SetSize(21, 21);
		$self->{edtISBN}->SetSize(128, 21);
		$self->{edtLivro}->SetSize(306, 21);
		$self->{edtLivro}->Enable(0);
		$self->{btnPLivro}->SetSize(21, 21);
	$self->{gridVendas}->CreateGrid(10, 6);
	$self->{gridVendas}->SetColLabelSize(21);
	$self->{gridVendas}->EnableEditing(0);
	$self->{gridVendas}->SetSelectionMode(wxGridSelectRows);
		$self->{gridVendas}->SetSize(467, 137);
		$self->{labRegistro}->SetSize(144, 13);
		$self->{labPrecoTotal}->SetSize(61,13);
		$self->{edtPrecoTotal}->SetSize(127, 21);
		$self->{edtPrecoTotal}->Enable(0);
		$self->{btnLimpar}->SetSize(75, 25);
		$self->{btnFechar}->SetSize(75, 25);

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: frmConVendas::__do_layout

		$self->{sizer_1} = Wx::BoxSizer->new(wxVERTICAL);
		$self->{sizer_6} = Wx::BoxSizer->new(wxVERTICAL);
		$self->{sizer_22} = Wx::GridSizer->new(1, 2, 0, 0);
		$self->{sizer_23} = Wx::BoxSizer->new(wxVERTICAL);
		$self->{sizer_8} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{sizer_7} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{sizer_24} = Wx::BoxSizer->new(wxVERTICAL);
		$self->{sizer_4} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{grid_sizer_8} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_6} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_5} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{sizer_3} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{grid_sizer_4} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_3} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_2} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{sizer_2} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{grid_sizer_1} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_1}->Add($self->{labDtHrVenda}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_1}->Add($self->{edtDtHrVenda}, 0, 0, 0);
		$self->{sizer_2}->Add($self->{grid_sizer_1}, 0, wxLEFT, 2);
		$self->{sizer_2}->Add($self->{btnPesquisar}, 0, wxLEFT|wxTOP|wxALIGN_BOTTOM, 10);
		$self->{sizer_1}->Add($self->{sizer_2}, 0, 0, 0);
		$self->{grid_sizer_2}->Add($self->{labCPF}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_2}->Add($self->{edtCPF}, 0, 0, 0);
		$self->{sizer_3}->Add($self->{grid_sizer_2}, 0, wxLEFT, 2);
		$self->{grid_sizer_3}->Add($self->{labCliente}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_3}->Add($self->{edtCliente}, 0, 0, 0);
		$self->{sizer_3}->Add($self->{grid_sizer_3}, 0, wxLEFT, 2);
		$self->{grid_sizer_4}->Add(20, 20, 0, 0, 0);
		$self->{grid_sizer_4}->Add($self->{btnPCliente}, 0, 0, 0);
		$self->{sizer_3}->Add($self->{grid_sizer_4}, 0, 0, 0);
		$self->{sizer_1}->Add($self->{sizer_3}, 0, 0, 0);
		$self->{grid_sizer_5}->Add($self->{labISBN}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_5}->Add($self->{edtISBN}, 0, 0, 0);
		$self->{sizer_4}->Add($self->{grid_sizer_5}, 0, wxLEFT, 2);
		$self->{grid_sizer_6}->Add($self->{labLivro}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_6}->Add($self->{edtLivro}, 0, 0, 0);
		$self->{sizer_4}->Add($self->{grid_sizer_6}, 0, wxLEFT, 2);
		$self->{grid_sizer_8}->Add(20, 20, 0, 0, 0);
		$self->{grid_sizer_8}->Add($self->{btnPLivro}, 0, 0, 0);
		$self->{sizer_4}->Add($self->{grid_sizer_8}, 0, 0, 0);
		$self->{sizer_1}->Add($self->{sizer_4}, 0, 0, 0);
		$self->{sizer_1}->Add($self->{gridVendas}, 1, wxALL|wxEXPAND, 2);
		$self->{sizer_24}->Add($self->{labRegistro}, 0, wxALL, 4);
		$self->{sizer_24}->Add(20, 20, 0, 0, 0);
		$self->{sizer_22}->Add($self->{sizer_24}, 0, 0, 0);
		$self->{sizer_7}->Add($self->{labPrecoTotal}, 0, wxALL, 2);
		$self->{sizer_7}->Add($self->{edtPrecoTotal}, 0, wxALL, 2);
		$self->{sizer_23}->Add($self->{sizer_7}, 0, wxALL|wxALIGN_RIGHT, 2);
		$self->{sizer_8}->Add($self->{btnLimpar}, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2);
		$self->{sizer_8}->Add($self->{btnFechar}, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2);
		$self->{sizer_23}->Add($self->{sizer_8}, 0, wxALL|wxALIGN_RIGHT, 2);
		$self->{sizer_22}->Add($self->{sizer_23}, 1, wxALIGN_RIGHT|wxALIGN_BOTTOM, 0);
		$self->{sizer_6}->Add($self->{sizer_22}, 0, wxEXPAND, 0);
		$self->{sizer_1}->Add($self->{sizer_6}, 0, wxEXPAND, 0);
		$self->SetAutoLayout(1);
		$self->SetSizer($self->{sizer_1});
		$self->{sizer_1}->Fit($self);
		$self->{sizer_1}->SetSizeHints($self);

# end wxGlade
}

# end of class frmConVendas

1;

