# generated by wxGlade 0.3.1 on Mon Dec 27 07:02:32 2004

from wxPython.wx import *

# begin wxGlade: dependencies
from wxPython.grid import *
# end wxGlade

class frmConVendas(wxPanel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: frmConVendas.__init__
        kwds["style"] = wxTAB_TRAVERSAL
        wxPanel.__init__(self, *args, **kwds)
        self.labDtHrVenda = wxStaticText(self, ID_FRMCONVENDAS_LABDTHRVENDA, "Data/Hora Venda: ")
        self.edtDtHrVenda = wxTextCtrl(self, ID_FRMCONVENDAS_EDTDTHRVENDA, "")
        self.btnPesquisar = wxButton(self, ID_FRMCONVENDAS_BTNPESQUISAR, "&Pesquisar")
        self.labCPF = wxStaticText(self, ID_FRMCONVENDAS_LABCPF, "CPF: ")
        self.edtCPF = wxTextCtrl(self, ID_FRMCONVENDAS_EDTCPF, "")
        self.labCliente = wxStaticText(self, ID_FRMCONVENDAS_LABCLIENTE, "Cliente: ")
        self.edtCliente = wxTextCtrl(self, ID_FRMCONVENDAS_EDTCLIENTE, "")
        self.btnPCliente = wxButton(self, ID_FRMCONVENDAS_BTNPCLIENTE, "...")
        self.labISBN = wxStaticText(self, ID_FRMCONVENDAS_LABISBN, "ISBN: ")
        self.edtISBN = wxTextCtrl(self, ID_FRMCONVENDAS_EDTISBN, "")
        self.labLivro = wxStaticText(self, ID_FRMCONVENDAS_LABLIVRO, "Livro: ")
        self.edtLivro = wxTextCtrl(self, ID_FRMCONVENDAS_EDTLIVRO, "")
        self.btnPLivro = wxButton(self, ID_FRMCONVENDAS_BTNPLIVRO, "...")
        self.gridVendas = wxGrid(self, ID_FRMCONVENDAS_GRIDVENDAS)
        self.labRegistro = wxStaticText(self, ID_FRMCONVENDAS_LABREGISTRO, "Registro 0 de 0")
        self.labPrecoTotal = wxStaticText(self, ID_FRMCONVENDAS_LABPRECOTOTAL, "Preço Total: ")
        self.edtPrecoTotal = wxTextCtrl(self, ID_FRMCONVENDAS_EDTPRECOTOTAL, "")
        self.btnLimpar = wxButton(self, ID_FRMCONVENDAS_BTNLIMPAR, "&Limpar")
        self.btnFechar = wxButton(self, ID_FRMCONVENDAS_BTNFECHAR, "&Fechar")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: frmConVendas.__set_properties
        self.labDtHrVenda.SetSize((91, 13))
        self.edtDtHrVenda.SetSize((128, 21))
        self.btnPesquisar.SetSize((75, 25))
        self.edtCPF.SetSize((128, 21))
        self.edtCliente.SetSize((306, 21))
        self.edtCliente.Enable(0)
        self.btnPCliente.SetSize((21, 21))
        self.edtISBN.SetSize((128, 21))
        self.edtLivro.SetSize((306, 21))
        self.edtLivro.Enable(0)
        self.btnPLivro.SetSize((21, 21))
        self.gridVendas.CreateGrid(10, 6)
        self.gridVendas.SetColLabelSize(21)
        self.gridVendas.EnableEditing(0)
        self.gridVendas.SetSelectionMode(wxGrid.wxGridSelectRows)
        self.gridVendas.SetSize((467, 137))
        self.labRegistro.SetSize((144, 13))
        self.labPrecoTotal.SetSize((61,13))
        self.edtPrecoTotal.SetSize((127, 21))
        self.edtPrecoTotal.Enable(0)
        self.btnLimpar.SetSize((75, 25))
        self.btnFechar.SetSize((75, 25))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: frmConVendas.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        sizer_6 = wxBoxSizer(wxVERTICAL)
        sizer_22 = wxGridSizer(1, 2, 0, 0)
        sizer_23 = wxBoxSizer(wxVERTICAL)
        sizer_8 = wxBoxSizer(wxHORIZONTAL)
        sizer_7 = wxBoxSizer(wxHORIZONTAL)
        sizer_24 = wxBoxSizer(wxVERTICAL)
        sizer_4 = wxBoxSizer(wxHORIZONTAL)
        grid_sizer_8 = wxGridSizer(2, 1, 0, 0)
        grid_sizer_6 = wxGridSizer(2, 1, 0, 0)
        grid_sizer_5 = wxGridSizer(2, 1, 0, 0)
        sizer_3 = wxBoxSizer(wxHORIZONTAL)
        grid_sizer_4 = wxGridSizer(2, 1, 0, 0)
        grid_sizer_3 = wxGridSizer(2, 1, 0, 0)
        grid_sizer_2 = wxGridSizer(2, 1, 0, 0)
        sizer_2 = wxBoxSizer(wxHORIZONTAL)
        grid_sizer_1 = wxGridSizer(2, 1, 0, 0)
        grid_sizer_1.Add(self.labDtHrVenda, 0, wxALIGN_BOTTOM, 0)
        grid_sizer_1.Add(self.edtDtHrVenda, 0, 0, 0)
        sizer_2.Add(grid_sizer_1, 0, wxLEFT, 2)
        sizer_2.Add(self.btnPesquisar, 0, wxLEFT|wxTOP|wxALIGN_BOTTOM, 10)
        sizer_1.Add(sizer_2, 0, 0, 0)
        grid_sizer_2.Add(self.labCPF, 0, wxALIGN_BOTTOM, 0)
        grid_sizer_2.Add(self.edtCPF, 0, 0, 0)
        sizer_3.Add(grid_sizer_2, 0, wxLEFT, 2)
        grid_sizer_3.Add(self.labCliente, 0, wxALIGN_BOTTOM, 0)
        grid_sizer_3.Add(self.edtCliente, 0, 0, 0)
        sizer_3.Add(grid_sizer_3, 0, wxLEFT, 2)
        grid_sizer_4.Add(20, 20, 0, 0, 0)
        grid_sizer_4.Add(self.btnPCliente, 0, 0, 0)
        sizer_3.Add(grid_sizer_4, 0, 0, 0)
        sizer_1.Add(sizer_3, 0, 0, 0)
        grid_sizer_5.Add(self.labISBN, 0, wxALIGN_BOTTOM, 0)
        grid_sizer_5.Add(self.edtISBN, 0, 0, 0)
        sizer_4.Add(grid_sizer_5, 0, wxLEFT, 2)
        grid_sizer_6.Add(self.labLivro, 0, wxALIGN_BOTTOM, 0)
        grid_sizer_6.Add(self.edtLivro, 0, 0, 0)
        sizer_4.Add(grid_sizer_6, 0, wxLEFT, 2)
        grid_sizer_8.Add(20, 20, 0, 0, 0)
        grid_sizer_8.Add(self.btnPLivro, 0, 0, 0)
        sizer_4.Add(grid_sizer_8, 0, 0, 0)
        sizer_1.Add(sizer_4, 0, 0, 0)
        sizer_1.Add(self.gridVendas, 1, wxALL|wxEXPAND, 2)
        sizer_24.Add(self.labRegistro, 0, wxALL, 4)
        sizer_24.Add(20, 20, 0, 0, 0)
        sizer_22.Add(sizer_24, 0, 0, 0)
        sizer_7.Add(self.labPrecoTotal, 0, wxALL, 2)
        sizer_7.Add(self.edtPrecoTotal, 0, wxALL, 2)
        sizer_23.Add(sizer_7, 0, wxALL|wxALIGN_RIGHT, 2)
        sizer_8.Add(self.btnLimpar, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2)
        sizer_8.Add(self.btnFechar, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2)
        sizer_23.Add(sizer_8, 0, wxALL|wxALIGN_RIGHT, 2)
        sizer_22.Add(sizer_23, 1, wxALIGN_RIGHT|wxALIGN_BOTTOM, 0)
        sizer_6.Add(sizer_22, 0, wxEXPAND, 0)
        sizer_1.Add(sizer_6, 0, wxEXPAND, 0)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        # end wxGlade

# end of class frmConVendas


