# generated by wxGlade 0.3.1 on Fri Jan 14 19:47:45 2005
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;
package frmFilha;

use Wx qw[:everything];
use base qw(Wx::MDIChildFrame);
use strict;

# begin wxGlade: ::dependencies
# end wxGlade

sub new {
	my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$title  = ""                 unless defined $title;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: frmFilha::new

	$style = wxDEFAULT_FRAME_STYLE 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );

	$self->__set_properties();
	$self->__do_layout();

	return $self;

# end wxGlade
}


sub __set_properties {
	my $self = shift;

# begin wxGlade: frmFilha::__set_properties

		$self->SetTitle("Cadastro de");
		my $icon = Wx::Icon->new();
		$icon->CopyFromBitmap(Wx::Bitmap->new("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\livrus.xpm", wxBITMAP_TYPE_ANY));
		$self->SetIcon($icon);
		$self->SetSize(400, 300);
		$self->SetBackgroundColour(Wx::SystemSettings::GetColour(wxSYS_COLOUR_BTNFACE));

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: frmFilha::__do_layout

		$self->Layout();

# end wxGlade
}

# end of class frmFilha

1;

