# generated by wxGlade 0.3.1 on Mon Dec 27 07:02:32 2004

from wxPython.wx import *

# begin wxGlade: dependencies
# end wxGlade

class frmFilha(wxMDIChildFrame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: frmFilha.__init__
        kwds["style"] = wxDEFAULT_FRAME_STYLE
        wxMDIChildFrame.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: frmFilha.__set_properties
        self.SetTitle("Cadastro de")
        _icon = wxEmptyIcon()
        _icon.CopyFromBitmap(wxBitmap("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\livrus.xpm", wxBITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetSize((400, 300))
        self.SetBackgroundColour(wxSystemSettings_GetSystemColour(wxSYS_COLOUR_BTNFACE))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: frmFilha.__do_layout
        self.Layout()
        # end wxGlade

# end of class frmFilha


