# generated by wxGlade 0.3.1 on Fri Jan 14 19:47:45 2005
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;
package frmLogin;

use Wx qw[:everything];
use base qw(Wx::Dialog);
use strict;

# begin wxGlade: ::dependencies
# end wxGlade

sub new {
	my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$title  = ""                 unless defined $title;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: frmLogin::new

	$style = wxDEFAULT_DIALOG_STYLE 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
	$self->{bmpLogin} = Wx::StaticBitmap->new($self, ID_FRMLOGIN_BMPLOGIN, Wx::Bitmap->new("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\login.xpm", wxBITMAP_TYPE_ANY),);
	$self->{labLogin} = Wx::StaticText->new($self, ID_FRMLOGIN_LABLOGIN, "Login:", wxDefaultPosition, wxDefaultSize, );
	$self->{edtLogin} = Wx::TextCtrl->new($self, ID_FRMLOGIN_EDTLOGIN, "", wxDefaultPosition, wxDefaultSize, );
	$self->{labSenha} = Wx::StaticText->new($self, ID_FRMLOGIN_LABSENHA, "Senha:", wxDefaultPosition, wxDefaultSize, );
	$self->{edtSenha} = Wx::TextCtrl->new($self, ID_FRMLOGIN_EDTSENHA, "", wxDefaultPosition, wxDefaultSize, );
		$self->{btnLogin} = Wx::Button->new($self, ID_FRMLOGIN_BTNLOGIN, "&Login");
		$self->{btnCancelar} = Wx::Button->new($self, ID_FRMLOGIN_BTNCANCELAR, "&Cancelar");

	$self->__set_properties();
	$self->__do_layout();

	return $self;

# end wxGlade
}


sub __set_properties {
	my $self = shift;

# begin wxGlade: frmLogin::__set_properties

	$self->SetTitle("Login do Sistema");
		$self->{edtLogin}->SetSize(80, 21);
		$self->{edtSenha}->SetSize(80, 21);
		$self->{btnLogin}->SetSize(75, 25);
	$self->{btnLogin}->SetDefault();
		$self->{btnCancelar}->SetSize(75, 25);

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: frmLogin::__do_layout

		$self->{sizer_1} = Wx::BoxSizer->new(wxVERTICAL);
		$self->{sizer_4} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{sizer_2} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{sizer_3} = Wx::BoxSizer->new(wxVERTICAL);
		$self->{sizer_2}->Add($self->{bmpLogin}, 0, wxALL, 6);
		$self->{sizer_3}->Add($self->{labLogin}, 0, wxALL|wxALIGN_BOTTOM, 2);
		$self->{sizer_3}->Add($self->{edtLogin}, 0, wxALL, 2);
		$self->{sizer_3}->Add($self->{labSenha}, 0, wxALL|wxALIGN_BOTTOM, 2);
		$self->{sizer_3}->Add($self->{edtSenha}, 0, wxALL, 2);
		$self->{sizer_2}->Add($self->{sizer_3}, 0, wxALL, 6);
		$self->{sizer_1}->Add($self->{sizer_2}, 0, 0, 3);
		$self->{sizer_4}->Add($self->{btnLogin}, 0, wxLEFT|wxTOP|wxBOTTOM|wxALIGN_BOTTOM, 10);
		$self->{sizer_4}->Add($self->{btnCancelar}, 0, wxALL|wxALIGN_BOTTOM, 10);
		$self->{sizer_1}->Add($self->{sizer_4}, 0, wxALL|wxALIGN_CENTER_HORIZONTAL, 1);
		$self->SetAutoLayout(1);
		$self->SetSizer($self->{sizer_1});
		$self->{sizer_1}->Fit($self);
		$self->{sizer_1}->SetSizeHints($self);
	$self->Layout();
	$self->Centre();

# end wxGlade
}

# end of class frmLogin

1;

