# generated by wxGlade 0.3.1 on Mon Dec 27 07:02:32 2004

from wxPython.wx import *

# begin wxGlade: dependencies
# end wxGlade

class frmPrincipal(wxFrame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: frmPrincipal.__init__
        kwds["style"] = wxDEFAULT_FRAME_STYLE
        wxFrame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.barraMenu = wxMenuBar()
        self.SetMenuBar(self.barraMenu)
        self.mnuCadastros = wxMenu()
        self.mnuCadastros.Append(MNU_CAD_ASSUNTOS, "&Assuntos", "Cadastros de Assuntos", wxITEM_NORMAL)
        self.barraMenu.Append(self.mnuCadastros, "&Cadastros")
        self.mnuPesquisas = wxMenu()
        self.mnuPesquisas.Append(MNU_CON_ASSUNTOS, "&Assuntos", "Consulta de Assuntos", wxITEM_NORMAL)
        self.barraMenu.Append(self.mnuPesquisas, "&Pesquisas")
        self.mnuVendas = wxMenu()
        self.mnuVendas.Append(MNU_VEN_VENDERLIVROS, "&Vender Livros", "Vender Livros", wxITEM_NORMAL)
        self.barraMenu.Append(self.mnuVendas, "&Vendas")
        self.mnuOpcoes = wxMenu()
        self.mnuOpcoes.Append(MNU_OP_SOBRE, "&Sobre", "Sobre o Sistema", wxITEM_NORMAL)
        self.mnuOpcoes.Append(MNU_OP_SAIR, "Sa&ir", "Sair do Sistema", wxITEM_NORMAL)
        self.barraMenu.Append(self.mnuOpcoes, "&Opções")
        # Menu Bar end
        
        # Tool Bar
        self.barraFerra = wxToolBar(self, -1)
        self.SetToolBar(self.barraFerra)
        self.barraFerra.AddLabelTool(MNU_CAD_CLIENTES, "", wxBitmap("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\cliente.xpm", wxBITMAP_TYPE_ANY), wxBitmap("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\dcliente.xpm", wxBITMAP_TYPE_ANY), wxITEM_NORMAL, "", "")
        self.barraFerra.AddLabelTool(MNU_CAD_LIVROS, "", wxBitmap("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\livro.xpm", wxBITMAP_TYPE_ANY), wxBitmap("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\dlivro.xpm", wxBITMAP_TYPE_ANY), wxITEM_NORMAL, "", "")
        self.barraFerra.AddLabelTool(MNU_VEN_VENDERLIVROS, "", wxBitmap("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\livros.xpm", wxBITMAP_TYPE_ANY), wxBitmap("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\dlivros.xpm", wxBITMAP_TYPE_ANY), wxITEM_NORMAL, "", "")
        self.barraFerra.AddSeparator()
        self.barraFerra.AddLabelTool(MNU_OP_SOBRE, "", wxBitmap("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\sobre.xpm", wxBITMAP_TYPE_ANY), wxBitmap("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\dsobre.xpm", wxBITMAP_TYPE_ANY), wxITEM_NORMAL, "", "")
        self.barraFerra.AddLabelTool(MNU_OP_SAIR, "", wxBitmap("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\sair.xpm", wxBITMAP_TYPE_ANY), wxBitmap("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\dsair.xpm", wxBITMAP_TYPE_ANY), wxITEM_NORMAL, "", "")
        # Tool Bar end
        self.barraStatus = self.CreateStatusBar(2)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: frmPrincipal.__set_properties
        self.SetTitle("Livrus Virtus")
        _icon = wxEmptyIcon()
        _icon.CopyFromBitmap(wxBitmap("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\livrus.xpm", wxBITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.barraFerra.Realize()
        self.barraStatus.SetStatusWidths([100, -1])
        # statusbar fields
        barraStatus_fields = ["Usuário: ", ""]
        for i in range(len(barraStatus_fields)):
            self.barraStatus.SetStatusText(barraStatus_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: frmPrincipal.__do_layout
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class frmPrincipal


