# generated by wxGlade 0.3.1 on Fri Jan 14 19:47:45 2005
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;
package frmPrincipal;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;
require resource;

# begin wxGlade: ::dependencies
# end wxGlade

sub new {
	my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$title  = ""                 unless defined $title;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: frmPrincipal::new

	$style = wxDEFAULT_FRAME_STYLE 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
	

	# Menu Bar  

	$self->{barraMenu} = Wx::MenuBar->new();
	$self->SetMenuBar($self->{barraMenu});
	my $wxglade_tmp_menu;
	$self->{mnuCadastros} = Wx::Menu->new();
	$self->{mnuCadastros}->Append($Resource::MNU_CAD_ASSUNTOS, "&Assuntos", "Cadastros de Assuntos");
	$self->{mnuCadastros}->Append($Resource::MNU_CAD_AUTORES, "A&utores", "Cadastros de Autores");
	$self->{mnuCadastros}->Append($Resource::MNU_CAD_EDITORAS, "&Editoras", "Cadastros de Editoras");
	$self->{mnuCadastros}->Append($Resource::MNU_CAD_ENDERECOS, "E&ndereços", "Cadastro de Endereços");
	$self->{mnuCadastros}->Append($Resource::MNU_CAD_IDIOMAS, "&Idiomas", "Cadastro de Idiomas");
	$self->{mnuCadastros}->Append($Resource::MNU_CAD_PAISES, "&Países", "Cadastro de Países");
	$self->{mnuCadastros}->Append($Resource::MNU_CAD_PROFISSOES, "P&rofissões", "Cadastro de Profissões");
	$self->{mnuCadastros}->AppendSeparator();
	$self->{mnuCadastros}->Append($Resource::MNU_CAD_CLIENTES, "&Clientes", "Cadastro de Clientes");
	$self->{mnuCadastros}->Append($Resource::MNU_CAD_LIVROS, "&Livros", "Cadastro de Livros");
	$self->{barraMenu}->Append($self->{mnuCadastros}, "&Cadastros");
	$self->{mnuPesquisas} = Wx::Menu->new();
	$self->{mnuPesquisas}->Append($Resource::MNU_CON_ASSUNTOS, "&Assuntos", "Consulta de Assuntos");
	$self->{mnuPesquisas}->Append($Resource::MNU_CON_AUTORES, "A&utores", "Consultas de Autores");
	$self->{mnuPesquisas}->Append($Resource::MNU_CON_EDITORAS, "&Editoras", "Consulta de Editoras");
	$self->{mnuPesquisas}->Append($Resource::MNU_CON_ENDERECOS, "E&ndereços", "Consulta de Endereços");
	$self->{mnuPesquisas}->Append($Resource::MNU_CON_IDIOMAS, "&Idiomas", "Consulta de Idiomas");
	$self->{mnuPesquisas}->Append($Resource::MNU_CON_PAISES, "&Países", "Consulta de Países");
	$self->{mnuPesquisas}->Append($Resource::MNU_CON_PROFISSOES, "P&rofissões", "Consulta de Profissões");
	$self->{mnuPesquisas}->AppendSeparator();
	$self->{mnuPesquisas}->Append($Resource::MNU_CON_CLIENTES, "&Clientes", "Consulta de Clientes");
	$self->{mnuPesquisas}->Append($Resource::MNU_CON_LIVROS, "&Livros", "Consulta de Livros");
	$self->{barraMenu}->Append($self->{mnuPesquisas}, "&Pesquisas");
	$self->{mnuVendas} = Wx::Menu->new();
	$self->{mnuVendas}->Append($Resource::MNU_VEN_VENDERLIVROS, "&Vender Livros", "Vender Livros");
	$self->{mnuVendas}->Append($Resource::MNU_VEN_VENDASREALIZADAS, "Vendas &Realizadas", "Vendas Realizadas");
	$self->{barraMenu}->Append($self->{mnuVendas}, "&Vendas");
	$self->{mnuOpcoes} = Wx::Menu->new();
	$self->{mnuOpcoes}->Append($Resource::MNU_OP_ALTERARSENHA, "&Alterar Senha", "Alteração de Senha");
	$self->{mnuOpcoes}->AppendSeparator();
	$self->{mnuOpcoes}->Append($Resource::MNU_OP_SOBRE, "&Sobre", "Sobre o Sistema");
	$self->{mnuOpcoes}->Append($Resource::MNU_OP_SAIR, "Sa&ir\tCtrl-S", "Sair do Sistema");
	$self->{barraMenu}->Append($self->{mnuOpcoes}, "&Opções");
	
# Menu Bar end

		$self->{barraStatus} = $self->CreateStatusBar(2);
	
# Tool Bar
	$self->{barraFerra} = Wx::ToolBar->new($self, -1, wxDefaultPosition, wxDefaultSize, );
	$self->SetToolBar($self->{barraFerra});
	$self->{barraFerra}->AddTool($Resource::MNU_CAD_CLIENTES, "", Wx::Bitmap->new("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\cliente.xpm", wxBITMAP_TYPE_ANY), Wx::Bitmap->new("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\dcliente.xpm", wxBITMAP_TYPE_ANY), wxITEM_NORMAL, "", "");
	$self->{barraFerra}->AddTool($Resource::MNU_CAD_LIVROS, "", Wx::Bitmap->new("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\livro.xpm", wxBITMAP_TYPE_ANY), Wx::Bitmap->new("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\dlivro.xpm", wxBITMAP_TYPE_ANY), wxITEM_NORMAL, "", "");
	$self->{barraFerra}->AddTool($Resource::MNU_VEN_VENDERLIVROS, "", Wx::Bitmap->new("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\livros.xpm", wxBITMAP_TYPE_ANY), Wx::Bitmap->new("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\dlivros.xpm", wxBITMAP_TYPE_ANY), wxITEM_NORMAL, "", "");
	$self->{barraFerra}->AddSeparator();
	$self->{barraFerra}->AddTool($Resource::MNU_OP_SOBRE, "", Wx::Bitmap->new("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\sobre.xpm", wxBITMAP_TYPE_ANY), Wx::Bitmap->new("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\dsobre.xpm", wxBITMAP_TYPE_ANY), wxITEM_NORMAL, "", "");
	$self->{barraFerra}->AddTool($Resource::MNU_OP_SAIR, "", Wx::Bitmap->new("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\sair.xpm", wxBITMAP_TYPE_ANY), Wx::Bitmap->new("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\dsair.xpm", wxBITMAP_TYPE_ANY), wxITEM_NORMAL, "", "");
	# Tool Bar end

	$self->__set_properties();
	$self->__do_layout();

	return $self;

# end wxGlade
}


sub __set_properties {
	my $self = shift;

# begin wxGlade: frmPrincipal::__set_properties

		$self->SetTitle("Livrus Virtus");
		my $icon = Wx::Icon->new();
		$icon->CopyFromBitmap(Wx::Bitmap->new("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\livrus.xpm", wxBITMAP_TYPE_ANY));
		$self->SetIcon($icon);
		$self->{barraStatus}->SetStatusWidths(100,-1);
	
	my( @barraStatus_fields ) = (
		"Usuário: ",
		""
	);

		if( @barraStatus_fields ) {
			$self->{barraStatus}->SetStatusText($barraStatus_fields[$_], $_) 	
			for 0 .. $#barraStatus_fields ;
	}
	$self->{barraFerra}->Realize();

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: frmPrincipal::__do_layout

		$self->Layout();
		$self->Centre();

# end wxGlade
}

# end of class frmPrincipal

1;

