# generated by wxGlade 0.3.1 on Mon Dec 27 07:02:32 2004

from wxPython.wx import *

# begin wxGlade: dependencies
# end wxGlade

class frmSobre(wxDialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: frmSobre.__init__
        kwds["style"] = wxDEFAULT_DIALOG_STYLE
        wxDialog.__init__(self, *args, **kwds)
        self.labBmp = wxStaticBitmap(self, ID_FRMSOBRE_LABBMP, wxBitmap("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\livrusvirtus.xpm", wxBITMAP_TYPE_ANY))
        self.labVersao = wxStaticText(self, ID_FRMSOBRE_LABVERSAO, "Versão: 1.0.0")
        self.labDireitos = wxStaticText(self, ID_FRMSOBRE_LABDIREITOS, "Todos os diretos reservados para: Henrique F. de Souza")
        self.labSistema = wxStaticText(self, ID_FRMSOBRE_LABSISTEMA, "Sistema integrante do projeto Livrus Virtus, versão programada no Visual C++ 6.0 em wxWindows.", style=wxALIGN_CENTRE)
        self.btnOk = wxButton(self, ID_FRMSOBRE_BTNOK, "&Ok")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: frmSobre.__set_properties
        self.SetTitle("Sobre o Sistema")
        self.labSistema.SetSize((240, 29))
        self.btnOk.SetSize((75, 25))
        self.btnOk.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: frmSobre.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        sizer_2 = wxStaticBoxSizer(wxStaticBox(self, -1, ""), wxVERTICAL)
        sizer_2.Add(self.labBmp, 0, wxALIGN_CENTER_HORIZONTAL, 0)
        sizer_2.Add(self.labVersao, 0, wxALL|wxALIGN_RIGHT, 2)
        sizer_2.Add(self.labDireitos, 0, wxALL, 2)
        sizer_2.Add(self.labSistema, 0, wxALL|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 2)
        sizer_1.Add(sizer_2, 1, wxALL|wxEXPAND, 6)
        sizer_1.Add(self.btnOk, 0, wxALL|wxALIGN_CENTER_HORIZONTAL, 4)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class frmSobre


