# generated by wxGlade 0.3.1 on Mon Dec 27 07:02:32 2004

from wxPython.wx import *

# begin wxGlade: dependencies
# end wxGlade

class frmSplash(wxDialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: frmSplash.__init__
        kwds["style"] = wxDEFAULT_DIALOG_STYLE
        wxDialog.__init__(self, *args, **kwds)
        self.labBmp = wxStaticBitmap(self, -1, wxBitmap("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\livrusvirtus.xpm", wxBITMAP_TYPE_ANY))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: frmSplash.__set_properties
        self.SetTitle("Splash")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: frmSplash.__do_layout
        sizer_1 = wxBoxSizer(wxHORIZONTAL)
        sizer_1.Add(self.labBmp, 0, wxALL|wxEXPAND, 2)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class frmSplash


