# generated by wxGlade 0.3.1 on Fri Jan 14 19:47:45 2005
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;
package frmSplash;

use Wx qw[:everything];
use base qw(Wx::Dialog);
use strict;

# begin wxGlade: ::dependencies
# end wxGlade

sub new {
	my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$title  = ""                 unless defined $title;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: frmSplash::new

	$style = wxDEFAULT_DIALOG_STYLE 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
	$self->{labBmp} = Wx::StaticBitmap->new($self, -1, Wx::Bitmap->new("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\livrusvirtus.xpm", wxBITMAP_TYPE_ANY),);

	$self->__set_properties();
	$self->__do_layout();

	return $self;

# end wxGlade
}


sub __set_properties {
	my $self = shift;

# begin wxGlade: frmSplash::__set_properties

	$self->SetTitle("Splash");

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: frmSplash::__do_layout

		$self->{sizer_1} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{sizer_1}->Add($self->{labBmp}, 0, wxALL|wxEXPAND, 2);
		$self->SetAutoLayout(1);
		$self->SetSizer($self->{sizer_1});
		$self->{sizer_1}->Fit($self);
		$self->{sizer_1}->SetSizeHints($self);
	$self->Layout();
	$self->Centre();

# end wxGlade
}

# end of class frmSplash

1;

