// -*- C++ -*- generated by wxGlade 0.3.1 on Mon Dec 27 07:02:26 2004

#include "frmSobre.h"


frmSobre::frmSobre(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: frmSobre::frmSobre
    labBmp = new wxStaticBitmap(this, ID_FRMSOBRE_LABBMP, wxBitmap(wxT("C:\\LivrusVirtus\\VCPP6\\wxWin\\wxODBC\\xpms\\livrusvirtus.xpm"), wxBITMAP_TYPE_ANY));
    labVersao = new wxStaticText(this, ID_FRMSOBRE_LABVERSAO, wxT("Versão: 1.0.0"));
    labDireitos = new wxStaticText(this, ID_FRMSOBRE_LABDIREITOS, wxT("Todos os diretos reservados para: Henrique F. de Souza"));
    labSistema = new wxStaticText(this, ID_FRMSOBRE_LABSISTEMA, wxT("Sistema integrante do projeto Livrus Virtus, versão programada no Visual C++ 6.0 em wxWindows."), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTRE);
    btnOk = new wxButton(this, ID_FRMSOBRE_BTNOK, wxT("&Ok"));

    set_properties();
    do_layout();
    // end wxGlade
}


void frmSobre::set_properties()
{
    // begin wxGlade: frmSobre::set_properties
    SetTitle(wxT("Sobre o Sistema"));
    labSistema->SetSize(wxSize(240, 29));
    btnOk->SetSize(wxSize(75, 25));
    btnOk->SetDefault();
    // end wxGlade
}


void frmSobre::do_layout()
{
    // begin wxGlade: frmSobre::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* sizer_2 = new wxStaticBoxSizer(new wxStaticBox(this, -1, wxT("")), wxVERTICAL);
    sizer_2->Add(labBmp, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    sizer_2->Add(labVersao, 0, wxALL|wxALIGN_RIGHT, 2);
    sizer_2->Add(labDireitos, 0, wxALL, 2);
    sizer_2->Add(labSistema, 0, wxALL|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 2);
    sizer_1->Add(sizer_2, 1, wxALL|wxEXPAND, 6);
    sizer_1->Add(btnOk, 0, wxALL|wxALIGN_CENTER_HORIZONTAL, 4);
    SetAutoLayout(true);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    sizer_1->SetSizeHints(this);
    Layout();
    Centre();
    // end wxGlade
}

