// -*- C++ -*- generated by wxGlade 0.3.1 on Mon Dec 27 07:02:26 2004

#include <wx/wx.h>
#include <wx/image.h>

#ifndef FRMSPLASH_H
#define FRMSPLASH_H

// begin wxGlade: dependencies
// end wxGlade


class frmSplash: public wxDialog {
public:
    // begin wxGlade: frmSplash::ids
    // end wxGlade

    frmSplash(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: frmSplash::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: frmSplash::attributes
    wxStaticBitmap* labBmp;
    // end wxGlade
};


#endif // FRMSPLASH_H
