# generated by wxGlade 0.3.1 on Fri Jan 14 19:47:45 2005
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;
package frmVenderLivros;

use Wx qw[:everything];
use base qw(Wx::Panel);
use strict;

# begin wxGlade: ::dependencies
# end wxGlade

sub new {
	my( $self, $parent, $id, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: frmVenderLivros::new

	$style = wxTAB_TRAVERSAL 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $pos, $size, $style, $name );
	$self->{labDtHrVenda} = Wx::StaticText->new($self, ID_FRMVENDERLIVROS_LABDTHRVENDA, "Data/Hora Venda: ", wxDefaultPosition, wxDefaultSize, );
	$self->{edtDtHrVenda} = Wx::TextCtrl->new($self, ID_FRMVENDERLIVROS_EDTDTHRVENDA, "", wxDefaultPosition, wxDefaultSize, );
	$self->{labCodigo} = Wx::StaticText->new($self, ID_FRMCADASTROS_LABCODIGO, "CPF: ", wxDefaultPosition, wxDefaultSize, );
	$self->{edtCodigo} = Wx::TextCtrl->new($self, ID_FRMCADASTROS_EDTCODIGO, "", wxDefaultPosition, wxDefaultSize, );
	$self->{labDescricao} = Wx::StaticText->new($self, ID_FRMCADASTROS_LABDESCRICAO, "Cliente: ", wxDefaultPosition, wxDefaultSize, );
	$self->{edtDescricao} = Wx::TextCtrl->new($self, ID_FRMCADASTROS_EDTDESCRICAO, "", wxDefaultPosition, wxDefaultSize, );
		$self->{btnPCliente} = Wx::Button->new($self, ID_FRMVENDERLIVROS_BTNPCLIENTE, "...");
	$self->{labISBN} = Wx::StaticText->new($self, ID_FRMVENDERLIVROS_LABISBN, "ISBN: ", wxDefaultPosition, wxDefaultSize, );
	$self->{edtISBN} = Wx::TextCtrl->new($self, ID_FRMVENDERLIVROS_EDTISBN, "", wxDefaultPosition, wxDefaultSize, );
	$self->{labLivro} = Wx::StaticText->new($self, ID_FRMVENDERLIVROS_LABLIVRO, "Livro: ", wxDefaultPosition, wxDefaultSize, );
	$self->{edtLivro} = Wx::TextCtrl->new($self, ID_FRMVENDERLIVROS_EDTLIVRO, "", wxDefaultPosition, wxDefaultSize, );
		$self->{btnAdLivros} = Wx::Button->new($self, ID_FRMVENDERLIVROS_BTNADLIVROS, "+");
		$self->{btnPLivro} = Wx::Button->new($self, ID_FRMVENDERLIVROS_BTNPLIVRO, "...");
	$self->{labLivros} = Wx::StaticText->new($self, ID_FRMVENDERLIVROS_LABLIVROS, "Livros para vender: ", wxDefaultPosition, wxDefaultSize, );
	$self->{lstLivros} = Wx::ListBox->new($self, ID_FRMVENDERLIVROS_LSTLIVROS, wxDefaultPosition, wxDefaultSize, ["choice 1"], );
	$self->{labPrecoTotal} = Wx::StaticText->new($self, ID_FRMVENDERLIVROS_LABPRECOTOTAL, "Preço Total: ", wxDefaultPosition, wxDefaultSize, );
	$self->{edtPrecoTotal} = Wx::TextCtrl->new($self, ID_FRMVENDERLIVROS_EDTPRECOTOTAL, "", wxDefaultPosition, wxDefaultSize, );
		$self->{btnVender} = Wx::Button->new($self, ID_FRMVENDERLIVROS_BTNVENDER, "&Vender");
		$self->{btnLimpar} = Wx::Button->new($self, ID_FRMVENDERLIVROS_BTNLIMPAR, "&Limpar");
		$self->{btnFechar} = Wx::Button->new($self, ID_FRMVENDERLIVROS_BTNFECHAR, "&Fechar");

	$self->__set_properties();
	$self->__do_layout();

	return $self;

# end wxGlade
}


sub __set_properties {
	my $self = shift;

# begin wxGlade: frmVenderLivros::__set_properties

		$self->{labDtHrVenda}->SetSize(91, 13);
		$self->{edtDtHrVenda}->SetSize(128, 21);
		$self->{edtDtHrVenda}->Enable(0);
		$self->{edtCodigo}->SetSize(128, 21);
		$self->{edtDescricao}->SetSize(306, 21);
		$self->{edtDescricao}->Enable(0);
		$self->{btnPCliente}->SetSize(21, 21);
		$self->{edtISBN}->SetSize(128, 21);
		$self->{edtLivro}->SetSize(282, 21);
		$self->{edtLivro}->Enable(0);
		$self->{btnAdLivros}->SetSize(21, 21);
		$self->{btnPLivro}->SetSize(21, 21);
	$self->{lstLivros}->SetSelection(0);
		$self->{edtPrecoTotal}->SetSize(127, 21);
		$self->{edtPrecoTotal}->Enable(0);
		$self->{btnVender}->SetSize(75, 25);
		$self->{btnLimpar}->SetSize(75, 25);
		$self->{btnFechar}->SetSize(75, 25);

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: frmVenderLivros::__do_layout

		$self->{sizer_1} = Wx::BoxSizer->new(wxVERTICAL);
		$self->{sizer_6} = Wx::BoxSizer->new(wxVERTICAL);
		$self->{sizer_8} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{sizer_7} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{sizer_5} = Wx::BoxSizer->new(wxVERTICAL);
		$self->{sizer_4} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{grid_sizer_8} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_7} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_6} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_5} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{sizer_3} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{grid_sizer_4} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_3} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_2} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{sizer_2} = Wx::BoxSizer->new(wxHORIZONTAL);
		$self->{grid_sizer_1} = Wx::GridSizer->new(2, 1, 0, 0);
		$self->{grid_sizer_1}->Add($self->{labDtHrVenda}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_1}->Add($self->{edtDtHrVenda}, 0, 0, 0);
		$self->{sizer_2}->Add($self->{grid_sizer_1}, 0, wxLEFT, 2);
		$self->{sizer_2}->Add(20, 20, 0, 0, 0);
		$self->{sizer_1}->Add($self->{sizer_2}, 0, 0, 0);
		$self->{grid_sizer_2}->Add($self->{labCodigo}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_2}->Add($self->{edtCodigo}, 0, 0, 0);
		$self->{sizer_3}->Add($self->{grid_sizer_2}, 0, wxLEFT, 2);
		$self->{grid_sizer_3}->Add($self->{labDescricao}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_3}->Add($self->{edtDescricao}, 0, 0, 0);
		$self->{sizer_3}->Add($self->{grid_sizer_3}, 0, wxLEFT, 2);
		$self->{grid_sizer_4}->Add(20, 20, 0, 0, 0);
		$self->{grid_sizer_4}->Add($self->{btnPCliente}, 0, 0, 0);
		$self->{sizer_3}->Add($self->{grid_sizer_4}, 0, 0, 0);
		$self->{sizer_1}->Add($self->{sizer_3}, 0, 0, 0);
		$self->{grid_sizer_5}->Add($self->{labISBN}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_5}->Add($self->{edtISBN}, 0, 0, 0);
		$self->{sizer_4}->Add($self->{grid_sizer_5}, 0, wxLEFT, 2);
		$self->{grid_sizer_6}->Add($self->{labLivro}, 0, wxALIGN_BOTTOM, 0);
		$self->{grid_sizer_6}->Add($self->{edtLivro}, 0, 0, 0);
		$self->{sizer_4}->Add($self->{grid_sizer_6}, 0, wxLEFT, 2);
		$self->{grid_sizer_7}->Add(20, 20, 0, 0, 0);
		$self->{grid_sizer_7}->Add($self->{btnAdLivros}, 0, 0, 0);
		$self->{sizer_4}->Add($self->{grid_sizer_7}, 1, wxEXPAND, 0);
		$self->{grid_sizer_8}->Add(20, 20, 0, 0, 0);
		$self->{grid_sizer_8}->Add($self->{btnPLivro}, 0, 0, 0);
		$self->{sizer_4}->Add($self->{grid_sizer_8}, 0, 0, 0);
		$self->{sizer_1}->Add($self->{sizer_4}, 0, 0, 0);
		$self->{sizer_5}->Add($self->{labLivros}, 0, wxALIGN_BOTTOM, 0);
		$self->{sizer_5}->Add($self->{lstLivros}, 1, wxALL|wxEXPAND, 1);
		$self->{sizer_1}->Add($self->{sizer_5}, 1, wxEXPAND, 0);
		$self->{sizer_7}->Add($self->{labPrecoTotal}, 0, wxALL, 2);
		$self->{sizer_7}->Add($self->{edtPrecoTotal}, 0, wxALL, 2);
		$self->{sizer_6}->Add($self->{sizer_7}, 0, wxALL|wxALIGN_RIGHT, 2);
		$self->{sizer_8}->Add($self->{btnVender}, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2);
		$self->{sizer_8}->Add($self->{btnLimpar}, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2);
		$self->{sizer_8}->Add($self->{btnFechar}, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2);
		$self->{sizer_6}->Add($self->{sizer_8}, 0, wxALL, 2);
		$self->{sizer_1}->Add($self->{sizer_6}, 0, wxALIGN_RIGHT|wxALIGN_BOTTOM, 0);
		$self->SetAutoLayout(1);
		$self->SetSizer($self->{sizer_1});
		$self->{sizer_1}->Fit($self);
		$self->{sizer_1}->SetSizeHints($self);

# end wxGlade
}

# end of class frmVenderLivros

1;

