# generated by wxGlade 0.3.1 on Mon Dec 27 07:02:32 2004

from wxPython.wx import *

# begin wxGlade: dependencies
# end wxGlade

class frmVenderLivros(wxPanel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: frmVenderLivros.__init__
        kwds["style"] = wxTAB_TRAVERSAL
        wxPanel.__init__(self, *args, **kwds)
        self.labDtHrVenda = wxStaticText(self, ID_FRMVENDERLIVROS_LABDTHRVENDA, "Data/Hora Venda: ")
        self.edtDtHrVenda = wxTextCtrl(self, ID_FRMVENDERLIVROS_EDTDTHRVENDA, "")
        self.labCodigo = wxStaticText(self, ID_FRMCADASTROS_LABCODIGO, "CPF: ")
        self.edtCodigo = wxTextCtrl(self, ID_FRMCADASTROS_EDTCODIGO, "")
        self.labDescricao = wxStaticText(self, ID_FRMCADASTROS_LABDESCRICAO, "Cliente: ")
        self.edtDescricao = wxTextCtrl(self, ID_FRMCADASTROS_EDTDESCRICAO, "")
        self.btnPCliente = wxButton(self, ID_FRMVENDERLIVROS_BTNPCLIENTE, "...")
        self.labISBN = wxStaticText(self, ID_FRMVENDERLIVROS_LABISBN, "ISBN: ")
        self.edtISBN = wxTextCtrl(self, ID_FRMVENDERLIVROS_EDTISBN, "")
        self.labLivro = wxStaticText(self, ID_FRMVENDERLIVROS_LABLIVRO, "Livro: ")
        self.edtLivro = wxTextCtrl(self, ID_FRMVENDERLIVROS_EDTLIVRO, "")
        self.btnAdLivros = wxButton(self, ID_FRMVENDERLIVROS_BTNADLIVROS, "+")
        self.btnPLivro = wxButton(self, ID_FRMVENDERLIVROS_BTNPLIVRO, "...")
        self.labLivros = wxStaticText(self, ID_FRMVENDERLIVROS_LABLIVROS, "Livros para vender: ")
        self.lstLivros = wxListBox(self, ID_FRMVENDERLIVROS_LSTLIVROS, choices=["choice 1"])
        self.labPrecoTotal = wxStaticText(self, ID_FRMVENDERLIVROS_LABPRECOTOTAL, "Preço Total: ")
        self.edtPrecoTotal = wxTextCtrl(self, ID_FRMVENDERLIVROS_EDTPRECOTOTAL, "")
        self.btnVender = wxButton(self, ID_FRMVENDERLIVROS_BTNVENDER, "&Vender")
        self.btnLimpar = wxButton(self, ID_FRMVENDERLIVROS_BTNLIMPAR, "&Limpar")
        self.btnFechar = wxButton(self, ID_FRMVENDERLIVROS_BTNFECHAR, "&Fechar")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: frmVenderLivros.__set_properties
        self.labDtHrVenda.SetSize((91, 13))
        self.edtDtHrVenda.SetSize((128, 21))
        self.edtDtHrVenda.Enable(0)
        self.edtCodigo.SetSize((128, 21))
        self.edtDescricao.SetSize((306, 21))
        self.edtDescricao.Enable(0)
        self.btnPCliente.SetSize((21, 21))
        self.edtISBN.SetSize((128, 21))
        self.edtLivro.SetSize((282, 21))
        self.edtLivro.Enable(0)
        self.btnAdLivros.SetSize((21, 21))
        self.btnPLivro.SetSize((21, 21))
        self.lstLivros.SetSelection(0)
        self.edtPrecoTotal.SetSize((127, 21))
        self.edtPrecoTotal.Enable(0)
        self.btnVender.SetSize((75, 25))
        self.btnLimpar.SetSize((75, 25))
        self.btnFechar.SetSize((75, 25))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: frmVenderLivros.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        sizer_6 = wxBoxSizer(wxVERTICAL)
        sizer_8 = wxBoxSizer(wxHORIZONTAL)
        sizer_7 = wxBoxSizer(wxHORIZONTAL)
        sizer_5 = wxBoxSizer(wxVERTICAL)
        sizer_4 = wxBoxSizer(wxHORIZONTAL)
        grid_sizer_8 = wxGridSizer(2, 1, 0, 0)
        grid_sizer_7 = wxGridSizer(2, 1, 0, 0)
        grid_sizer_6 = wxGridSizer(2, 1, 0, 0)
        grid_sizer_5 = wxGridSizer(2, 1, 0, 0)
        sizer_3 = wxBoxSizer(wxHORIZONTAL)
        grid_sizer_4 = wxGridSizer(2, 1, 0, 0)
        grid_sizer_3 = wxGridSizer(2, 1, 0, 0)
        grid_sizer_2 = wxGridSizer(2, 1, 0, 0)
        sizer_2 = wxBoxSizer(wxHORIZONTAL)
        grid_sizer_1 = wxGridSizer(2, 1, 0, 0)
        grid_sizer_1.Add(self.labDtHrVenda, 0, wxALIGN_BOTTOM, 0)
        grid_sizer_1.Add(self.edtDtHrVenda, 0, 0, 0)
        sizer_2.Add(grid_sizer_1, 0, wxLEFT, 2)
        sizer_2.Add(20, 20, 0, 0, 0)
        sizer_1.Add(sizer_2, 0, 0, 0)
        grid_sizer_2.Add(self.labCodigo, 0, wxALIGN_BOTTOM, 0)
        grid_sizer_2.Add(self.edtCodigo, 0, 0, 0)
        sizer_3.Add(grid_sizer_2, 0, wxLEFT, 2)
        grid_sizer_3.Add(self.labDescricao, 0, wxALIGN_BOTTOM, 0)
        grid_sizer_3.Add(self.edtDescricao, 0, 0, 0)
        sizer_3.Add(grid_sizer_3, 0, wxLEFT, 2)
        grid_sizer_4.Add(20, 20, 0, 0, 0)
        grid_sizer_4.Add(self.btnPCliente, 0, 0, 0)
        sizer_3.Add(grid_sizer_4, 0, 0, 0)
        sizer_1.Add(sizer_3, 0, 0, 0)
        grid_sizer_5.Add(self.labISBN, 0, wxALIGN_BOTTOM, 0)
        grid_sizer_5.Add(self.edtISBN, 0, 0, 0)
        sizer_4.Add(grid_sizer_5, 0, wxLEFT, 2)
        grid_sizer_6.Add(self.labLivro, 0, wxALIGN_BOTTOM, 0)
        grid_sizer_6.Add(self.edtLivro, 0, 0, 0)
        sizer_4.Add(grid_sizer_6, 0, wxLEFT, 2)
        grid_sizer_7.Add(20, 20, 0, 0, 0)
        grid_sizer_7.Add(self.btnAdLivros, 0, 0, 0)
        sizer_4.Add(grid_sizer_7, 1, wxEXPAND, 0)
        grid_sizer_8.Add(20, 20, 0, 0, 0)
        grid_sizer_8.Add(self.btnPLivro, 0, 0, 0)
        sizer_4.Add(grid_sizer_8, 0, 0, 0)
        sizer_1.Add(sizer_4, 0, 0, 0)
        sizer_5.Add(self.labLivros, 0, wxALIGN_BOTTOM, 0)
        sizer_5.Add(self.lstLivros, 1, wxALL|wxEXPAND, 1)
        sizer_1.Add(sizer_5, 1, wxEXPAND, 0)
        sizer_7.Add(self.labPrecoTotal, 0, wxALL, 2)
        sizer_7.Add(self.edtPrecoTotal, 0, wxALL, 2)
        sizer_6.Add(sizer_7, 0, wxALL|wxALIGN_RIGHT, 2)
        sizer_8.Add(self.btnVender, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2)
        sizer_8.Add(self.btnLimpar, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2)
        sizer_8.Add(self.btnFechar, 0, wxALL|wxALIGN_RIGHT|wxALIGN_BOTTOM, 2)
        sizer_6.Add(sizer_8, 0, wxALL, 2)
        sizer_1.Add(sizer_6, 0, wxALIGN_RIGHT|wxALIGN_BOTTOM, 0)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        # end wxGlade

# end of class frmVenderLivros


