#!/usr/bin/env python
# generated by wxGlade 0.3.1 on Mon Dec 27 07:02:32 2004

from wxPython.wx import *
from frmPrincipal import frmPrincipal

if __name__ == "__main__":
    LivrusApp = wxPySimpleApp(0)
    wxInitAllImageHandlers()
    frmPrincipal = frmPrincipal(None, -1, "")
    LivrusApp.SetTopWindow(frmPrincipal)
    frmPrincipal.Show(1)
    LivrusApp.MainLoop()
