#!/usr/bin/perl -w -- 
# generated by wxGlade 0.3.1 on Fri Jan 14 19:47:45 2005
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;
1;

package main;

use frmPrincipal;


unless(caller){
	local *Wx::App::OnInit = sub{1};
	my $LivrusApp = Wx::App->new();
	Wx::InitAllImageHandlers();

	my $frmPrincipal = frmPrincipal->new();

	$LivrusApp->SetTopWindow($frmPrincipal);
	$frmPrincipal->Show(1);
	$LivrusApp->MainLoop();
}
