# Generated automatically from Makefile.in by config.pl.
# KDE tags expanded automatically by am_edit - $Revision: 1.1 $ 
# Makefile.in generated automatically by automake 1.4-p6 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999, 2001 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

####### kdevelop will overwrite this part!!! (begin)##########


SHELL = /bin/sh

srcdir = .
top_srcdir = ..
VPATH = .
prefix = /usr/local
exec_prefix = ${prefix}
#>- 
bindir = ${exec_prefix}/bin
#>+ 3
DEPDIR = .deps

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/plivrus
pkglibdir = $(libdir)/plivrus
pkgincludedir = $(includedir)/plivrus

top_builddir = ..

ACLOCAL = aclocal-1.4
AUTOCONF = autoconf
AUTOMAKE = automake-1.4
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c -p
INSTALL_PROGRAM = ${INSTALL} $(INSTALL_STRIP_FLAG) $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i386-linux
build_triplet = i386-pc-linux-gnu
host_alias = i386-linux
host_triplet = i386-pc-linux-gnu
target_alias = i386-linux
target_triplet = i386-pc-linux-gnu
ARTSCCONFIG = @ARTSCCONFIG@
AS = @AS@
AUTODIRS = 
CC = gcc
CONF_FILES =  $(top_srcdir)/configure.in.in
CPP = cpp
CXX = g++
CXXCPP = g++ -E
DCOPIDL = @DCOPIDL@
DCOPIDL2CPP = @DCOPIDL2CPP@
DCOP_DEPENDENCIES = @DCOP_DEPENDENCIES@
DLLTOOL = @DLLTOOL@
DPMSINC = @DPMSINC@
DPMSLIB = @DPMSLIB@
EXEEXT = 
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
GLINC = @GLINC@
GLLIB = @GLLIB@
GMSGFMT = @GMSGFMT@
IDL = @IDL@
IDL_DEPENDENCIES = @IDL_DEPENDENCIES@
JAR = @JAR@
JAVAC = @JAVAC@
JAVAH = @JAVAH@
JVMLIBS = @JVMLIBS@
KDECONFIG = @KDECONFIG@
KDE_CXXFLAGS = 
KDE_EXTRA_RPATH = @KDE_EXTRA_RPATH@
KDE_INCLUDES = @KDE_INCLUDES@
KDE_LDFLAGS = @KDE_LDFLAGS@
KDE_MT_LDFLAGS = @KDE_MT_LDFLAGS@
KDE_MT_LIBS = @KDE_MT_LIBS@
KDE_PLUGIN = -avoid-version -module -no-undefined $(KDE_RPATH) $(KDE_MT_LDFLAGS)
KDE_RPATH = @KDE_RPATH@
KDE_USE_CLOSURE_FALSE = #
KDE_USE_CLOSURE_TRUE = 
KDE_USE_FINAL_FALSE = 
KDE_USE_FINAL_TRUE = #
KDE_XSL_STYLESHEET = @KDE_XSL_STYLESHEET@
LEX = @LEX@
LEXLIB = @LEXLIB@
LIBCOMPAT = @LIBCOMPAT@
LIBCRYPT = @LIBCRYPT@
LIBDL = @LIBDL@
LIBGEN = @LIBGEN@
LIBJPEG = @LIBJPEG@
LIBMICO = @LIBMICO@
LIBOBJS = @LIBOBJS@
LIBPNG = @LIBPNG@
LIBPTHREAD = @LIBPTHREAD@
LIBPYTHON = @LIBPYTHON@
LIBQIMGIO = @LIBQIMGIO@
LIBRESOLV = @LIBRESOLV@
LIBSHADOW = @LIBSHADOW@
LIBSM = @LIBSM@
LIBSOCKET = @LIBSOCKET@
LIBTIFF = @LIBTIFF@
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBUCB = @LIBUCB@
LIBUTIL = @LIBUTIL@
LIBXINERAMA = @LIBXINERAMA@
LIBZ = @LIBZ@
LIB_KAB = @LIB_KAB@
LIB_KDECORE = @LIB_KDECORE@
LIB_KDEPRINT = @LIB_KDEPRINT@
LIB_KDEUI = @LIB_KDEUI@
LIB_KFILE = @LIB_KFILE@
LIB_KFM = @LIB_KFM@
LIB_KHTML = @LIB_KHTML@
LIB_KIMGIO = @LIB_KIMGIO@
LIB_KIO = @LIB_KIO@
LIB_KPARTS = @LIB_KPARTS@
LIB_KSPELL = @LIB_KSPELL@
LIB_KSYCOCA = @LIB_KSYCOCA@
LIB_QPE = @LIB_QPE@
LIB_QT = @LIB_QT@
LIB_QTOPIA = @LIB_QTOPIA@
LIB_SMB = @LIB_SMB@
LIB_X11 = @LIB_X11@
LIB_XEXT = @LIB_XEXT@
LN_S = ln -s
MAKEINFO = makeinfo
MCOPIDL = @MCOPIDL@
MEINPROC = @MEINPROC@
MICO_INCLUDES = @MICO_INCLUDES@
MICO_LDFLAGS = @MICO_LDFLAGS@
MOC = @MOC@
MSGFMT = @MSGFMT@
NOOPT_CFLAGS = 
NOOPT_CXXFLAGS =  -g3 -I/usr/local/include -I/usr/local/lib/wx/include/x11univ-2.4 -I/usr/local/include -I/usr/X11R6/include -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXUNIVERSAL__ -D__WXX11__ -D_IODBC_ -MMD -pthread -Wall -fno-exceptions -fno-check-new
NOREPO = -fno-repo
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = plivrus
PAMLIBS = @PAMLIBS@
PASSWDLIBS = @PASSWDLIBS@
PYTHONINC = @PYTHONINC@
PYTHONLIB = @PYTHONLIB@
PYTHONMODDIR = @PYTHONMODDIR@
QTE_NORTTI = @QTE_NORTTI@
QTOPIA_INCLUDES = @QTOPIA_INCLUDES@
QT_INCLUDES = @QT_INCLUDES@
QT_LDFLAGS = @QT_LDFLAGS@
RANLIB = ranlib
REPO = -frepo
SETUIDFLAGS = @SETUIDFLAGS@
STRIP = strip
TOPSUBDIRS =  plivrus
UIC = @UIC@
UIC_TR = @UIC_TR@
USER_INCLUDES = 
USER_LDFLAGS = 
USE_EXCEPTIONS = -fexceptions
USE_RTTI = 
USE_THREADS = @USE_THREADS@
VERSION = 0.1
WOVERLOADED_VIRTUAL = 
XGETTEXT = @XGETTEXT@
XPMINC = @XPMINC@
XPMLIB = @XPMLIB@
X_EXTRA_LIBS = @X_EXTRA_LIBS@
X_INCLUDES = @X_INCLUDES@
X_LDFLAGS = @X_LDFLAGS@
X_PRE_LIBS = @X_PRE_LIBS@
all_includes =  
all_libraries =  
idldir = @idldir@
jni_includes = @jni_includes@
kde_appsdir = @kde_appsdir@
kde_bindir = @kde_bindir@
kde_confdir = @kde_confdir@
kde_datadir = @kde_datadir@
kde_htmldir = @kde_htmldir@
kde_icondir = @kde_icondir@
kde_includes = @kde_includes@
kde_libraries = @kde_libraries@
kde_libs_htmldir = @kde_libs_htmldir@
kde_libs_prefix = @kde_libs_prefix@
kde_locale = @kde_locale@
kde_mimedir = @kde_mimedir@
kde_moduledir = @kde_moduledir@
kde_qtver = @kde_qtver@
kde_servicesdir = @kde_servicesdir@
kde_servicetypesdir = @kde_servicetypesdir@
kde_sounddir = @kde_sounddir@
kde_styledir = @kde_styledir@
kde_templatesdir = @kde_templatesdir@
kde_wallpaperdir = @kde_wallpaperdir@
kde_widgetdir = @kde_widgetdir@
micodir = @micodir@
qt_includes = @qt_includes@
qt_libraries = @qt_libraries@
x_includes = @x_includes@
x_libraries = @x_libraries@

bin_PROGRAMS = plivrus

plivrus_SOURCES = VenderLivros.cpp DateCtrl.cpp ConVendas.cpp ConProfissoes.cpp ConPaises.cpp ConLivros.cpp ConIdiomas.cpp ConEnderecos.cpp ConEditoras.cpp ConClientes.cpp ConAutores.cpp CadProfissoes.cpp CadPaises.cpp CadLivros.cpp CadIdiomas.cpp CadEnderecos.cpp CadEditoras.cpp CadClientes.cpp CadAutores.cpp AlterarSenha.cpp Consultas.cpp ConAssuntos.cpp Cadastros.cpp CadAssuntos.cpp Splash.cpp Sobre.cpp RotinasGlobais.cpp Principal.cpp Login.cpp Livrus.cpp Filha.cpp ConsultasSQL.cpp 
plivrus_LDADD = /home/hfs/wxX11-2.4.2/lib/libwx_x11univ-2.4.so.0.1.1

EXTRA_DIST = ConsultasSQL.cpp ConsultasSQL.h Filha.cpp Filha.h Livrus.cpp Livrus.h Livrus.ico Livrus.rc Login.cpp Login.h Principal.cpp Principal.h resource.h RotinasGlobais.cpp RotinasGlobais.h Sobre.cpp Sobre.h Splash.cpp Splash.h CadAssuntos.cpp CadAssuntos.h Cadastros.cpp Cadastros.h ConAssuntos.cpp ConAssuntos.h Consultas.cpp Consultas.h AlterarSenha.cpp AlterarSenha.h CadAutores.cpp CadAutores.h CadClientes.cpp CadClientes.h CadEditoras.cpp CadEditoras.h CadEnderecos.cpp CadEnderecos.h CadIdiomas.cpp CadIdiomas.h CadLivros.cpp CadLivros.h CadPaises.cpp CadPaises.h CadProfissoes.cpp CadProfissoes.h ConAutores.cpp ConAutores.h ConClientes.cpp ConClientes.h ConEditoras.cpp ConEditoras.h ConEnderecos.cpp ConEnderecos.h ConIdiomas.cpp ConIdiomas.h ConLivros.cpp ConLivros.h ConPaises.cpp ConPaises.h ConProfissoes.cpp ConProfissoes.h ConVendas.cpp ConVendas.h DateCtrl.cpp DateCtrl.h VenderLivros.cpp VenderLivros.h 

####### kdevelop will overwrite this part!!! (end)############
# set the include path found by configure
INCLUDES = $(all_includes)

# the library search path.
plivrus_LDFLAGS = $(all_libraries) 
mkinstalldirs = $(SHELL) $(top_srcdir)/admin/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
bin_PROGRAMS =  plivrus$(EXEEXT)
PROGRAMS =  $(bin_PROGRAMS)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I..
CPPFLAGS = 
LDFLAGS = -lodbc -pthread -Wl,--version-script,/home/hfs/wxX11-2.4.2/version-script -L/usr/X11R6/lib -lX11 -lpng -ljpeg -ltiff -lz -ldl -lm
LIBS = 
#>- plivrus_OBJECTS =  VenderLivros.$(OBJEXT) DateCtrl.$(OBJEXT) \
#>- ConVendas.$(OBJEXT) ConProfissoes.$(OBJEXT) ConPaises.$(OBJEXT) \
#>- ConLivros.$(OBJEXT) ConIdiomas.$(OBJEXT) ConEnderecos.$(OBJEXT) \
#>- ConEditoras.$(OBJEXT) ConClientes.$(OBJEXT) ConAutores.$(OBJEXT) \
#>- CadProfissoes.$(OBJEXT) CadPaises.$(OBJEXT) CadLivros.$(OBJEXT) \
#>- CadIdiomas.$(OBJEXT) CadEnderecos.$(OBJEXT) CadEditoras.$(OBJEXT) \
#>- CadClientes.$(OBJEXT) CadAutores.$(OBJEXT) AlterarSenha.$(OBJEXT) \
#>- Consultas.$(OBJEXT) ConAssuntos.$(OBJEXT) Cadastros.$(OBJEXT) \
#>- CadAssuntos.$(OBJEXT) Splash.$(OBJEXT) Sobre.$(OBJEXT) \
#>- RotinasGlobais.$(OBJEXT) Principal.$(OBJEXT) Login.$(OBJEXT) \
#>- Livrus.$(OBJEXT) Filha.$(OBJEXT) ConsultasSQL.$(OBJEXT)
#>+ 14
plivrus_final_OBJECTS = plivrus.all_cpp.o 
plivrus_nofinal_OBJECTS = VenderLivros.$(OBJEXT) DateCtrl.$(OBJEXT) \
	ConVendas.$(OBJEXT) ConProfissoes.$(OBJEXT) ConPaises.$(OBJEXT) \
	ConLivros.$(OBJEXT) ConIdiomas.$(OBJEXT) ConEnderecos.$(OBJEXT) \
	ConEditoras.$(OBJEXT) ConClientes.$(OBJEXT) ConAutores.$(OBJEXT) \
	CadProfissoes.$(OBJEXT) CadPaises.$(OBJEXT) CadLivros.$(OBJEXT) \
	CadIdiomas.$(OBJEXT) CadEnderecos.$(OBJEXT) CadEditoras.$(OBJEXT) \
	CadClientes.$(OBJEXT) CadAutores.$(OBJEXT) AlterarSenha.$(OBJEXT) \
	Consultas.$(OBJEXT) ConAssuntos.$(OBJEXT) Cadastros.$(OBJEXT) \
	CadAssuntos.$(OBJEXT) Splash.$(OBJEXT) Sobre.$(OBJEXT) \
	RotinasGlobais.$(OBJEXT) Principal.$(OBJEXT) Login.$(OBJEXT) \
	Livrus.$(OBJEXT) Filha.$(OBJEXT) ConsultasSQL.$(OBJEXT)
plivrus_OBJECTS = $(plivrus_nofinal_OBJECTS)
#plivrus_OBJECTS = $(plivrus_final_OBJECTS)
plivrus_DEPENDENCIES =  \
	/home/hfs/wxX11-2.4.2/lib/libwx_x11univ-2.4.so.0.1.1
CXXFLAGS = -O2 -O0 -g3 -I/usr/local/include -I/usr/local/lib/wx/include/x11univ-2.4 -I/usr/local/include -I/usr/X11R6/include -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXUNIVERSAL__ -D__WXX11__ -D_IODBC_ -O2 -MMD -pthread -Wall -fno-exceptions -fno-check-new
#>- CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
#>+ 1
CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS)
#>- LTCXXCOMPILE = $(LIBTOOL) --mode=compile $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
#>+ 1
LTCXXCOMPILE = $(LIBTOOL) --mode=compile --tag=CXX $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS)
CXXLD = $(CXX)
#>- CXXLINK = $(LIBTOOL) --mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(LDFLAGS) -o $@
#>+ 1
CXXLINK = $(LIBTOOL) --mode=link --tag=CXX $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS) $(LDFLAGS) -o $@
DIST_COMMON =  Makefile.am Makefile.in


#>- DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)
#>+ 4
KDE_DIST=wx.rc 

DISTFILES= $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST) $(KDE_DIST)


TAR = gtar
GZIP_ENV = --best
#>- DEP_FILES =  .deps/AlterarSenha.P .deps/CadAssuntos.P .deps/CadAutores.P \
#>- .deps/CadClientes.P .deps/CadEditoras.P .deps/CadEnderecos.P \
#>- .deps/CadIdiomas.P .deps/CadLivros.P .deps/CadPaises.P \
#>- .deps/CadProfissoes.P .deps/Cadastros.P .deps/ConAssuntos.P \
#>- .deps/ConAutores.P .deps/ConClientes.P .deps/ConEditoras.P \
#>- .deps/ConEnderecos.P .deps/ConIdiomas.P .deps/ConLivros.P \
#>- .deps/ConPaises.P .deps/ConProfissoes.P .deps/ConVendas.P \
#>- .deps/Consultas.P .deps/ConsultasSQL.P .deps/DateCtrl.P .deps/Filha.P \
#>- .deps/Livrus.P .deps/Login.P .deps/Principal.P .deps/RotinasGlobais.P \
#>- .deps/Sobre.P .deps/Splash.P .deps/VenderLivros.P
#>+ 22
#DEP_FILES =   $(DEPDIR)/plivrus.all_cpp.P \
		  .deps/AlterarSenha.P .deps/CadAssuntos.P .deps/CadAutores.P \
	.deps/CadClientes.P .deps/CadEditoras.P .deps/CadEnderecos.P \
	.deps/CadIdiomas.P .deps/CadLivros.P .deps/CadPaises.P \
	.deps/CadProfissoes.P .deps/Cadastros.P .deps/ConAssuntos.P \
	.deps/ConAutores.P .deps/ConClientes.P .deps/ConEditoras.P \
	.deps/ConEnderecos.P .deps/ConIdiomas.P .deps/ConLivros.P \
	.deps/ConPaises.P .deps/ConProfissoes.P .deps/ConVendas.P \
	.deps/Consultas.P .deps/ConsultasSQL.P .deps/DateCtrl.P .deps/Filha.P \
	.deps/Livrus.P .deps/Login.P .deps/Principal.P .deps/RotinasGlobais.P \
	.deps/Sobre.P .deps/Splash.P .deps/VenderLivros.P
DEP_FILES =    .deps/AlterarSenha.P .deps/CadAssuntos.P .deps/CadAutores.P \
	.deps/CadClientes.P .deps/CadEditoras.P .deps/CadEnderecos.P \
	.deps/CadIdiomas.P .deps/CadLivros.P .deps/CadPaises.P \
	.deps/CadProfissoes.P .deps/Cadastros.P .deps/ConAssuntos.P \
	.deps/ConAutores.P .deps/ConClientes.P .deps/ConEditoras.P \
	.deps/ConEnderecos.P .deps/ConIdiomas.P .deps/ConLivros.P \
	.deps/ConPaises.P .deps/ConProfissoes.P .deps/ConVendas.P \
	.deps/Consultas.P .deps/ConsultasSQL.P .deps/DateCtrl.P .deps/Filha.P \
	.deps/Livrus.P .deps/Login.P .deps/Principal.P .deps/RotinasGlobais.P \
	.deps/Sobre.P .deps/Splash.P .deps/VenderLivros.P

SOURCES = $(plivrus_SOURCES)
OBJECTS = $(plivrus_OBJECTS)

#>- all: all-redirect
#>+ 1
all: docs-am  all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .cpp .lo .o .obj .s
$(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
#>- 	cd $(top_srcdir) && $(AUTOMAKE) --gnu plivrus/Makefile
#>+ 2
	cd $(top_srcdir) && $(AUTOMAKE) --gnu plivrus/Makefile
	cd $(top_srcdir) && perl admin/am_edit plivrus/Makefile.in

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	&& CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-binPROGRAMS:

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

distclean-binPROGRAMS:

maintainer-clean-binPROGRAMS:

install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	if test -f $$p; then \
	echo " $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`"; \
	$(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	list='$(bin_PROGRAMS)'; for p in $$list; do \
	rm -f $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	done

# FIXME: We should only use cygpath when building on Windows,
# and only if it is available.
.c.obj:
	$(COMPILE) -c `cygpath -w $<`

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core
	-rm -f *.$(OBJEXT)

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

plivrus$(EXEEXT): $(plivrus_OBJECTS) $(plivrus_DEPENDENCIES)
	@rm -f plivrus$(EXEEXT)
	$(CXXLINK) $(plivrus_LDFLAGS) $(plivrus_OBJECTS) $(plivrus_LDADD) $(LIBS)
.cpp.o:
	$(CXXCOMPILE) -c $<
.cpp.obj:
	$(CXXCOMPILE) -c `cygpath -w $<`
.cpp.lo:
	$(LTCXXCOMPILE) -c $<

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	awk '    { files[$$0] = 1; } \
	END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	&& mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	awk '    { files[$$0] = 1; } \
	END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	|| (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = plivrus

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	&& $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu plivrus/Makefile
	@for file in $(DISTFILES); do \
	d=$(srcdir); \
	if test -d $$d/$$file; then \
	cp -pr $$d/$$file $(distdir)/$$file; \
	else \
	test -f $(distdir)/$$file \
	|| ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	|| cp -p $$d/$$file $(distdir)/$$file || :; \
	fi; \
	done

DEPS_MAGIC := $(shell mkdir .deps > /dev/null 2>&1 || :)

-include $(DEP_FILES)

mostlyclean-depend:

clean-depend:

distclean-depend:
	-rm -rf .deps

maintainer-clean-depend:

%.o: %.c
	@echo '$(COMPILE) -c $<'; \
	$(COMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-cp .deps/$(*F).pp .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	| sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	>> .deps/$(*F).P; \
	rm .deps/$(*F).pp

%.lo: %.c
	@echo '$(LTCOMPILE) -c $<'; \
	$(LTCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
	< .deps/$(*F).pp > .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	| sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	>> .deps/$(*F).P; \
	rm -f .deps/$(*F).pp

%.o: %.cpp
	@echo '$(CXXCOMPILE) -c $<'; \
	$(CXXCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-cp .deps/$(*F).pp .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	| sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	>> .deps/$(*F).P; \
	rm .deps/$(*F).pp

%.lo: %.cpp
	@echo '$(LTCXXCOMPILE) -c $<'; \
	$(LTCXXCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
	< .deps/$(*F).pp > .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	| sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	>> .deps/$(*F).P; \
	rm -f .deps/$(*F).pp
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am: install-binPROGRAMS
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-binPROGRAMS
uninstall: uninstall-am
all-am: Makefile $(PROGRAMS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(bindir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-binPROGRAMS mostlyclean-compile \
	mostlyclean-libtool mostlyclean-tags mostlyclean-depend \
	mostlyclean-generic

mostlyclean: mostlyclean-am

#>- clean-am:  clean-binPROGRAMS clean-compile clean-libtool clean-tags \
#>- clean-depend clean-generic mostlyclean-am
#>+ 2
clean-am: clean-final   clean-binPROGRAMS clean-compile clean-libtool clean-tags \
	clean-depend clean-generic mostlyclean-am

#>- clean: clean-am
#>+ 1
clean: kde-rpo-clean  clean-am

distclean-am:  distclean-binPROGRAMS distclean-compile distclean-libtool \
	distclean-tags distclean-depend distclean-generic \
	clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-binPROGRAMS \
	maintainer-clean-compile maintainer-clean-libtool \
	maintainer-clean-tags maintainer-clean-depend \
	maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-binPROGRAMS distclean-binPROGRAMS clean-binPROGRAMS \
	maintainer-clean-binPROGRAMS uninstall-binPROGRAMS install-binPROGRAMS \
	mostlyclean-compile distclean-compile clean-compile \
	maintainer-clean-compile mostlyclean-libtool distclean-libtool \
	clean-libtool maintainer-clean-libtool tags mostlyclean-tags \
	distclean-tags clean-tags maintainer-clean-tags distdir \
	mostlyclean-depend distclean-depend clean-depend \
	maintainer-clean-depend info-am info dvi-am dvi check check-am \
	installcheck-am installcheck install-exec-am install-exec \
	install-data-am install-data install-am install uninstall-am uninstall \
	all-redirect all-am all installdirs mostlyclean-generic \
	distclean-generic clean-generic maintainer-clean-generic clean \
	mostlyclean distclean maintainer-clean


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:

#>+ 2
docs-am:

#>+ 5
force-reedit:
		cd $(top_srcdir) && $(AUTOMAKE) --gnu plivrus/Makefile
	cd $(top_srcdir) && perl admin/am_edit plivrus/Makefile.in


#>+ 11
plivrus.all_cpp.cpp: $(srcdir)/Makefile.in $(srcdir)/VenderLivros.cpp $(srcdir)/DateCtrl.cpp $(srcdir)/ConVendas.cpp $(srcdir)/ConProfissoes.cpp $(srcdir)/ConPaises.cpp $(srcdir)/ConLivros.cpp $(srcdir)/ConIdiomas.cpp $(srcdir)/ConEnderecos.cpp $(srcdir)/ConEditoras.cpp $(srcdir)/ConClientes.cpp $(srcdir)/ConAutores.cpp $(srcdir)/CadProfissoes.cpp $(srcdir)/CadPaises.cpp $(srcdir)/CadLivros.cpp $(srcdir)/CadIdiomas.cpp $(srcdir)/CadEnderecos.cpp $(srcdir)/CadEditoras.cpp $(srcdir)/CadClientes.cpp $(srcdir)/CadAutores.cpp $(srcdir)/AlterarSenha.cpp $(srcdir)/Consultas.cpp $(srcdir)/ConAssuntos.cpp $(srcdir)/Cadastros.cpp $(srcdir)/CadAssuntos.cpp $(srcdir)/Splash.cpp $(srcdir)/Sobre.cpp $(srcdir)/RotinasGlobais.cpp $(srcdir)/Principal.cpp $(srcdir)/Login.cpp $(srcdir)/Livrus.cpp $(srcdir)/Filha.cpp $(srcdir)/ConsultasSQL.cpp  
	@echo 'creating plivrus.all_cpp.cpp ...'; \
	rm -f plivrus.all_cpp.files plivrus.all_cpp.final; \
	echo "#define KDE_USE_FINAL 1" >> plivrus.all_cpp.final; \
	for file in VenderLivros.cpp DateCtrl.cpp ConVendas.cpp ConProfissoes.cpp ConPaises.cpp ConLivros.cpp ConIdiomas.cpp ConEnderecos.cpp ConEditoras.cpp ConClientes.cpp ConAutores.cpp CadProfissoes.cpp CadPaises.cpp CadLivros.cpp CadIdiomas.cpp CadEnderecos.cpp CadEditoras.cpp CadClientes.cpp CadAutores.cpp AlterarSenha.cpp Consultas.cpp ConAssuntos.cpp Cadastros.cpp CadAssuntos.cpp Splash.cpp Sobre.cpp RotinasGlobais.cpp Principal.cpp Login.cpp Livrus.cpp Filha.cpp ConsultasSQL.cpp ; do \
	  echo "#include \"$$file\"" >> plivrus.all_cpp.files; \
	  test ! -f $(srcdir)/$$file || egrep '^#pragma +implementation' $(srcdir)/$$file >> plivrus.all_cpp.final; \
	done; \
	cat plivrus.all_cpp.final plivrus.all_cpp.files  > plivrus.all_cpp.cpp; \
	rm -f plivrus.all_cpp.final plivrus.all_cpp.files

#>+ 3
clean-final:
	-rm -f plivrus.all_cpp.cpp

#>+ 2
final:
	$(MAKE) plivrus_OBJECTS="$(plivrus_final_OBJECTS)" all-am
#>+ 2
final-install:
	$(MAKE) plivrus_OBJECTS="$(plivrus_final_OBJECTS)" install-am
#>+ 2
no-final:
	$(MAKE) plivrus_OBJECTS="$(plivrus_nofinal_OBJECTS)" all-am
#>+ 2
no-final-install:
	$(MAKE) plivrus_OBJECTS="$(plivrus_nofinal_OBJECTS)" install-am
#>+ 3
cvs-clean:
	$(MAKE) -f $(top_srcdir)/admin/Makefile.common cvs-clean

#>+ 3
kde-rpo-clean:
	-rm -f *.rpo
