// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef Livrus_h
#define Livrus_h
#include <FL/Fl.H>
#include <FL/Fl_Menu_Bar.H>
extern void frmPrincipal_mnuCadAssuntos_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuCadAutores_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuCadEditoras_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuCadEnderecos_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuCadIdiomas_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuCadPaises_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuCadProfissoes_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuCadClientes_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuCadLivros_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuConAssuntos_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuConAutores_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuConEditoras_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuConEnderecos_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuConIdiomas_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuConPaises_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuConProfissoes_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuConClientes_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuConLivros_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuVenVenderLivros_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuVenVendasRealizadas_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuOpAlterarSenha_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuOpSobre_cb(Fl_Menu_*, void*);
extern void frmPrincipal_mnuOpSair_cb(Fl_Menu_*, void*);
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
extern void frmPrincipal_tlbClientesClick_cb(Fl_Button*, void*);
extern void frmPrincipal_tlbLivrosClick_cb(Fl_Button*, void*);
extern void frmPrincipal_tlbVendaClick_cb(Fl_Button*, void*);
extern void frmPrincipal_tlbSobreClick_cb(Fl_Button*, void*);
extern void frmPrincipal_tlbSairClick_cb(Fl_Button*, void*);
#include <FL/Fl_Box.H>
#include <FL/Fl_Double_Window.H>

class CfrmPrincipal : Fl_Window {
public:
  void IniciaControles();
  frmPrincipal *fPrincipal;
  Fl_Menu_Bar *BarraDeMenu;
  static Fl_Menu_Item menu_BarraDeMenu[];
  static Fl_Menu_Item *mnuCadastros;
  static Fl_Menu_Item *mnuCadAssuntos;
  static Fl_Menu_Item *mnuCadAutores;
  static Fl_Menu_Item *mnuCadEditoras;
  static Fl_Menu_Item *mnuCadEnderecos;
  static Fl_Menu_Item *mnuCadIdiomas;
  static Fl_Menu_Item *mnuCadPaises;
  static Fl_Menu_Item *mnuCadProfissoes;
  static Fl_Menu_Item *mnuCadCLientes;
  static Fl_Menu_Item *mnuCadLivros;
  static Fl_Menu_Item *mnuPesquisas;
  static Fl_Menu_Item *mnuConAssuntos;
  static Fl_Menu_Item *mnuConAutores;
  static Fl_Menu_Item *mnuConEditoras;
  static Fl_Menu_Item *mnuConEnderecos;
  static Fl_Menu_Item *mnuConIdiomas;
  static Fl_Menu_Item *mnuConPaises;
  static Fl_Menu_Item *mnuConProfissoes;
  static Fl_Menu_Item *mnuConClientes;
  static Fl_Menu_Item *mnuConLivros;
  static Fl_Menu_Item *mnuVendas;
  static Fl_Menu_Item *mnuVenVenderLivros;
  static Fl_Menu_Item *mnuVenVendasRealizadas;
  static Fl_Menu_Item *mnuJanelas;
  static Fl_Menu_Item *mnuJanLadoHorizontal;
  static Fl_Menu_Item *mnuJanLadoVertical;
  static Fl_Menu_Item *mnuJanEmCascata;
  static Fl_Menu_Item *mnuJanOrganizarIcones;
  static Fl_Menu_Item *mnuOpcoes;
  static Fl_Menu_Item *mnuOpAlterarSenha;
  static Fl_Menu_Item *mnuOpSobre;
  static Fl_Menu_Item *mnuOpSair;
  Fl_Group *BarraDeFerra;
  Fl_Button *tlbClientes;
  Fl_Button *tlbLivros;
  Fl_Button *tlbVenda;
  Fl_Button *tlbSobre;
  Fl_Button *tlbSair;
  Fl_Box *BarraDeStatus1;
  Fl_Box *BarraDeStatus2;
};
#include <FL/Fl_Input.H>
extern void frmCadastros_btnNovoClick_cb(Fl_Button*, void*);
extern void frmCadastros_btnPesquisarClick_cb(Fl_Button*, void*);
extern void frmCadastros_btnAnteriorClick_cb(Fl_Button*, void*);
extern void frmCadastros_btnProximoClick_cb(Fl_Button*, void*);
extern void frmCadastros_btnSalvarClick_cb(Fl_Button*, void*);
extern void frmCadastros_btnExcluirClick_cb(Fl_Button*, void*);
extern void frmCadastros_btnLimparClick_cb(Fl_Button*, void*);
extern void frmCadastros_btnFecharClick_cb(Fl_Button*, void*);

class CfrmCadastros : Fl_Double_Window {
public:
  void IniciaControles();
  Fl_Double_Window *fCadastros;
  Fl_Input *edtCodigo;
  Fl_Button *btnNovo;
  Fl_Input *edtDescricao;
  Fl_Button *btnPesquisar;
  Fl_Button *btnAnterior;
  Fl_Button *btnProximo;
  Fl_Button *btnSalvar;
  Fl_Button *btnExcluir;
  Fl_Button *btnLimpar;
  Fl_Button *btnFechar;
};

class CfrmSplash : Fl_Double_Window {
public:
  void IniciaControles();
  CfrmSplash *fSplash;
  Fl_Box *imagem1;
};
extern void frmSobre_btnOkClick_cb(Fl_Button*, void*);

class CfrmSobre : Fl_Double_Window {
public:
  void IniciaControles();
  CfrmSobre *fSobre;
  Fl_Group *grupo1;
  Fl_Box *imagem1;
  Fl_Box *labVersao;
  Fl_Box *labDireitos;
  Fl_Box *labSistema;
  Fl_Button *btnOk;
};
extern void frmLogin_btnLoginClick_cb(Fl_Button*, void*);
extern void frmLogin_btnCancelarClick_cb(Fl_Button*, void*);

class CfrmLogin : Fl_Double_Window {
public:
  void IniciaControles();
  CfrmLogin *fLogin;
  Fl_Input *edtLogin;
  Fl_Input *edtSenha;
  Fl_Button *btnLogin;
  Fl_Button *btnCancelar;
};
extern void frmAlterarSenha_btnSalvarClick_cb(Fl_Button*, void*);
extern void frmAlterarSenha_btnLimparClick_cb(Fl_Button*, void*);
extern void frmAlterarSenha_btnFecharClick_cb(Fl_Button*, void*);

class CfrmAlterarSenha : Fl_Double_Window {
public:
  void IniciaControles();
  CfrmAlterarSenha *fAlterarSenha;
  Fl_Input *edtLogin;
  Fl_Input *edtSenhaAtual;
  Fl_Input *edtNovaSenha;
  Fl_Input *edtConfirmaSenha;
  Fl_Button *btnSalvar;
  Fl_Button *btnLimpar;
  Fl_Button *btnFechar;
};
extern void frmCadEnderecos_btnNovoClick_cb(Fl_Button*, void*);
#include <FL/Fl_Choice.H>
extern void frmCadEnderecos_btnPesquisarClick_cb(Fl_Button*, void*);
extern void frmCadEnderecos_btnAnteriorClick_cb(Fl_Button*, void*);
extern void frmCadEnderecos_btnProximoClick_cb(Fl_Button*, void*);
extern void frmCadEnderecos_btnSalvarClick_cb(Fl_Button*, void*);
extern void frmCadEnderecos_btnExcluirClick_cb(Fl_Button*, void*);
extern void frmCadEnderecos_btnLimparClick_cb(Fl_Button*, void*);
extern void frmCadEnderecos_btnFecharClick_cb(Fl_Button*, void*);

class CfrmCadEnderecos : CfrmCadastros {
public:
  void IniciaControles();
  CfrmCadEnderecos *fCadEnderecos;
  Fl_Input *edtCodigo;
  Fl_Button *btnNovo;
  Fl_Input *edtDescricao;
  Fl_Input *edtBairro;
  Fl_Input *edtCep;
  Fl_Input *edtCidade;
  Fl_Choice *cmbEstado;
  Fl_Button *btnPesquisar;
  Fl_Button *btnAnterior;
  Fl_Button *btnProximo;
  Fl_Button *btnSalvar;
  Fl_Button *btnExcluir;
  Fl_Button *btnLimpar;
  Fl_Button *btnFechar;
};
extern void frmCadAssuntos_btnNovoClick_cb(Fl_Button*, void*);
extern void frmCadAssuntos_btnPesquisarClick_cb(Fl_Button*, void*);
extern void frmCadAssuntos_btnAnteriorClick_cb(Fl_Button*, void*);
extern void frmCadAssuntos_btnProximoClick_cb(Fl_Button*, void*);
extern void frmCadAssuntos_btnSalvarClick_cb(Fl_Button*, void*);
extern void frmCadAssuntos_btnExcluirClick_cb(Fl_Button*, void*);
extern void frmCadAssuntos_btnLimparClick_cb(Fl_Button*, void*);
extern void frmCadAssuntos_btnFecharClick_cb(Fl_Button*, void*);

class CfrmCadAssuntos : CfrmCadastros {
public:
  void IniciaControles();
  Fl_Double_Window *fCadAssuntos;
  Fl_Input *edtCodigo;
  Fl_Button *btnNovo;
  Fl_Input *edtDescricao;
  Fl_Button *btnPesquisar;
  Fl_Button *btnAnterior;
  Fl_Button *btnProximo;
  Fl_Button *btnSalvar;
  Fl_Button *btnExcluir;
  Fl_Button *btnLimpar;
  Fl_Button *btnFechar;
};
extern void frmCadAutores_btnNovoClick_cb(Fl_Button*, void*);
extern void frmCadAutores_btnPesquisarClick_cb(Fl_Button*, void*);
extern void frmCadAutores_btnAnteriorClick_cb(Fl_Button*, void*);
extern void frmCadAutores_btnProximoClick_cb(Fl_Button*, void*);
extern void frmCadAutores_btnSalvarClick_cb(Fl_Button*, void*);
extern void frmCadAutores_btnExcluirClick_cb(Fl_Button*, void*);
extern void frmCadAutores_btnLimparClick_cb(Fl_Button*, void*);
extern void frmCadAutores_btnFecharClick_cb(Fl_Button*, void*);

class CfrmCadAutores : CfrmCadastros {
public:
  void IniciaControles();
  Fl_Double_Window *fCadAutores;
  Fl_Input *edtCodigo;
  Fl_Button *btnNovo;
  Fl_Input *edtDescricao;
  Fl_Button *btnPesquisar;
  Fl_Button *btnAnterior;
  Fl_Button *btnProximo;
  Fl_Button *btnSalvar;
  Fl_Button *btnExcluir;
  Fl_Button *btnLimpar;
  Fl_Button *btnFechar;
};
extern void frmCadClientes_edtCodigoKillFocus_cb(Fl_Input*, void*);
extern void frmCadClientes_btnNovoClick_cb(Fl_Button*, void*);
#include <FL/Fl_Round_Button.H>
extern void frmCadClientes_edtDtNascKillFocus_cb(Fl_Input*, void*);
extern void frmCadLivros_edtCodEnderecoKillFocus_cb(Fl_Input*, void*);
extern void frmCadClientes_btnPEnderecoClick_cb(Fl_Button*, void*);
extern void frmCadClientes_edtCodPaisKillFocus_cb(Fl_Input*, void*);
extern void frmCadClientes_btnPPaisClick_cb(Fl_Button*, void*);
extern void frmCadClientes_edtCodProfissaoKillFocus_cb(Fl_Input*, void*);
extern void frmCadClientes_btnPProfissaoClick_cb(Fl_Button*, void*);
extern void frmCadClientes_btnPesquisarClick_cb(Fl_Button*, void*);
extern void frmCadClientes_btnAnteriorClick_cb(Fl_Button*, void*);
extern void frmCadClientes_btnProximoClick_cb(Fl_Button*, void*);
extern void frmCadClientes_btnSalvarClick_cb(Fl_Button*, void*);
extern void frmCadClientes_btnExcluirClick_cb(Fl_Button*, void*);
extern void frmCadClientes_btnLimparClick_cb(Fl_Button*, void*);
extern void frmCadClientes_btnFecharClick_cb(Fl_Button*, void*);

class CfrmCadClientes : CfrmCadastros {
public:
  void IniciaControles();
  CfrmCadClientes *fCadClientes;
  Fl_Input *edtCodigo;
  Fl_Button *btnNovo;
  Fl_Input *edtDescricao;
  Fl_Input *edtEmail;
  Fl_Input *edtIdentidade;
  Fl_Group *grpSexo;
  Fl_Round_Button *rbMasculino;
  Fl_Round_Button *rbFeminino;
  Fl_Input *edtTelefone;
  Fl_Input *edtDtNasc;
  Fl_Group *grpEndereco;
  Fl_Input *edtCodEndereco;
  Fl_Button *btnPEndereco;
  Fl_Input *edtLogradouro;
  Fl_Input *edtBairro;
  Fl_Input *edtCep;
  Fl_Input *edtCidade;
  Fl_Input *edtEstado;
  Fl_Input *edtCodPais;
  Fl_Input *edtPais;
  Fl_Button *btnPPais;
  Fl_Input *edtCodProfissao;
  Fl_Input *edtProfissao;
  Fl_Button *btnPProfissao;
  Fl_Button *btnPesquisar;
  Fl_Button *btnAnterior;
  Fl_Button *btnProximo;
  Fl_Button *btnSalvar;
  Fl_Button *btnExcluir;
  Fl_Button *btnLimpar;
  Fl_Button *btnFechar;
};
extern void frmCadLivros_edtCodigoKillFocus_cb(Fl_Input*, void*);
extern void frmCadLivros_btnNovoClick_cb(Fl_Button*, void*);
#include <FL/Fl_Value_Input.H>
extern void frmCadLivros_edtCodEditoraKillFocus_cb(Fl_Input*, void*);
extern void frmCadLivros_btnPEditoraClick_cb(Fl_Button*, void*);
extern void frmCadLivros_edtCodAssuntoKillFocus_cb(Fl_Input*, void*);
extern void frmCadLivros_btnAdAssuntosClick_cb(Fl_Button*, void*);
extern void frmCadLivros_btnPAssuntoClick_cb(Fl_Button*, void*);
#include <FL/Fl_Browser.H>
extern void frmCadLivros_lstAssuntosDblClick_cb(Fl_Browser*, void*);
extern void frmCadLivros_edtCodAutorKillFocus_cb(Fl_Input*, void*);
extern void frmCadLivros_btnAdAutoresClick_cb(Fl_Button*, void*);
extern void frmCadLivros_btnPAutorClick_cb(Fl_Button*, void*);
extern void frmCadLivros_lstAutoresDblClick_cb(Fl_Browser*, void*);
extern void frmCadLivros_btnPesquisarClick_cb(Fl_Button*, void*);
extern void frmCadLivros_btnAnteriorClick_cb(Fl_Button*, void*);
extern void frmCadLivros_btnProximoClick_cb(Fl_Button*, void*);
extern void frmCadLivros_btnSalvarClick_cb(Fl_Button*, void*);
extern void frmCadLivros_btnExcluirClick_cb(Fl_Button*, void*);
extern void frmCadLivros_btnLimparClick_cb(Fl_Button*, void*);
extern void frmCadLivros_btnFecharClick_cb(Fl_Button*, void*);

class CfrmCadLivros : CfrmCadastros {
public:
  void IniciaControles();
  CfrmCadLivros *fCadLivros;
  Fl_Input *edtCodigo;
  Fl_Button *btnNovo;
  Fl_Input *edtDescricao;
  Fl_Value_Input *edtEdicao;
  Fl_Value_Input *edtAnoPubli;
  Fl_Input *edtCodEditora;
  Fl_Input *edtEditora;
  Fl_Button *btnPEditora;
  Fl_Value_Input *edtVolume;
  Fl_Choice *cmbIdioma;
  Fl_Value_Input *edtNPaginas;
  Fl_Input *edtCodAssunto;
  Fl_Input *edtAssunto;
  Fl_Button *btnAdAssuntos;
  Fl_Button *btnPAssunto;
  Fl_Input *edtPreco;
  Fl_Browser *lstAssuntos;
  Fl_Value_Input *edtQtdEstoque;
  Fl_Input *edtCodAutor;
  Fl_Input *edtAutor;
  Fl_Button *btnAdAutores;
  Fl_Button *btnPAutor;
  Fl_Browser *lstAutores;
  Fl_Button *btnPesquisar;
  Fl_Button *btnAnterior;
  Fl_Button *btnProximo;
  Fl_Button *btnSalvar;
  Fl_Button *btnExcluir;
  Fl_Button *btnLimpar;
  Fl_Button *btnFechar;
};
extern void frmConsultas_btnPesquisarClick_cb(Fl_Button*, void*);
extern void frmConsultas_gridConsultaSelect_cb(Fl_Browser*, void*);
extern void frmConsultas_btnLimparClick_cb(Fl_Button*, void*);
extern void frmConsultas_btnFecharClick_cb(Fl_Button*, void*);

class CfrmConsultas : Fl_Double_Window {
public:
  void IniciaControles();
  CfrmConsultas *fConsultas;
  Fl_Group *grupo1;
  Fl_Input *edtDescricao;
  Fl_Button *btnPesquisar;
  Fl_Browser *gridConsulta;
  Fl_Group *grupo2;
  Fl_Box *labRegistros;
  Fl_Button *btnLimpar;
  Fl_Button *btnFechar;
};

class CfrmConAssuntos : CfrmConsultas {
public:
  void IniciaControles();
  CfrmConAssuntos *fConAssuntos;
  Fl_Group *grupo1;
  Fl_Input *edtDescricao;
  Fl_Button *btnPesquisar;
  Fl_Browser *gridConsulta;
  Fl_Group *grupo2;
  Fl_Box *labRegistros;
  Fl_Button *btnLimpar;
  Fl_Button *btnFechar;
};
#include <FL/Fl_Output.H>
extern void frmVenderLivros_edtCPFKillFocus_cb(Fl_Input*, void*);
extern void frmVenderLivros_btnPClienteClick_cb(Fl_Button*, void*);
extern void frmVenderLivros_edtISBNKillFocus_cb(Fl_Input*, void*);
extern void frmVenderLivros_btnAdLivrosClick_cb(Fl_Button*, void*);
extern void frmVenderLivros_btnPLivroClick_cb(Fl_Button*, void*);
extern void frmVenderLivros_lstVendasSelect_cb(Fl_Browser*, void*);
extern void frmVenderLivros_btnVenderClick_cb(Fl_Button*, void*);
extern void frmVenderLivros_btnLimparClick_cb(Fl_Button*, void*);
extern void frmVenderLivros_btnFecharClick_cb(Fl_Button*, void*);

class CfrmVenderLivros : Fl_Double_Window {
public:
  void IniciaControles();
  CfrmVenderLivros *fVenderLivros;
  Fl_Output *edtDtHrVenda;
  Fl_Input *edtCPF;
  Fl_Output *edtCliente;
  Fl_Button *btnPCliente;
  Fl_Input *edtISBN;
  Fl_Output *edtLivro;
  Fl_Button *btnAdLivros;
  Fl_Button *btnPLivro;
  Fl_Browser *lstLivros;
  Fl_Output *edtPrecoTotal;
  Fl_Button *btnVender;
  Fl_Button *btnLimpar;
  Fl_Button *btnFechar;
};
extern void frmConVendas_edtDtHrVendaKillFocus_cb(Fl_Output*, void*);
extern void frmConVendas_btnPesquisarClick_cb(Fl_Button*, void*);
extern void frmConVendas_edtCPFKillFocus_cb(Fl_Input*, void*);
extern void frmConVendas_btnPClienteClick_cb(Fl_Button*, void*);
extern void frmConVendas_edtISBNKillFocus_cb(Fl_Input*, void*);
extern void frmConVendas_btnPLivroClick_cb(Fl_Button*, void*);
extern void frmConVendas_gridConsultaSelect_cb(Fl_Browser*, void*);
extern void frmConVendas_btnLimparClick_cb(Fl_Button*, void*);
extern void frmConVendas_btnFecharClick_cb(Fl_Button*, void*);

class CfrmConVendas : Fl_Double_Window {
public:
  void IniciaControles();
  CfrmConVendas *fConVendas;
  Fl_Group *grupo1;
  Fl_Output *edtDtHrVenda;
  Fl_Button *btnPesquisar;
  Fl_Input *edtCPF;
  Fl_Output *edtCliente;
  Fl_Button *btnPCliente;
  Fl_Input *edtISBN;
  Fl_Output *edtLivro;
  Fl_Button *btnPLivro;
  Fl_Browser *gridConsulta;
  Fl_Group *grupo2;
  Fl_Box *labRegistros;
  Fl_Output *edtPrecoTotal;
  Fl_Button *btnLimpar;
  Fl_Button *btnFechar;
};
#endif
