$Resource = nil

class Resource
  FRMPRINCIPAL = 900
  FRMCADASSUNTOS = 1000
  FRMCADAUTORES	 = 1001
  FRMCADEDITORAS = 1002
  FRMCADENDERECOS = 1003
  FRMCADIDIOMAS	 = 1004
  FRMCADPAISES	 = 1005
  FRMCADPROFISSOES = 1006
  FRMCADCLIENTES	 = 1007
  FRMCADLIVROS	  = 1008
  FRMVENDERLIVROS = 1009
  FRMCONVENDAS	  = 1010
  FRMALTERARSENHA = 1111

  MNU_CAD_ASSUNTOS	=	2000
  MNU_CAD_AUTORES	=	2001
  MNU_CAD_EDITORAS  =	2002
  MNU_CAD_ENDERECOS	=	2003
  MNU_CAD_IDIOMAS	=	2004
  MNU_CAD_PAISES	=	2005
  MNU_CAD_PROFISSOES	=	2006
  MNU_CAD_CLIENTES	=	2007
  MNU_CAD_LIVROS	=	2008
  MNU_CON_ASSUNTOS	=	2009
  MNU_CON_AUTORES	=	2010
  MNU_CON_EDITORAS	=	2011
  MNU_CON_ENDERECOS	=	2012
  MNU_CON_IDIOMAS	=	2013
  MNU_CON_PAISES	=	2014
  MNU_CON_PROFISSOES	=	2015
  MNU_CON_CLIENTES	=	2016
  MNU_CON_LIVROS	=	2017
  MNU_VEN_VENDERLIVROS	=	2018
  MNU_VEN_VENDASREALIZADAS	=	2019
  MNU_OP_ALTERARSENHA	=	2020
  MNU_OP_SOBRE	=	2021
  MNU_OP_SAIR	=	2022

  TLB_CADCLIENTES = 2023
  TLB_CADLIVROS = 2024
  TLB_VENDERLIVROS = 2025

  ICO_LIVRUS	      = "Livrus.ico"

  STR_TITULO        = "Livrus Virtus"
  STR_APPEXEC       = "A aplica\xe7\xe3o j\xe1 est\xe1 sendo executada."
  STR_NREGJAN       = "N\xe3o consigo registrar a janela principal."
  STR_SEMJAN        = "Sem janela principal"
  STR_NCONBANCO     = "N\xe3o consigo conectar com o banco de dados!"
  STR_NALOCODBC     = "N\xe3o foi poss\xedvel alocar um manuseador para o ambiente ODBC"
  STR_CADASSUNTO    = "Cadastro de Assuntos"
  STR_CADAUTOR      = "Cadastro de Autores"
  STR_CADEDITORA    = "Cadastro de Editoras"
  STR_CADENDERECO   = "Cadastro de Endere\xe7os"
  STR_CADIDIOMA     = "Cadastro de Idiomas"
  STR_CADPAIS       = "Cadastro de Pa\xedses"
  STR_CADPROFISS    = "Cadastro de Profiss\xf5es"
  STR_CADCLIENTE    = "Cadastro de Clientes"
  STR_CADLIVRO      = "Cadastro de Livros"
  STR_CONASSUNTO    = "Consulta de Assuntos"
  STR_CONAUTOR      = "Consulta de Autores"
  STR_CONEDITORA    = "Consulta de Editoras"
  STR_CONENDERECO   = "Consulta de Endere\xe7os"
  STR_CONIDIOMA     = "Consulta de Idiomas"
  STR_CONPAIS       = "Consulta de Pa\xedses"
  STR_CONPROFISS    = "Consulta de Profiss\xf5es"
  STR_CONCLIENTE    = "Consulta de Clientes"
  STR_CONLIVRO      = "Consulta de Livros"
  STR_VENLIVRO      = "Vender Livros"
  STR_CONVENLIVRO   = "Vendas Realizadas"
  STR_ALTSENHA      = "Altera\xe7\xe3o de Senha"
  STR_OPSOBRE       = "Sobre o Sistema"
  STR_OPSAIR        = "Sair do Sistema"  
  STR_SAIRSIS       = "Deseja sair do sistema?"
  STR_EMAILNINF     = "E-mail n\xe3o informado!"
  STR_NCCRIADLG     = "N\xe3o consigo criar a dialog!"
  STR_CERTEXCL      = "Certeza de excluir?"
  STR_TELNINF       = "Telefone n\xe3o informado!"
  STR_NREGTELA      = "N\xe3o consigo registrar a tela!"
  STR_NCCRIATELA    = "N\xe3o consigo criar a tela!"
  STR_NCPREPSQL     = "N\xe3o conseguiu preparar o SQL!"
  STR_NCEXECSQL     = "N\xe3o conseguiu executar o SQL!"
  STR_DATINV        = "Data inv\xe1lida!"
  STR_SENALTSUC     = "Senha alterada com sucesso!"
  STR_SENNCSU       = "A Senha atual n\xe3o confere com a senha do usu\xe1rio!"
  STR_NSENNINF      = "Nova senha n\xe3o informada!"
  STR_NSENNCCON     = "A Nova senha n\xe3o confere com a senha a confirmar!"
  STR_DTHRINV       = "Data/Hora inv\xe1lida!"
  STR_USUARIO       = "Usu\xe1rio: "
  STR_LOGSENINC     = "Login ou senha incorretos!"
  STR_ISBNNINF      = "ISBN n\xe3o informado!"
  STR_CODNINF       = "C\xf3digo n\xe3o informado!"
  STR_ASSNENC       = "Assunto n\xe3o encontrado!"
  STR_ASSNINF       = "Assunto n\xe3o informado!"
  STR_AUTNENC       = "Autor n\xe3o encontrado!"
  STR_AUTNINF       = "Autor n\xe3o informado!"
  STR_EDTNENC       = "Editora n\xe3o encontrada!"
  STR_EDTNINF       = "Editora n\xe3o informada!"
  STR_ENDNENC       = "Endere\xe7o n\xe3o encontrado!"
  STR_ENDNINF       = "Endere\xe7o n\xe3o informado!"
  STR_IDINENC       = "Idioma n\xe3o encontrado!"
  STR_IDININF       = "Idioma n\xe3o informado!"
  STR_PAISNENC      = "Pa\xeds n\xe3o encontrado!"
  STR_PAISNINF      = "Pa\xeds n\xe3o informado!"
  STR_PROFNENC      = "Profiss\xe3o n\xe3o encontrada!"
  STR_PROFNINF      = "Profiss\xe3o n\xe3o informada!"
  STR_CLINENC       = "Cliente n\xe3o encontrado!"
  STR_CLININF       = "Cliente n\xe3o informado!"
  STR_LIVNENC       = "Livro n\xe3o encontrado!"
  STR_LIVNINF       = "Livro n\xe3o informado!"
  STR_PE            = "Pernambuco"
  STR_AC            = "Acre"
  STR_AL            = "Alagoas"
  STR_AP            = "Amap\xe1"
  STR_AM            = "Amazonas"
  STR_BA            = "Bahia"
  STR_BR            = "Bras\xedlia"
  STR_CE            = "Cear\xe1"
  STR_DF            = "Distrito Federal"
  STR_ES            = "Esp\xedrito Santo"
  STR_GO            = "Goi\xe1s"
  STR_MT            = "Mato Grosso"
  STR_MS            = "Mato Grosso do Sul"
  STR_MG            = "Minas Gerais"
  STR_PA            = "Par\xe1"
  STR_PB            = "Para\xedba"
  STR_PR            = "Paran\xe1"
  STR_SC            = "Santa Catarina"
  STR_RN            = "Rio Grande do Norte"
  STR_RS            = "Rio Grande do Sul"
  STR_RJ            = "Rio de Janeiro"
  STR_RO            = "Rondônia"
  STR_RR            = "Roraima"
  STR_SP            = "São Paulo"
  STR_SE            = "Sergipe"
  STR_TO            = "Tocantins"
  STR_CPFNINF       = "CPF n\xe3o informado!"
  STR_SEXNINF       = "Sexo n\xe3o informado!"
  STR_CPFINV        = "CPF inv\xe1lido!"
  STR_TITNINF       = "T\xedtulo n\xe3o informado!"
  STR_ISBNINV       = "ISBN inv\xe1lido!"
  STR_NUMINV        = "Número inválido!"
  STR_LIVVENNINF    = "Livro(s) para vender n\xe3o informado(s)!"
  STR_LIVNEST       = "Livro n\xe3o existe no estoque!"
  STR_VENRESUC      = "Venda realizada com sucesso!"
  STR_VENNENC       = "Venda n\xe3o encontrada!"
  STR_BAIRRONINF    = "Bairro n\xe3o informado!"
  STR_CEPNINF       = "CEP n\xe3o informado!"
  STR_CIDADENINF    = "Cidade n\xe3o informada!"
  STR_NDCOBANCO     = "N\xe3o consigo desconectar com o banco de dados!"
  STR_NALOCHSTM     = "N\xe3o foi poss\xedvel alocar o manuseador para o procedimento!"
  STR_DESCPROC      = "N\xe3o conseguiu descrever o procedimento!"
  STR_NINITRAN      = "N\xe3o conseguiu iniciar a transa\xe7\xe3o!"
  STR_NLIBTRAN      = "N\xe3o conseguiu liberar a transa\xe7\xe3o!"
  STR_NFINTRAN      = "N\xe3o conseguiu finalizar a transa\xe7\xe3o!"
end
