#DEFINE CAMINHO_PADRAO 		"C:\LivrusVirtus\VFP6"
#DEFINE APP_GLOBAL          goApp
#DEFINE LIB_LIVRUS			"LivrusLib.vcx"
#DEFINE MENU_LIVRUS			"menuLivrus.mpr"
#DEFINE BARRA_LIVRUS		"tlbbarra"
#DEFINE FRM_SPLASH			"frmSplash"
#DEFINE FRM_LOGIN			"frmLogin"
#DEFINE FRM_SOBRE			"frmSobre"
#DEFINE ICONE_PRINCIPAL		CAMINHO_PADRAO + "\FIGURAS\Livrus.ico"

*--- Constantes do MensageBox
#DEFINE MB_OK						0
#DEFINE MB_OKCANCELAR				1
#DEFINE MB_ANULAR_REPETIR_IGNORAR	2
#DEFINE MB_ERRO						16
#DEFINE MB_INFORMACAO				64
#DEFINE MB_EXCLAMACAO				48
#DEFINE MB_INTERROGACAO				36
#DEFINE ID_SIM						6
#DEFINE ID_NAO						7
